- ReactiveUI.Testing/TestUtils.cs
- ReactiveUI.Tests/ReactiveUI.Tests_Net45.csproj
- ReactiveUI.Tests/TestUtilsTest.cs
This prevents `TestScheduler.WithAsync` from throwing a SynchronizationLockExceptionObject exception, because we can't `await` inside a Monitor
> Use an AutoResetEvent instead of a Monitor in TestScheduler.WithScheduler

- ReactiveUI/Cocoa/ReactiveNavigationController.cs
- ReactiveUI/ReactiveUI_iOS.csproj
I copied ReactiveTabBarController to make this, but changed the activation to be on ViewWillAppear instead of ViewDidAppear to line up with pull request #779.
Not sure if nobody has needed/wanted this yet or if it just a bad idea to make UINavigationController reactive.
> Added ReactiveNavigationController

- NuGet/ReactiveUI-AndroidSupport/ReactiveUI-AndroidSupport.nuspec
- ReactiveUI.AndroidSupport/ReactiveActionBarActivity.cs
- ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- ReactiveUI.AndroidSupport/packages.config
I created the reactive implementation for ActionBarActivity from Android AppCompat library.
I added this to the AndroidSupport library.
> Created ReactiveActionBarActivity

- docs/basics/reactive-command-async.md
The documentation seems to outdated, I was having compile error when trying to convert a command to property based on this example and realized that I should use `out` instead of `ref`
> Changes ref to out

- ReactiveUI.XamForms/XamForms/RoutedViewHost.cs
The problem is that RoutingState sets up NavigateAndReset to call Navigate.ExecuteAsync(). The Xam.Forms view host listens for NavigateAndReset, then calls PopToRootAsync() and then PushAsync().
This causes us to push the new page, pop to root, then push the new page again.
Instead of listening to NavigateAndReset in the view host, listen for the navigation stack to change to 0 and then call PopToRootAsync(), and let RoutingState execute Navigate as usual.
So, I haven't managed to build ReactiveUI itself yet. What I did was kind of janky I guess, but I copied `RoutedViewHost` into my own app and renamed the class and made these changes to it. I hope I haven't missed anything here. I'll try again to build ReactiveUI tomorrow so I can test this more properly.
> Fix Xamarin.Forms navigation so we don't go forward, backward, forward.

- ReactiveUI/Xaml/ActivationForViewFetcher.cs
While looking into https://github.com/reactiveui/ReactiveUI/issues/822, I found that the code was unnecessarily complex
> Simplify the Windows Phone ActivationForViewFetcher logic

- ReactiveUI.Tests/ReactiveNotifyPropertyChangedMixinTest.cs
- ReactiveUI/VariadicTemplates.cs
Whenever a property chain returns a `null` observable, an instance of `Observable.Empty<TRet>` is swapped in.
Happy to rearrange as you see fit. In particular, I wasn't sure about where I should put the `ObservableExtensions` helper class.
> Fixes #830.

- ReactiveUI/WeakEventManager.cs
This took a while to find but the number of handlers grows into the thousands when using Entry.Text bound to a string. This seems to have fixed the issue and greatly speeds up ReactiveUI.
See comments on the issue thread.
> Possible fix for issue #746

- ReactiveUI.Tests/INPCObservableForPropertyTests.cs
- ReactiveUI.Tests/ReactiveUI.Tests_Net45.csproj
- ReactiveUI/INPCObservableForProperty.cs
The documentation for [INotifyPropertyChanged.PropertyChanged](https://msdn.microsoft.com/en-us/library/system.componentmodel.inotifypropertychanged.propertychanged.aspx) says that `null` and `string.Empty` are valid values for the PropertyName and indicate that the whole object has changed. The current version of `INPCObservableForProperty` ignores such values.
This pull request adds support for these values and also adds tests for the `INPCObservableForProperty` class.
> Fix handling of null PropertyName values in INPCObservableForProperty

- ReactiveUI/PropertyBinding.cs
- ReactiveUI/Xaml/WpfDependencyObjectObservableForProperty.cs
Provide more meaningful messages when certain bindings fail
I've found a few places where exceptions are occurring due to improper usage in my application.
These changes helped me better know where I went wrong.
> Improve error exception logging

- ReactiveUI/Android/ReactiveActivity.cs
- ReactiveUI/Android/ReactiveFragment.cs
In some circumstances, the Xamarin Android framework already has a reference to an object, but needs to create it's peer MCW.  In these instances, the constructor that takes `(IntPtr, JniHandleOwnership)` is called.
This is detailed here: [Java Activation](http://developer.xamarin.com/guides/android/under_the_hood/architecture/#Java_Activation)
Also, an SO answer from @jonpryor discussing this a bit: http://stackoverflow.com/a/10603714/335675
This change adds the aforementioned constructors to both the `ReactiveActivity` and `ReactiveActivity<TViewModel>` classes.
> [Android] Add ReactiveActivity ctors for JNI ownership transfer

- NuGet/ReactiveUI-Core/ReactiveUI-Core.nuspec
This PR sets the lowest Splat version to 1.6.2. Fixes #889.
> Set Splat lowest version to 1.6.2.

- ReactiveUI.Tests/PropertyBindingTest.cs
- ReactiveUI/Xaml/AutoDataTemplateBindingHook.cs
This prevents ReactiveUI from setting a DataTemplate for simple cases
like a ComboBox that displays just a list of strings where there is no
need for a dedicated datatemplate
> Don't automatically create a DataTemplate, if the DisplayMemberPath of the ItemsControl is set

- ReactiveUI/ReactiveUI_Net45.csproj
- ReactiveUI/ReactiveUI_WP8.csproj
- ReactiveUI/ReactiveUI_WinRT.csproj
- ReactiveUI/ReactiveUI_WinRT80.csproj
- ReactiveUI/Xaml/Attributes.cs
This PR fixes #863 by adding the `XmlnsDefinition` attribute for supported XAML platforms. Consequently, XAML code can do this:
```XML
<Whatever x:rxui="http://reactiveui.net">
```
Unfortunately, the Xam Forms XAML layer does not support XmlnsDefinition nor (to my knowledge) anything equivalent to it, so for now you're stuck writing out crazy long namespace mappings on that platform.
> Add XmlnsDefinitionAttribute for those XAML platforms that support it.

- ReactiveUI.Tests/ObservableAsPropertyHelperTest.cs
- ReactiveUI/ObservableAsPropertyHelper.cs
Fixes #815.
The initial value is no longer piped through the scheduled subject. Instead, it is prepended to the source observable. Consequently, it is immediately available.
> Ensure ObservableAsPropertyHelper provides initial value immediately

- ReactiveUI.XamForms/XamForms/ViewModelViewHost.cs
Fixes #946 by checking the view's type and throwing a useful exception if it isn't a `Xamarin.Forms.View`.
> Throw a useful exception if the view is of the wrong type.

- NuGet/ReactiveUI-XamForms/ReactiveUI-XamForms.nuspec
- ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
- ReactiveUI.XamForms/packages.config
Fixes #948 by upgrading the XF dependency to latest.
Technically, RxUI does not have a binary dependency on the latest XF version, but I'm creating this under the assumption we want people to use the latest. Will discuss.
> Upgrade Xamarin Forms dependency.

- ReactiveUI/ReactiveUI_Net45.csproj
- ReactiveUI/ReactiveUI_WP8.csproj
- ReactiveUI/ReactiveUI_WinRT.csproj
- ReactiveUI/ReactiveUI_WinRT80.csproj
- ReactiveUI/Xaml/ReactiveUserControl.cs
This PR adds a `ReactiveUserControl<TViewModel>` for XAML platforms. It is the simplest possible thing that works and is intended to supersede #349 in the absence of a reason for the complexity of that solution.
> Add ReactiveUserControl for XAML platforms.

- ReactiveUI.XamForms/XamForms/ActivationForViewFetcher.cs
Fixes #949 by adding support for `View` activation.
The implementation is a little more awkward than we would like, but that's due to Xamarin Forms not exposing any lifecycle events for `View` objects. Instead, we have to hook into the lifecycle events of the view's hosting `Page`.
> Add support for View activation.

- ReactiveUI.XamForms/XamForms/ActivationForViewFetcher.cs
The code I wrote previously to detect parent changes for a `View` so that activation can be hooked is insufficient. We need to monitor all ancestors.
> Support ancestral parent changes in View activation.

- ReactiveUI.Tests/ReactiveCommandTest.cs
- ReactiveUI/ReactiveCommand.cs
If the `executeAsync` func throws an exception while creating the observable (i.e. synchronously), then this exception is lost by frameworks relying on `ICommand.Execute` - this swallows any exceptions returned from `ReactiveCommand.ExecuteAsync`.
This change ensures these exceptions are forwarded to `ThrownExceptions`, which would seem to be the expected behaviour.
Fixes #973
> Forward exceptions on creating execute observable to ThrownExceptions

- NuGet/ReactiveUI-AndroidSupport/ReactiveUI-AndroidSupport.nuspec
- ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs
- ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- ReactiveUI.AndroidSupport/packages.config
The `ReactiveRecyclerViewAdapter` is similar to the `ReactiveListAdapter` class, only for the `RecyclerView` control.
In the future I want to implement granular change notification updates, similar to the updates in `CommonReactiveSource` for Cocoa, we could probably even share some of the logic between Android and Cocoa.
> Implement a basic reactive adapter for the Android RecyclerView

- ReactiveUI.Tests/PropertyBindingTest.cs
- ReactiveUI/PropertyBinding.cs
If you `observable.BindTo(null, x => x.SomeProperty)`, the binding will fail when it tries to execute with the somewhat cryptic error message "Non-static method requires a target" and a stack trace that doesn't point you to where you Did It Wrong (tm).  Instead, I have `BindTo` throw an `ArgumentNullException` if its `target` paramter is `null`.
See #1017 for previous discussion.
> BindTo helpful error when binding to null.

- .hgeol
- ReactiveUI.Tests/DependencyResolverTests.cs
- ReactiveUI.Tests/ReactiveUI.Tests_Net45.csproj
- ReactiveUI/IDependencyResolver.cs
- ReactiveUI/Interfaces.cs
- ReactiveUI/ReactiveUI.csproj
- ReactiveUI/ReactiveUI_Net45.csproj
- ReactiveUI/ReactiveUI_WP8.csproj
- ReactiveUI/ReactiveUI_WinRT.csproj
- ReactiveUI/ViewAttributes.cs
The many lines of:
```csharp
resolver.Register(() => new FooView(), IViewFor<FooViewModel>);
resolver.Register(() => new BarView(), IViewFor<BarViewModel>);
... <etc> ...
```
Can be reduced to: `resolver.RegisterViewsForViewModels(typeof(FooView).Assembly)`
> Have a lot of Views? Hate registering each one? This PR is for you!

- ReactiveUI.Tests/ReactiveUI.Tests_Net45.csproj
- ReactiveUI.Tests/RoutableViewModelMixinTests.cs
- ReactiveUI/RoutableViewModelMixin.cs
I found I wanted to compose an existing observable with an observable version of `WhenNavigatedTo`, so that's what we've got here.
`WhenNavigatedToObservable()` returns an observable that fires events in the stream when the navigation stack is modified such that this VM is the topmost VM. To avoid leaking resources, it will fire `OnCompleted` when the VM is removed from the navigation stack. The alternative would be to have the user track this subscription and then dispose of it manually later, but I'm assuming that most of the time the calling VM is going to be thrown away when it no longer exists in the back stack. This removes a potential leak if the user fails to track the subscription.
`WhenNavigatingFromObservable` fires events just before another view model is added to the top of …
> adding observable version of WhenNavigatedTo, plus tests

- ReactiveUI/ReactiveCollectionMixins.cs
Firstly, there is little point defining an overload that takes a selector.
Callers can simply perform the selector themselves prior to invoking
CreateCollection.
Secondly, an overload that takes only a scheduler is very useful for unit
tests, because normally that's all they want to specify.
> Improve CreateCollection overloads.

- ReactiveUI.Tests/ReactiveCommandTest.cs
- ReactiveUI/ReactiveCommand.cs
Fixes a bug with RxCommands that take a nullable parameter type. Executing via `ICommand` and passing `null` as the parameter would throw:
```cs
ICommand command = ReactiveCommand.Create<int?>(p => {});
// this throws
command.Execute(null);
```
> Fix bug executing via ICommand with nullable parameter types.

- ReactiveUI/VariadicTemplates.tt
Ages ago I fixed a problem with WhenAnyObservable. However, I fixed it in
the source file and neglected to update the template file. This commit
rectifies this sorry state of affairs.
> Fix variadic template.

- ReactiveUI.XamForms/XamForms/RoutedViewHost.cs
When the user navigates back externally (e.g. by pressing back in the action bar), make sure we don't double count. That is, make sure we don't _also_ call `PopAsync` because obviously the user will navigate back two pages instead of one and the nav stack will be out of sync with the visible screen.
> Don't double-count when navigating back from external trigger.

- ReactiveUI.Tests/ReactiveCommandTest.cs
- ReactiveUI/ReactiveCommand.cs
As per discussion on Slack, RxCommand should deliver exceptions via the provided output scheduler.
> Ensure exceptions are delivered on output scheduler.

- ReactiveUI.Tests/ObservableAsPropertyHelperTest.cs
- ReactiveUI/ObservableAsPropertyHelper.cs
In order for Data Bindings to work properly, we need to signal the right property name, in the case of indexers.
> Make ToProperty work properly on Indexers

- ReactiveUI.Tests/RoutingState.cs
- ReactiveUI/RoutingState.cs
This PR adds a `Scheduler` property to `RoutingState`. If unset, it defaults to `RxApp.MainThreadScheduler`. If set, all commands are recreated with the specified scheduler.
I need this because I am lacking determinism in a suite of tests. The root cause is a lack of scheduling control with the commands created by `RoutingState`.
> Add RoutingState.Scheduler property.

- ReactiveUI.Tests/ObservedChangedMixinTest.cs
- ReactiveUI.Tests/ReactiveCommandTest.cs
- ReactiveUI.Tests/ReactiveNotifyPropertyChangedMixinTest.cs
- ReactiveUI.Tests/RoutableViewModelMixinTests.cs
- ReactiveUI.Tests/RoutingState.cs
- ReactiveUI.Tests/Winforms/RoutedViewHostTests.cs
- ReactiveUI/ReactiveCommand.cs
- ReactiveUI/RoutingState.cs
Fixes #1062 by:
* ensuring executing a reactive command returns a cold/lazy observable
* adding overloads of `ReactiveCommand.CreateFromTask` that work with `CancellationToken`
* renaming `ReactiveCommand.ExecuteAsync` to `ReactiveCommand.Execute`
> Cancellation support in RxCommand, plus better naming

- ReactiveUI/Activation.cs
- ReactiveUI/AddTo.cs
- ReactiveUI/DisposableMixins.cs
- ReactiveUI/ReactiveUI.csproj
- ReactiveUI/ReactiveUI_Android.csproj
- ReactiveUI/ReactiveUI_Mac.csproj
- ReactiveUI/ReactiveUI_Mac64.csproj
- ReactiveUI/ReactiveUI_Net45.csproj
- ReactiveUI/ReactiveUI_UWP.csproj
- ReactiveUI/ReactiveUI_WP8.csproj
- ReactiveUI/ReactiveUI_WinRT.csproj
- ReactiveUI/ReactiveUI_iOS.csproj
- ReactiveUI/ReactiveUI_iOS64.csproj
Fixes #1063 by adding `WhenActivated` overloads that work with `CompositeDisposable`, as well as a `DisposeWith` extension method to add a disposable to a `CompositeDisposable`.
Facilitates code that looks like this:
```cs
this
.WhenActivated(
disposables =>
{
this
.Bind(this.ViewModel, x => x.SomeProperty, x => x.someControl.SomeProperty)
.DisposeWith(disposables);
this
.BindCommand(this.ViewModel, x => x.SomeCommand, x => x.someButton)
.DisposeWith(disposables);
});
```
> WhenActivated and CompositeDisposable enhancements

- ReactiveUI.Tests/ObservableAsPropertyHelperTest.cs
- ReactiveUI/ObservableAsPropertyHelper.cs
> Subscribe to the source of an ObservableAsPropertyHelper immediately and add a deferSubscription parameter

- ReactiveUI/WaitForDispatcherScheduler.cs
Replace catching Exception into InvalidOperationException. We want to be explicit because i.e when System.Reactive.Windows.Threading is not attached then FileNotFoundException is thrown and causes using CurrentThreadScheduler instead of DispatcherScheduler. It may cause a lot of silent exceptions being thrown and usage of wrong dispatcher
> WaitForScheduler Exception handling

- ReactiveUI.XamForms/XamForms/ActivationForViewFetcher.cs
A change in XF behavior triggered this. Basically, views that are hidden by a dialog are no longer considered active, so their `OnDisappearing` triggers. This was causing problems for me because my main view (which extends `RoutedViewHost`) was disappearing and then reappearing.
Rather than attempt to fix the routing infrastructure (which I don't really want to touch ever again) I decided to make the XF activation-for-view-fetcher support `ICanActivate`. This allows me to circumvent the problem by implementing said interface on my main view such that it _never_ deactivates.
> Add support for ICanActivate.

- src/ReactiveUI.nuspec
appears that when targeting destination of "./" XS does not like it.
Successfully installed 'reactiveui-core 7.0.0.1460439208'.
Installing 'reactiveui 7.0.0.1467085873'.
Could not find a part of the path
"/var/folders/q3/954zjj750dx3rds3rvlpy8pwwd4mly/T/nuget/udgmfebb.wkc/RELEASENOTES.md".
> unship RELEASENOTES.MD as part of package due to XS + NuGet issue

- bootstrap.ps1
chore
Android API Levels 10-23 are automatically installed on the CI host (AppVeyor) before building the framework.
Android API 24 is also downloaded, thus 10-24 are automatically installed on the CI host (AppVeyor) before building the framework.
No
> chore: bootstrapper now download/installs Android API level 24

- src/ReactiveUI-AndroidSupport.nuspec
- src/ReactiveUI-Blend.nuspec
- src/ReactiveUI-Testing.nuspec
- src/ReactiveUI-Winforms.nuspec
- src/ReactiveUI-XamForms.nuspec
- src/ReactiveUI.nuspec
Bug fix for https://github.com/reactiveui/ReactiveUI/issues/1147
Dependencies are pinned to a version that does not exist.
Pin the version to the exact same version that is being built.
No
fixes #1147
> fix: set nuspec dependency to == (exact) version as that is being built

- src/ReactiveUI.Events/ReactiveUI.Events_XamForms.csproj
- src/ReactiveUI.Events/packages.ReactiveUI.Events_XamForms.config
Feature (and CI chore)
Generate ReactiveUI-Events for Xamarin.Forms v2.2.0.31
Generate ReactiveUI-Events for Xamarin.Forms v2.3.1.114
No
This also resolves a build error as the EventsGenerator will download the latest version of Xamarin Forms from NuGet and codegen eventhandlers from that. Now, if a new major/minor is …
> feat: upgrade reactiveui-events for Xamarin.Forms from v2.2.0.31 to v2.3.1.114

- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
- src/ReactiveUI.XamForms/packages.config
feature
reactiveui-core targets from v2.2.0.31
reactiveui-core retargeted from v2.2.0.31 to v2.3.1.114
no
>  feat: upgrade reactiveui-core for Xamarin.Forms from v2.2.0.31 to v2.3.1.114

- src/ReactiveUI-XamForms.nuspec
Feature
```
<dependencies>
<dependency id="reactiveui-core" version="$version$" />
<dependency id="Xamarin.Forms" version="2.1.0.6529" />
</dependencies>
```
```
<dependencies>
<dependency id="reactiveui-core" version="$version$" />
<dependency id="Xamarin.Forms" version="2.3.1.114" />
</dependencies>
```
No
> feat: update reactiveui-xamforms nuspec dependency from v2.1.0.6529 to v2.3.1.114

- bootstrap.ps1
bugfix for chore
API 24 attempts to be installed but fails as SDK Manager is at v23 which results in a failed build.
API 24 is not installed, when AppVeyor is upgraded this commit should be reverted.
No
This reverts commit 2a37bc12181dc715c9723aaf5fb38f338ce0f8c9.
> revert: "chore: bootstrapper now download/installs Android API level 24

- appveyor.yml
Chore
New version of the Sonarcube agent has been published and in doing so they have changed the command line arguments (breaking change) without notifying consumers. 
https://sonarqube.com/dashboard/index?id=ReactiveUI
Disabled Sonarqube until have more time to investigate. Builds will be green after this change is merged in.
No
> chore: resolve build failures by disabling sonarqube integration

- src/ReactiveUI.Testing/ReactiveUI.Testing_iOS.csproj
Refactor
`reactiveui-testing` for iOS targets Monotouch which has been obsoleted by Xamarin and no longer compiles. Project does not compile because of this.
Migrated to Xamarin.iOS
No
**Other information**
> refactor: reactiveui-testing for iOS migrated from Monotouch to Xamarin.iOS

- build.cake
- src/ReactiveUI.Tests/WeakEventManagerTest.cs
refactor/feature/chore
Unit tests are not run by CI.
The CI runs the NET45 flavour of unit tests on `reactiveui-core`
No
There is a failing unit test which must be resolved before this PR can be merged.
> run unit tests as part of continuous integration pipeline

- src/Microsoft.Reactive.Testing/Microsoft.Reactive.Testing_Mac.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing_Mac.csproj
- src/ReactiveUI/ReactiveUI_Mac.csproj
refactor
`reactiveui-events` uses Xamarin.Mac as target framework.
`reactiveui` uses NET45 as target framework.
`reactiveui-testing` uses NET45 as target framework.
`Microsoft.Reactive.Testing_Mac` uses NET45 as target framework.
Xamarin.Mac used as target framework for all of above instead of NET45. This resolves a few `msbuild` compiler warnings.
No
> refactor: use xamarin.mac framework for reactiveui/reactiveui-testing/microsoft-reactive-testing

- src/EventBuilder/DefaultTemplate.mustache
refactor/chore on `reactiveui-events`
CS[1591,0618,0105,0672] are enabled and spam the build logs with useless information which makes reviewing the logs harder. We don't need these warnings because `reactiveui-events` is all automatically code generated.
CS[1591,0618,0105,0672] are disabled
No
> refactor: ignore CS[1591,0618,0105,0672] on reactiveui-events because that code is codegened

- src/ReactiveUI/Android/AndroidObservableForWidgets.cs
- src/ReactiveUI/Android/LinkerOverrides.cs
refactor
`.Current[Hour|Minute]` is used in the prayer to the linker gods and also in the WidgetsObservables. These two properties have been `[Obsoleted]`.
Use `.Hour|Minute` instead.
https://developer.android.com/guide/topics/ui/controls/pickers.html
https://developer.xamarin.com/guides/android/user_interface/time_picker/
No
> refactor: android timepicker use .Hour|Minute instead of .Current[Hour|Minute]

- src/ReactiveUI.Tests/ReactiveNotifyPropertyChangedMixinTest.cs
- src/ReactiveUI/VariadicTemplates.cs
- src/ReactiveUI/VariadicTemplates.tt
Feature.
The `WhenAnyObservable` operator does not work in the same fashion as other `WhenAny*` operators. All observables must be the same type, and the resulting observable sequence is the result of a `Merge` of those observables. Consider this:
```C#
public IObservable<bool> First { ... }
public IObservable<bool> Second { ... }
public IObservable<string> Third { ... }
// elsewhere
this
.WhenAnyObservable(x => x.First, x => x.Second)
.Select( /* er, umm, how do I distinguish whether the value came from First or Second? */ )
// somewhere else
this
.WhenAnyObservable(x => x.First, x => x.Third)  // oops, this is not even possible …
```
> Add WhenAnyObservable overloads that combine latest

- src/ReactiveUI.XamForms/XamForms/ViewModelViewHost.cs
Bug fix.
Crash when using `ViewModelViewHost` on XF.
Fix the `BindableProperty` metadata on `ViewModelViewHost`.
No.
> fix: resolve crash when using ViewModelViewHost with Xamarin Forms

- README.md
doc
Directed the community to send Paul an email to obtain an invite.
Directed the community to send Geoff an email to obtain an invite.
no
> docs: email geoff, not paul for slack invitation

- src/ReactiveUI.Tests/ReactiveCommandTest.cs
- src/ReactiveUI/ReactiveCommand.cs
Hi! I've described my issue today on the slack channel but nobody replies to me so I found the problem myself :smile: That's my original message:
[SlackMessage]
Hello everyone! I have a problem: the `ViewModel` is leaking if I use any property of the `Model` inside `canExecute` argument of any `ReactiveCommand`. The `Model` lives for the entire life of the application but `ViewModel` should be removed when I close its tab. I use RxUI 7.0. The example:
```c#
var canDeepCopy = this.WhenAnyValue(vm => vm.Model.Id).Select(id => id != Constants.NewEntityId);
this.DeepCopy = ReactiveCommand.Create(this.HandleDeepCopy, canDeepCopy);
```
If I replace `canDeepCopy` value by `Observable.Return(true)` `ViewModel` is not leaking anymore. I even tried to dispose `DeepCopy` command but it didn't give …
> fix: subscription leakage in ReactiveCommand

- src/ReactiveUI/Android/ControlFetcherMixin.cs
This will allow `WireUpControls()` to wire up View properties, and not just subclasses of it.
`WireUpControls()` doesn't currently wire up View properties, just subclasses.
`WireUpControls()` now also wires up View properties.
It shouldn't, unless you were expecting `null` values on your View properties. If you were working around this with manual `FindViewById` calls you're assigning the same view twice to the same property, worst-case. (Considering you weren't using duplicate names for views or controls in the first place.) …
> feature: allow WireUpControls to find View members

- src/ReactiveUI/Cocoa/ReactiveCollectionReusableView.cs
- src/ReactiveUI/Cocoa/ReactiveCollectionView.cs
- src/ReactiveUI/Cocoa/ReactiveCollectionViewCell.cs
- src/ReactiveUI/Cocoa/ReactiveCollectionViewController.cs
- src/ReactiveUI/Cocoa/ReactiveControl.cs
- src/ReactiveUI/Cocoa/ReactiveImageView.cs
- src/ReactiveUI/Cocoa/ReactiveNSView.cs
- src/ReactiveUI/Cocoa/ReactiveNSViewController.cs
- src/ReactiveUI/Cocoa/ReactiveNavigationController.cs
- src/ReactiveUI/Cocoa/ReactivePageViewController.cs
- src/ReactiveUI/Cocoa/ReactiveSplitViewController.cs
- src/ReactiveUI/Cocoa/ReactiveTabBarController.cs
- src/ReactiveUI/Cocoa/ReactiveTableView.cs
- src/ReactiveUI/Cocoa/ReactiveTableViewCell.cs
- src/ReactiveUI/Cocoa/ReactiveTableViewController.cs
I've added generic versions of every Reactive ViewController and View / Control on iOS and Mac to allow easier assignment of ViewModels with such classes. 
We use these classes in all of our projects, and it's kind of cumbersome to copy them every time, or to create a special package.
It's also spoken of in https://github.com/reactiveui/ReactiveUI/issues/1029.
You have to create/add these versions to all of your projects.
They're factory-installed!
It shouldn't, since the non-generic versions are still there. I took the …
> feature: added generic reactive controllers and views for iOS and Mac

- src/ReactiveUI-AndroidSupport.nuspec
- src/ReactiveUI-Blend.nuspec
- src/ReactiveUI-Testing.nuspec
- src/ReactiveUI-Winforms.nuspec
- src/ReactiveUI-XamForms.nuspec
- src/ReactiveUI.nuspec
Bug fix.
The packages are unpinned; `version="$version$"` means "Minimum version, inclusive" as per https://docs.nuget.org/ndocs/create-packages/dependency-versions
The packages are now pinned; `version="[$version$]"` means "Exact version match" as per https://docs.nuget.org/ndocs/create-packages/dependency-versions
No, even if it did we don't want to support this behaviour. For maintainer sanity, we version ReactiveUI and package as a pinned group - all packages in a release will always be the same version and only work with …
>  fix: reactiveui packages should be pinned and only work with packages from the same release

- src/Microsoft.Reactive.Testing/Microsoft.Reactive.Testing_Android.v3.ncrunchproject
- src/Microsoft.Reactive.Testing/Microsoft.Reactive.Testing_Mac.v3.ncrunchproject
- src/Microsoft.Reactive.Testing/Microsoft.Reactive.Testing_iOS.v3.ncrunchproject
- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.v3.ncrunchproject
- src/ReactiveUI.Blend/ReactiveUI.Blend_Net45.v3.ncrunchproject
- src/ReactiveUI.Blend/ReactiveUI.Blend_UWP.v3.ncrunchproject
- src/ReactiveUI.Blend/ReactiveUI.Blend_WinRT.v3.ncrunchproject
- src/ReactiveUI.Testing/ReactiveUI.Testing_Android.v3.ncrunchproject
- src/ReactiveUI.Testing/ReactiveUI.Testing_Mac.v3.ncrunchproject
- src/ReactiveUI.Testing/ReactiveUI.Testing_Net45.v3.ncrunchproject
- src/ReactiveUI.Testing/ReactiveUI.Testing_UWP.v3.ncrunchproject
- src/ReactiveUI.Testing/ReactiveUI.Testing_WinRT.v3.ncrunchproject
- src/ReactiveUI.Testing/ReactiveUI.Testing_iOS.v3.ncrunchproject
- src/ReactiveUI.Winforms/ReactiveUI.Winforms_Net45.v3.ncrunchproject
- src/ReactiveUI.v3.ncrunchsolution
- src/ReactiveUI/ReactiveUI.v3.ncrunchproject
- src/ReactiveUI/ReactiveUI_Android.v3.ncrunchproject
- src/ReactiveUI/ReactiveUI_Mac.v3.ncrunchproject
- src/ReactiveUI/ReactiveUI_UWP.v3.ncrunchproject
- src/ReactiveUI/ReactiveUI_WinRT.v3.ncrunchproject
- src/ReactiveUI/ReactiveUI_iOS.v3.ncrunchproject
Add NCrunch v3 configuration files. All projects other than NET45 are
ignored, meaning this is for running tests on Windows (the only platform
NCrunch supports).
Developer tooling.
No NCrunch config, meaning NCrunch users such as myself either forgo it or add config each time they pull ReactiveUI source afresh.
Add NCrunch v3 configuration files.
No.
> chore: add NCrunch configuration

- src/ReactiveUI.Tests/InteractionsTest.cs
- src/ReactiveUI/Interactions.cs
> feature: allow interaction handlers of any observable type

- build.cake
**Do you want to request a *feature* or report a *bug*?**
chore/bug
When a build starts, the initial identifier is an auto-incremented value supplied by AppVeyor. As part of the build script, this version in AppVeyor is changed to be the version obtained from GitVersion. This identifier is purely cosmetic and is used by the core team to correlate a build with the pull-request.
In some circumstances, such as restarting a failed/cancelled build the identifier in AppVeyor will be already updated and default behaviour is to throw an exception/cancel the build when in fact it is safe to swallow or append additional metadata (like the epoch when the build was started)
**What is the expected behavior?**
This throwing should not be a fatal build error …
> chore: failing to set the appveyor version should not be a fatal build error

- src/ReactiveUI/CommandBinding.cs
- src/ReactiveUI/ReactiveBinding.cs
Tidying comments in a couple of binding related files.
> style: tidy up comments for ReactiveBinding and command binding

- src/ReactiveUI/Activation.cs
More comment tidying, in Activation this time
> style: tidy up and expand comments in Activation

- src/ReactiveUI.Tests/PropertyBindingTest.cs
- src/ReactiveUI.Tests/Utility.cs
feat:, style: add an XUnit attribute to allow test running on invariant culture, this will avoid failed tests because of e.g. decimal separator differences
feature to prevent failed tests because of culture dependent decimal separators
TwoWayBindWithFuncConvertersSmokeTest will fail on German locale
TwoWayBindWithFuncConvertersSmokeTest will succeed on German locale
No!
- [X ] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
[Fact, …
> fix: add UseInvariantCultureAttribute and apply to relevant tests

- src/ReactiveUI.XamForms/XamForms/RoutedViewHost.cs
Removed a buggy checkin with attempting to replace TPL with ToObservable.  I tried changing the SelectMany to correctly return the Observables and the Do went back to being on the Thread Pool.  So for now I just moved the assignment of the VM up to the finally block of the SelectMany
The VM gets assigned in the Do block. 
It shouldn't
> fix: assign VM from correct thread in RoutedViewHost

- src/ReactiveUI.Tests/ViewLocatorTests.cs
- src/ReactiveUI/ViewLocator.cs
Fixes a regression introduced recently by #1282 whereby the runtime type of the provided view model is not considered when resolving the view.
Runtime type ignored, only generic type considered.
The runtime type is considered first, followed by the generic type as required.
No, it fixes one.
> fix: prefer runtime type when resolving views

- src/ReactiveUI/CompatMixins.cs
Refactoring.
Unused extension method, class that's public but exposes nothing.
No unused extension method, class that's internal only.
Shouldn't do, unless someone is using the CompatMixins clas somehow.
Found this whilst reviewing XML docs, this felt like a better thing to do than a comment that says "nothing to see here"
> refactor: removed unused extension method and make class internal

- src/ReactiveUI/Android/ControlFetcherMixin.cs
This clarifies the exception you get when `ControlFetcherMixin` collects the names of resource ID's in your layout files. It shows you for which ID's it's exactly failing so it's easier to find which names are the culprit.
When you have duplicate names with different casings in use as resource ID's, you get a fairly generic `ArgumentException` which is hard to understand without diving into the code of `ControlFetcherMixin`.
We throw a more explanatory `InvalidOperationException` which shows which names should be fixed to get things going.
**Does this PR introduce a …
> Clarified exception when WireUpControls fails

- src/ReactiveUI/Xaml/ViewModelViewHost.cs
Bug fix
The ViewModelViewHost leaks memory on XAML platforms.
The subscription to the SizeChangedEvent will be disposed via WhenActivated and it no longer leaks memory.
No
> Fix ViewModelViewHost memory leak

- src/ReactiveUI.Tests/ViewLocatorTests.cs
- src/ReactiveUI/ViewLocator.cs
Fix
#1299 and #1298 the view locator doesn't correctly resolve a couple of cases, and can't handle oddly named interfaces well.
Handle IRoutableViewModel style VMs, and handle interfaces that don't meet conventions.
It sort of undoes a breaking change introduced in 7.2 with the refactorings around the view locator.
This could conceivably be two separate PRs, but I think it's actually clearer to do it in one
> View locator changes

- src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
housekeeping to make contributing easier
Contributors would need to install a specific SDK
We use the NuGet package instead, removing this pain!
Nope
> housekeeping: retrieve System.Windows.Interactivity from NuGet so contributors don't need to install the SDK

- GitReleaseManager.yaml
Housekeeping
updated GitReleaseManager configuration to match the GitHub label changes introduced as part of the upcoming netstandard release.
no
> housekeeping: github labels updated to rename uwp & wpf, drop windows phone/store, add tizen

- README.md
Remove duplicate slack section in README - I don't think it adds much to have it twice, and means it has to be changed twice if anything happens.
> housekeeping: remove duplicate Slack section

- build.cake
Fix ish. Remove the "Core" publish target, which was removed during the merge.
It's possible that the target should actually be kept, in which case we need to reinstate it in nuget/csproj generation.
> chore: don't publish ReactiveUI-Core as package no longer exists

- build.cake
bugfix/housekeeping/chore. 
RxUI v7.x had verisons pinned; we merged the v8 into develop without pinning.
Pinning is reintroduced. See https://github.com/cake-contrib/Cake.PinNuGetDependency
Nope
> fix: pin child packages of our main project be locked to the version that's being built

- .gitignore
Make life easier for Mac users.
.DS_Store files generated by macOS constantly screw up your `git status`.
Ignore .DS_Store files, since they're of no interest.
Nope
> housekeeping: add .DS_Store files to .gitignore

- .gitignore
A little tidying up after #1332.
An extra file is gitignored
It's not gitignored, but it's also not included either.
No.
> chore: remove CommonAssemblyInfo from git

- src/ReactiveUI/Platforms/windows-common/PlatformOperations.cs
housekeeping
```
#if WINRT80
return Windows.Graphics.Display.DisplayProperties.CurrentOrientation.ToString();
#elif NETFX_CORE
```
```
-#if WINRT80
-            return Windows.Graphics.Display.DisplayProperties.CurrentOrientation.ToString();
-#elif NETFX_CORE
```
no
This is the last trace of WINRT80
```shell
reactiveui\ReactiveUI$ ack WINRT80
<nothing>
```
> housekeeping: removed dead code that references WINRT80

- GitVersion.yml
housekeeping
```
C:\dropbox\oss\reactiveui\ReactiveUI [develop ≡ +1 ~1 -0 !]> .\tools\GitVersion.CommandLine\tools\GitVersion.exe
{
"Major":7,
"Minor":5,
"Patch":0,
"PreReleaseTag":"alpha.32",
"PreReleaseTagWithDash":"-alpha.32",
"PreReleaseLabel":"alpha",
"PreReleaseNumber":32,
"BuildMetaData":"",
"BuildMetaDataPadded":"",
"FullBuildMetaData":"Branch.develop.Sha.7221f582afccc9a10878c99874ef4a0d91871e3d",
"MajorMinorPatch":"7.5.0",
"SemVer":"7.5.0-alpha.32",
"LegacySemVer":"7.5.0-alpha32",
"LegacySemVerPadded":"7.5.0-alpha0032",
"AssemblySemVer":"",
"FullSemVer":"7.5.0-alpha.32", …
```
> housekeeping: bumped next version to be v8

- src/ReactiveUI/Legacy/ReactiveCommand.cs
update to xmldocs
Creates a warning.
Doesn't create a warning.
Ish...I've renamed a couple of parameters to try and be more consistent, happy to not make this change though if we're worried people are using extension methods with explicitly named params for the `this` argument
Rebracer seems to have taken issue at the formatting of the file as it was...
> Tidy up comments in legacy ReactiveCommand

- appveyor.yml
chore
Uses -stable virtual machine on AppVeyor
Uses -preview virtual machine on AppVeyor
No end user breaking changes, this affects where we compile from. @onovotny recommends going up to 2017 preview to obtain fixes for compiling project SDK packages. For a maintainer - I'd recommend creating a virtual machine for ReactiveUI development running VS2017 preview if you are going to get heavily involved with msbuild stuff. For simple PR's then you are a-okay staying with -stable.
**Other …
> chore: use pre-release visual studio 2017 sdk to work around tooling issues

- src/ReactiveUI.Tests/ActivationTests.cs
- src/ReactiveUI.Tests/AutoPersistHelperTest.cs
- src/ReactiveUI.Tests/CommandBindingTests.cs
- src/ReactiveUI.Tests/DependencyResolverTests.cs
- src/ReactiveUI.Tests/MessageBusTest.cs
- src/ReactiveUI.Tests/ObservableAsPropertyHelperTest.cs
- src/ReactiveUI.Tests/Platforms/winforms/ActivationTests.cs
- src/ReactiveUI.Tests/Platforms/winforms/DefaultPropertyBindingTests.cs
- src/ReactiveUI.Tests/Platforms/xaml/ActivationForViewFetcherTest.cs
- src/ReactiveUI.Tests/Platforms/xaml/DependencyObjectObservableForPropertyTest.cs
- src/ReactiveUI.Tests/PropertyBindingTest.cs
- src/ReactiveUI.Tests/ReactiveCollectionTest.cs
- src/ReactiveUI.Tests/ReactiveCommandTest.cs
- src/ReactiveUI.Tests/ReactiveNotifyPropertyChangedMixinTest.cs
- src/ReactiveUI.Tests/ReactiveObjectTest.cs
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
- src/ReactiveUI.Tests/RoutingState.cs
- src/ReactiveUI.Tests/RxAppTest.cs
- src/ReactiveUI.Tests/TestConfiguration.cs
- src/ReactiveUI.Tests/TestUtilsTest.cs
Fixes #1301
Uses xunit 1.9.x
Use xunit 2.x
Unlikely, this shouldn't be being consumed by end users anyway.
The biggest change that impacts this is the threading model for xunit 2 has changed a bit, so some tests are marked as STA or WPF which ensures they're running on the right thread.
I'm a little concerned the tests could be a bit flaky because of the changes, so one thing I'm keen for this PR to do is build it on a different machine.
If tests are …
> chore: update to xunit 2

- appveyor.yml
housekeeping
Used my personal account (which is using the free tier)
Uses the .NET foundation AppVeyor account (which is paid for and very 🚤 🚓 ⏩ )
If I stuffed up the encryption of secrets for the `master` branch then we won't know until we go to release (the cakebuild will break). Fortunately that situation is easy to fix if it was to happen. 
> housekeeping: use .NET foundation appveyor infrastructure

- src/ReactiveUI/IDependencyResolver.cs
chore
Registration methods were duplicated in ReactiveUI and Splat.
Remove the duplicate methods from ReactiveUI.
People who explicitly used the RxUI methods. They should just use the Splat ones instead.
> chore: cull Splat methods that were never removed

- .gitignore
- appveyor.yml
- build.cake
- src/Directory.build.props
Fix for #1420
Appveyor is old version
Appveyor is preview builds
Hopefully nothing
Have raised a ticket on Cake, as the VSWhere tool we're using doesn't currently include pre-release builds, so VS can't find what it's doing. The build is falling back to MSBuild 14, which doesn't support new csprojs, hence breaking the build.
Cake ticket https://github.com/cake-build/cake/issues/1754, notes on vswhere prerelease flag …
> resolve red builds on the develop branch after VS2017 15.3

- GitReleaseManager.yaml
housekeeping
DNF labels would cause GRM to fail/we would not be able to release.
Ignore all DNF labels 
This will unbreak the release of v8.0.0; haven't discovered this yet because no releases have been done since joining the .NET foundation. GRM has a limitation (https://github.com/GitTools/GitReleaseManager/issues/90) where an issue can only belong to one label.
> housekeeping: ignore cla github labels otherwise release will break

- .github/stale.yml
housekeeping feature
GitHub issues (inc pull-requests) linger causing maintainer and user frustration.
A friendly robot automatically closes out issues which have no activity and reminds people that if they want the issue progressed then the best way to progress it is to ask a maintainer how. 
```
daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
- up-for-grabs
- starters
- bug
- cla-signed
- cla-already-signed
```
All GitHub issues (inc PR) that are older than 60 days of inactivity will need a bump of human activity within seven days of the …
> housekeeping: automatically close stale github issues in a friendly way

- src/Directory.build.targets
- src/ReactiveUI/Platforms/net45/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/netcoreapp1.0/PlatformRegistrations.cs
- src/ReactiveUI/ReactiveUI.csproj
Support for a .NET Core non-crashing build.
Any .NET Core usage of ReactiveUI will crash.
A .NET Core build will not crash upon load. The user must supply a scheduler for the `RxApp.MainThreadScheduler` depending on their platform.
Nothing.
Fixes #1417
> Add netcoreapp build

- src/ReactiveUI/ViewAttributes.cs
The ViewContractAttribute.Contract property is currently internal but to build a custom service locator, which supports view contract attribute, we need access to it.
> core: make ViewContractAttribute.Contract public

- .github/stale.yml
More options when triaging
See `.github/stale.yml` for current.
- Often I find myself doing triage and I just don't know (`¯\_(ツ)_/¯`) what to do with it but think the issue should be addressed. If you come across a `¯\_(ツ)_/¯` then that's an opportunity to help me and the other maintainers out. 
- `bug` now means an actual verified bug with an attached test case w/implicit understanding for maintainers (or community - yes please) should PR it. 
- There's sometimes long running discussions the maintainers want to have with a community - an proposal. 
**What might this PR …
> housekeeping: ¯\_(ツ)_/¯ and proposal labels won't be autoclosed

- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.Events/ReactiveUI.Events.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI/ReactiveUI.csproj
bug fix
Blocked by https://github.com/NuGet/Home/issues/5751
Fixes #1413 by bypassing NuGet issue @ https://github.com/NuGet/Home/issues/5751
Use https://docs.microsoft.com/en-us/nuget/reference/package-versioning when reviewing
System.Reactive v4.x and NuGet.exe needs more time to mature. We can remove these restrictions as a point release at a later point in time. Dynamic data is currently using `3.1.1` as min but is not clamped @RolandPheasant I strongly …
> fix: restrict system.reactive to 3.1.1 as min but never 4.x series

- src/Directory.build.targets
**Do you want to request a *feature* or report a *bug*?**
Bug
> In this you have the TargetPlatformVersion, but you also probably want to specify the TargetPlatformMinVersion. It defaults to 10.0.10240.0...and that version isn't even in support anymore :)
https://github.com/reactiveui/ReactiveUI/blob/ece4833e2712048851ac01e7b6285fd33681ebeb/src/Directory.build.targets#L10
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See https://github.com/akavache/Akavache/issues/370
**What is the expected behavior?**
See https://github.com/akavache/Akavache/issues/370
**What is the motivation / use case for changing the behavior?**
See https://github.com/akavache/Akavache/issues/370
> fix: set UWP min version to 10.0.10586.0

- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
Fixes #1340 
Fixes #1370 (this PR supersedes that one)
`reactiveui-testing` does not have a netstandard build.
We now have a `netstandard1.1` build (as well as all the other existing builds)
No.
In #1370 Kent attempted to replace all platforms a single netstandard target but we couldn't get it working. I had to keep keep all the other platforms otherwise system.reactive.interfaces blows up when installed into net45. NuGet resolved 3.0.0 when I …
> fix: added netstandard 1.1 build and added system.reactive references

- build.cake
housekeeping
- appveyor internal build numbers are updated w/build information
- this information is 💄 and not functional
- if a build failed and 💄 had been updated, then retrying builds would also fail
- FIXED; just use the autonumber provided to us by appveyor
- 🔥  💄 🔥 
If green then ready to 🚢 
> housekeeping: improve stability of CI when re-running a failed build

- src/ReactiveUI.Tests/MessageBusTest.cs
Changes a test that sometimes goes 💥 
MessageBus test sometimes doesn't do what's expected, because using tasks doesn't necessarily make any guarantees about threading,
Explicitly use a new thread, which should make sure things happen as we'd expected.
Nothing.
Spotted in #1470 but I don't think it's a unique scenario.
> test: use new threads explicitly in message bus test

- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
Bug fix the compile.
compile fails due to event generator grabbing latest nuget, but the events project referencing older version.
This also fixes #1492 
Now referencing Xamarin 2.4
Clients referencing the old 2.4 release.
> feature: bumped to xamarin forms 2.4

- appveyor.yml
feature(https://github.com/reactiveui/ReactiveUI/issues/1488)
when appveyor fails, binlogs artifact is not being uploaded
binlogs artifact is published even if the build failed
appveyor build :cry: 
> housekeeping: upload msbuild binlogs even when the build fails

- src/ReactiveUI.AndroidSupport/ReactiveAppCompatActivity.cs
feature
https://github.com/reactiveui/ReactiveUI/issues/1329
More details were mentioned [here](https://github.com/reactiveui/ReactiveUI/pull/841).
* Couldn't find any tests for a similar use case, but if you can think of anything I can cover here, please let me know.
> ReactiveAppCompatActivity was missing ctors for JNI ownership transfer

- GitReleaseManager.yaml
housekeeping
product named incorrectly
product named correctly
must rename github label as well otherwise gitreleasenotes will break.
> housekeeping: the f in wpf is foundation, not framework

- README.md
I added stackoverflow link to the reactiveui tagged questions.
> housekeeping: fixed broken link to stackoverflow

- samples/xamarin-forms/Cinephile/Cinephile.csproj
- samples/xamarin-forms/Cinephile/packages.config
- samples/xamarin-forms/Droid/Cinephile.Droid.csproj
- samples/xamarin-forms/Droid/MainActivity.cs
- samples/xamarin-forms/Droid/packages.config
- samples/xamarin-forms/iOS/Cinephile.iOS.csproj
- samples/xamarin-forms/iOS/packages.config
Bug fix and upgraded xamarin forms version
Currently in OnDestroy on the MainActivity it was calling BlobCache.Shutdown which completely shuts down the cache from ever being used again. In cases where the MainActivity is destroyed but static things stay in memory this caused the app to stop working.
you could recreate by
- app started
- click back button to minimize app (this destroys the main activity)
- start app back up and nothing renders
```
protected override void OnDestroy()
{
BlobCache.LocalMachine.Flush().Wait();
base.OnDestroy();
}
```
Here's a longer discussion …
> docs: upgraded version of xam forms and changed ondestroy to use flush instead of shutdown

- samples/xamarin-forms/Cinephile/Views/UpcomingMoviesListView.xaml
Since this was fixed https://github.com/reactiveui/ReactiveUI/pull/1270 we don't need to rely on a ViewModel="{Binding .}" anymore.
samples update
The list binding on Cinephile was done as `ViewModel="{Binding .}"`
Removed the XAML binding since after RxUI 7.2 this is not necessary anymore
nothing
> fix: remove ViewModel="{Binding .}" from Cinephile

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
- src/ReactiveUI.Tests/ObservableAsPropertyHelperTest.cs
- src/ReactiveUI/ObservableAsPropertyHelper.cs
Introduces a IsSubscribed property to the OAPH. 
No property and therefore no easy way to know if a subscription (and therefore the value) has changed. This addresses #1491
A property in the OAPH
Shouldn't break any existing code.
> feature: add IsSubscribed property to ObservableAsPropertyHelper<T>

- src/EventBuilder/Cecil/EventTemplateInformation.cs
- src/EventBuilder/DefaultTemplate.mustache
- src/EventBuilder/Entities/ObsoleteEventInfo.cs
- src/EventBuilder/Entities/PublicEventInfo.cs
feature
#1508 
If source event has [Obsolete] attribute generated event also will has it. Additional properties like Message, IsError are also passed.
nothing
btw Visual Studio automatically format some code in `EventTemplateInformation.cs`. Some discussion already started about that at slack.
> feat: propagate obsolete attributes to generated observables

- src/EventBuilder/Platforms/Android.cs
feature
Builds don't work if you upgrade VS2017 to latest (#1517)
Pin events to MonoAndroid 7
Upgrading to 8, potentially, but gives us a way to pin in future which I think mitigates
Temporarily fixes #1517
> feature: pin android sdk version to keep generated events in line in line with build target

- src/ReactiveUI.Tests/app.config
Remove fully qualified test names in test explorer.
#1328 
-
-
I'm having serious problems getting solution building in Visual Studio (do you have pre-requisities listed anywhere?). So I've not been able to verify this fix in VS. However, output from build scripts seems to remove fully qualified name from tests.
> housekeeping: remove fully qualified test names in test explorer (#1328)

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
- src/ReactiveUI.Tests/ObservableAsPropertyHelperTest.cs
- src/ReactiveUI.Tests/ReactiveObjectTest.cs
- src/ReactiveUI/ObservableAsPropertyHelper.cs
…yHelper, which allows use of the nameof() operator for performance based applications
Address #1505 - It adds a string overload of the ToProperty operator that can be used with the nameof() operator or later a fody. This helps when you have a large number of objects referencing a OAPH object.
To use the Expression<Func<>> to interpolate the name of the OAPH.
Adds a additional mixin that allows the use of a string. 
Since it's just adding a new override it shouldn't break existing use of the Expression. If other people have provided similar …
> feature: nameof() overload for ObservableAsPropertyHelper mixin

- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
fix
https://github.com/reactiveui/ReactiveUI/issues/1526
Unbreaks people, if an item is missed in the review then potentially a platform might remain broken etc.
> fix: this.Events() was not available for consumption due to assembly name conflicts

- src/ReactiveUI.Tests/ReactiveCommandTest.cs
- src/ReactiveUI/ReactiveCommand.cs
fixes
1. `InvokeCommand` relies on Rx's `WithLatestFrom` operator, which is...weird. It subscribes to first observable first, and then the second, which can result in missing values.
2. Multiple in-flight command executions are not supported. More specifically, a count of in-flight executions is not kept, so it behaves a little weird (saying it can execute when another execution may be in flight).
3. Disposing of an in-flight execution subscription is now handled correctly. Fixes #1525.
1. `InvokeCommand` relies on our own custom `WithLatestFromFixed` operator, which …
> fix: several ReactiveCommand bugs

- src/EventBuilder/Platforms/XamForms.cs
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
Bug fix (build).
The release of Xamarin.Forms 2.5 broke the build. Here's what happened, to the best of my understanding...
Xamarin.Forms 2.5 is the first version to have different platforms depend on different versions of the Android support libraries:
For reasons I don't fully understand, this was causing the NuGet package install in the XamForms event generation step to fail with:
```
2017-11-24 19:46:34.242 +10:30 [Warning] An exception was thrown whilst retrieving or installing "Xamarin.Forms": "System.InvalidOperationException: Updating 'Xamarin.Android.Support.v4 23.3.0' to 'Xamarin.Android.Support.v4 25.4.0.2' failed. …
```
> chore: fix build

- src/ReactiveUI/Platforms/apple-common/ReactiveControl.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveImageView.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveNSView.cs
- src/ReactiveUI/Platforms/ios/ReactiveCollectionViewCell.cs
- src/ReactiveUI/Platforms/ios/ReactiveTableView.cs
- src/ReactiveUI/Platforms/ios/ReactiveTableViewCell.cs
This is either a bug fix or enhancement, depending on how you look at it. It applies the equivalent activation fix for `UIView` subclasses, that #1182 already did for `UIViewController` subclasses.
#1182 changed `UIViewController` subclasses to use `ViewWillAppear` instead of `ViewDidAppear` for activation, such that activation occurs before the view becomes visible.
This PR does the equivalent thing for `UIView` subclasses.
`UIView` subclasses (correctly) override `WillMoveToSuperview`, which is called before the view becomes visible. However, within those overrides, they schedule an async callback on the UI thread like this:
``` …
```
> fix: activate iOS views synchronously

- GitVersion.yml
- build.cake
Adds the git commit sha to the Product Version on ReactiveUI dll's.
fixes #1515 
When viewing the Properties -> Details of any ReactiveUI dll you will be able to see the first 8 characters of the git commit hash in the Product Version field.
Shouldn't break anything, it is an isolated change to the output of the nuget package dll's.
@ghuntley was concerned about the legacy dll's being different.  It seems that they are working.  ReactiveUI.WPF and …
> Added git hash to AssemblyInformationVersion

- .gitignore
Rider creates a *.idea* folder to store editor specific project properties, the equivalent of Visual Studio's *.vs* folder. Adding *.idea* to gitignore makes it easier to use Rider for contributors.
> Add .idea to gitignore to simplify use of JetBrains Rider

- snippets/Rider/ReactiveUI.xml
The snippets didn't show default values when inserting the snippet because of some missing quotes. These are now added
> Fix default values for snippet variables in Rider

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
- src/ReactiveUI/ReactiveCommand.cs
Feature... kind of
https://github.com/reactiveui/ReactiveUI/issues/1572
ReactiveCommand implements IHandleObservableErrors
Nothing
> fix: implement IHandleObservableErrors on ReactiveCommand

- build.cake
Bug fix in build process.
MSBuild aborts if `/p:AndroidSdkDirectory` contains spaces (e.g. with `/p:AndroidSdkDirectory=C:\Program Files (x86)\Android\android-sdk`, which is where Xamarin installs it by default).
Added quotes to the Android SDK path passed to MSBuild.
> fix: allow ANDROID_HOME to contain spaces when building

- src/ReactiveUI/Platforms/android/FlexibleCommandBinder.cs
- src/ReactiveUI/Platforms/ios/FlexibleCommandBinder.cs
- src/ReactiveUI/Platforms/ios/LinkerOverrides.cs
- src/ReactiveUI/Platforms/ios/RoutedViewHost.cs
Housekeeping.
There are some UIKit ifdefs that don't make a whole host of sense (e.g. iOS always defines UIKIT  and Android never defines it)
Remove the extra ifdefs to try and tidy up.
Hopefully nothing.
> refactor: remove unused UIKIT ifdefs

- appveyor.yml
not sure if this is actually hit at the moment, but might make a difference.
Use a preview appveyor image
Use a non-preview appveyor image (matching the non-master build)
> chore: use same vs2017 appveyor image for master and develop

- src/ReactiveUI.Fody/ObservableAsPropertyWeaver.cs
Bug fix
https://github.com/kswoll/ReactiveUI.Fody/issues/26
ReactiveUI.Fody will actually work on netstandard
Nothing
I noticed this fix isn't included in #1503 so I just wanted to make sure it got in there. I included it in my recent [netstandard PR](https://github.com/kswoll/ReactiveUI.Fody/pull/54) to ReactiveUI.Fody.
> fix: unhandled exception in Fody on netstandard

- LICENSE
- src/Directory.build.props
Fixes #1580 
I keep getting reports from folks who want to contribute but their employer has a restrictive list of pre-approved licenses and MSPL isn't on that list. 
What if we enabled those to help us? Much easier than making them go through internal corporate bs.
Feelings (tm). This PR is under review by the .NET Foundation legal team. If no issues, then we merge!
> feature: what if we were licensed under MIT?

- src/ReactiveUI/ReactiveList.cs
- src/ReactiveUI/ReactiveObject.cs
- src/ReactiveUI/WeakEventManager.cs
Fix 
https://github.com/reactiveui/ReactiveUI/issues/1617
Use NET_461 instead of NET_45 pre-processor directive to disable WeakEventManager for WPF platform
Nothing.
> fix: disable WeakEventManager for net461 build (#1617)

- src/EventBuilder/Platforms/XamForms.cs
dodgy workaround that has been documented in the maintainer guide
unpinned builds
pinned builds
If we forget to bump this when bumping reactiveui.xamforms and then the correct version of events won't be code generatoed.
> housekeeping: pin xamarin.forms version used by eventbuilder

- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
- src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
BugFix
Current Fody branch doesn't build. Old version of Android SDK, .Net Core, .Net Framework referenced. Build fails.
Fody branch now builds and references similar versions of dependencies to ReactiveUI.
I have no idea what this might break. I'm an amature. 
**Other information:**
I think this is not relevant in this instance?
> Align Fody dependencies to ReactiveUI

- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.Events/ReactiveUI.Events.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
- src/ReactiveUI/ReactiveUI.csproj
Feature
`System.Reactive` is pinned to v3.x, preventing installation of v4.x
`System.Reactive` is unpinned.
I have not tested this change; it's a pure find and replace.
> feature: enable reactiveui with system.reactive v4

- src/ReactiveUI.AndroidSupport/ControlFetcherMixin.cs
Fixes #1679
See https://github.com/reactiveui/ReactiveUI/issues/1679
Adds a `ResolveStrategy` parameter to `WireUpControls` for AppCompatActivity and Fragment in `Android.Support.V{4,7}...` 
`ReactiveUI.AndroidSupport.ControlFetcherMixins.WireUpControls(AppCompatActivity)` is removed in favour of a more capable `ReactiveUI.ControlFetcherMixins.WireUpControls(Activity, ResolveStrategy)`
>  Add ResolveStrategy parameter to WireUpControls in ReactiveUI.AndroidSupport

- src/Directory.build.props
Fix
Older versions of MSBuild.Extras was mistakenly adding incorrect framework references. See https://github.com/reactiveui/splat/issues/187
Upgraded to latest version of MSBuild.Extras
See https://github.com/reactiveui/splat/issues/187
> fix: MSBuild.Extras was mistakenly adding incorrect framework references

- src/Directory.build.props
- src/Directory.build.targets
- src/EventBuilder/EventBuilder.csproj
- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.Events/ReactiveUI.Events.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
- src/ReactiveUI.LeakTests/ReactiveUI.LeakTests.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
- src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
- src/ReactiveUI/Platforms/netcoreapp2.1/PlatformRegistrations.cs
- src/ReactiveUI/ReactiveUI.csproj
- src/global.json
…Core 2.1 target
Fixes the fact that RxUI was broken with MSBuild.SdkExtras 1.6.41. Not uses the SDK method and a global.json file. Also removed references that msbuild.sdk.extras provide. 
For the build system to fail and not build anything.
That everything will build and will pretty.
Don't think anything?
> Fix MSBuild.Sdk.Extras support to use the new syntax. 

- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
MSBuild.Sdk.Extras prefers TargetFrameworks and makes it consistent with other projects.
Makes it consistent with other projects, and MSBuild.Sdk.Extras prefers the TargetFrameworks
As mentioned on the MSBuild.Sdk.Extras readme:
```
Make sure to use TargetFrameworks instead of TargetFramework, even if you're only building a single target framework. I am piggy-backing off of its looping capabilities.
```
To use TargetFramework instead of TargetFrameworks.
To use TargetFrameworks
It shouldn't TargetFramework is an alias for TargetFrameworks …
> bug: Fix the project to use TargetFrameworks

- README.md
Changes in README.md to make it more friendly to new users.
There are some images not displaying due to broken urls, there are no links to documentation or to "Getting Started" page in old README.md file.
Images are back in town, links to docs, packages and samples are also added. "A Compelling Example" now uses `WhenAnyValue` instead of `WhenAny` and `x.Value`, curly brackets are formatted using .NET Core code of conduct. 
Nothing, really.
Personally I don't like centered text and huge empty space caused by "Table of …
> housekeeping: Fix typos and broken links in readme

- src/Directory.build.props
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
- src/ReactiveUI.sln
- src/global.json
Increments the MsBuildSdkExtras version so it doesn't break WPF.
The old version wasn't producing baml files in the resources, instead was just injecting XAML.
Xaml files which breaks WPF users by having the transitioncontrol not work.
This bumps the MSBuildSdkExtras to 1.6.46
Will allow the transition control to work.
Some other minor changes. 
- Removed unneeded stuff inside the wpf project csproj.
- set a constant for the solution directory if one doesn't exist. Can be useful if you are using VS code or something
- Added the global.json to the …
> Fix WPF users not having themes set correctly.

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.Winforms.approved.txt
- src/ReactiveUI.Tests/INPCObservableForPropertyTests.cs
- src/ReactiveUI.Tests/Platforms/winforms/DefaultPropertyBindingTests.cs
- src/ReactiveUI.Tests/Platforms/xaml/DependencyObjectObservableForPropertyTest.cs
- src/ReactiveUI.Tests/PocoObservableForPropertyTests.cs
- src/ReactiveUI.Winforms/WinformsCreatesObservableForProperty.cs
- src/ReactiveUI.Wpf/WpfDependencyObjectObservableForProperty.cs
- src/ReactiveUI/INPCObservableForProperty.cs
- src/ReactiveUI/IROObservableForProperty.cs
- src/ReactiveUI/POCOObservableForProperty.cs
- src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs
- src/ReactiveUI/Platforms/apple-common/KVOObservableForProperty.cs
- src/ReactiveUI/Platforms/apple-common/ObservableForPropertyBase.cs
- src/ReactiveUI/Platforms/uap10.0.16299/DependencyObjectObservableForProperty.cs
- src/ReactiveUI/ReactiveNotifyPropertyChangedMixin.cs
- src/ReactiveUI/ReactiveUI.csproj
- src/ReactiveUI/RegisterableInterfaces.cs
bug fix.
Fixes #864
Makes POCOObservableForProperty  error message include the property name.
Just lists the full type name.
Now includes the property name.
Could be performance issue but only if the error happens, and only once per instance of the type.
> Fix: Made POCOObservableForProperty include property name in warning

- src/ReactiveUI/Platforms/ios/ReactiveTableViewSource.cs
Adds feature requested in #1523
Unable to customize UITableView row animations when using ReactiveTableViewSource. Stuck with the default _UITableViewRowAnimation.Automatic_.
Ability to customize the row animations via properties.
Nothing
> Add properties to specify UITableViewRowAnimations

- build.cake
feature
build only targets stable VS instances
include prerelease instances of VS when using vswhere.exe
There is no way, with this implementation, to prefer Stable VS if Preview is also installed.
Needed to address https://github.com/reactiveui/ReactiveUI/issues/1615
> Allow building against prerelease versions of VS

- .github/release-drafter.yml
👋  Geoff here.
See https://probot.github.io/apps/release-drafter/
We _were_ using GitReleaseManager many moons ago but had to stop using it. We have been manually generating release notes by hand since migrating to VSTS.
Release notes are automatically generated. As pull requests are merged, a draft release is kept up-to-date listing the changes, ready to publish when you’re ready.
https://probot.github.io/apps/release-drafter
> feature: automatically draft release notes

- src/ReactiveUI.XamForms/DisableAnimationAttribute.cs
- src/ReactiveUI.XamForms/RoutedViewHost.cs
Xamarin.Forms navigation animations transitions by default, and apps
must explicitly opt out of the animation. RoutedViewHost hides these
APIs from the user.
This allows apps to apply DisableAnimation attribute to views in order
to instruct RoutedViewHost to not animate the transition.
Feature - right now the ReactiveUI.XamForms RoutedViewHost hides the Xamarin.Forms navigation API so that there's no way for apps to disable animation transitions. This change allows developers to mark views so that when they are pushed into the navigation stack there is no transition animation.
The current behavior is to call `PushAsync(x)`, which …
> [XamForms] Allow navigation transition animations to be disabled

- src/Directory.build.targets
- src/ReactiveUI/Platforms/apple-common/PlatformOperations.cs
- src/ReactiveUI/ReactiveUI.csproj
Feature
Say you want to target MonoAndroid81 instead of the current MonoAndroid80, you need to change all properties in the csproj file.
It is now easier because the names should only contain the platform.
Nothing
> housekeeping: Use StartsWith in the csproj files to make it easier to target new versions

- benchmarks/ReactiveUI.Benchmarks.sln
- benchmarks/ReactiveUI.Benchmarks/AutoPersistBenchmark.cs
- benchmarks/ReactiveUI.Benchmarks/CreateReactiveListBenchmark.cs
- benchmarks/ReactiveUI.Benchmarks/Harness.cs
- benchmarks/ReactiveUI.Benchmarks/INPCObservableForPropertyBenchmarks.cs
- benchmarks/ReactiveUI.Benchmarks/Mocks/MockHostScreen.cs
- benchmarks/ReactiveUI.Benchmarks/Mocks/MockViewModel.cs
- benchmarks/ReactiveUI.Benchmarks/NavigationStackBenchmark.cs
- benchmarks/ReactiveUI.Benchmarks/ReactiveListOperationBenchmark.cs
- benchmarks/ReactiveUI.Benchmarks/ReactiveUI.Benchmarks.csproj
- benchmarks/ReactiveUI.Benchmarks/RoutableViewModelMixinsBenchmarks.cs
- Added NavigationStack Benchmarks
- Added AutoPersist Benchmarks
- Added ReactiveList Operations Benchmarks
- Added RoutableViewModelMixin Benchmarks
Resolves #1711 
Resolves #1276
There are no performance tests
Adds a harness for ReactiveUI to execute performance benchmarks
Nothing.  This PR is additive.  Nothing in this PR affects the core solution.
> Added Benchmark Harness (#1729)

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
- src/ReactiveUI/RoutingState.cs
The routing state has a Scheduler property, but to set the Scheduler it'll re-generate all the commands/observables all over again if you want to immediately change the scheduler.
Now we have a constructor overload which takes a scheduler and will only set these commands/observables once.
That you use the property but this has a performance downside.
To keep the property if users need it, but just add a additional constructor for the user.
Shouldn't break users due to keeping existing API.
> feature: Add a constructor to take the constructor to RoutingState

- src/ReactiveUI.AndroidSupport/ControlFetcherMixin.cs
- src/ReactiveUI.AndroidSupport/ReactiveAppCompatActivity.cs
- src/ReactiveUI.AndroidSupport/ReactiveDialogFragment.cs
- src/ReactiveUI.AndroidSupport/ReactiveFragment.cs
- src/ReactiveUI.AndroidSupport/ReactiveFragmentActivity.cs
- src/ReactiveUI.AndroidSupport/ReactivePagerAdapter.cs
- src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs
Fixed up the namespaces in the Android support.
Some C# 7 support for various things.
Cleaned up using statements.
Adds DD support to the ReactivePagingAdapter.
Some namespace cleanups.
Some C# 7 stuff. 
Namespace using cleanups.
> Made the ReactivePagerAdapter not rely on ReactiveList.

- src/Directory.build.props
Required for sourcelink to function on non-netstandard platforms.
This will embed the PDB inside the file.
See https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md
Fixes sourcelink functionality. It isn't compatible with the old non-documented "full" debug method. .NET Standard by default uses the new portable, and this will make the .net framework use it as well.
Use full where it can which is the older legacy PDB version.
Use embedded which will simplify debugging on RxUI. This matches Rx.NET which also embeds.
**What might this PR …
> housekeeping: Make debug type use portable format and embedded.

- src/ReactiveUI.XamForms/RoutedViewHost.cs
Bug fix (introduced in the migration from ReactiveList to DynamicData)
Null reference exception when creating a Xamarin.Forms RoutedViewHost. Internally, the following exception was thrown by the line changed in this PR:
> Index expressions are only supported with constants.
No more exception
Nothing
> Fix Xamarin.Forms RoutedViewHost exception

- src/EventBuilder/Platforms/Android.cs
- src/EventBuilder/Platforms/Bespoke.cs
- src/EventBuilder/Platforms/iOS.cs
really minor docs update
T:blah used in crefs, analyser doesn't like it
Analyser should like it
Nothing?
> housekeeping: tidy up cref documentation in event builder (#1753)

- README.md
Samples page <a href="https://github.com/reactiveui/website/pull/194">has been moved</a>, so I updated links in the README.md file.
Readme link to the <a href="https://reactiveui.net/docs/resources/samples">samples page</a> is broken.
Readme link to the <a href="https://reactiveui.net/docs/resources/samples">samples page</a> is working again.
Nothing.
> housekeeping: Fix broken link to samples page

- build.cake
Some test scenarios cannot depend on cake locating VS/MSBuild correctly.
Allows explicitly specifying VS and MSBuild to your cake script.
Relies on cake to locate VS.
VS/MSbuild can be specified to cake, if not falls back to cake locator.
I suppose it could break the cake script..
Required for https://github.com/reactiveui/ReactiveUI/issues/1615
> Housekeeping: Allow explicit specification of VS and MSBuild path

- benchmarks/ReactiveUI.Benchmarks.csproj
- integrationtests/IntegrationTests.Shared.Tests/IntegrationTests.Shared.Tests.csproj
- integrationtests/IntegrationTests.Shared/LoginViewModel.cs
Fixes Benchmarks and Integration Tests not building due to analyzers.
The projects won't build
They build again.
Stuff that is already broken.
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
> housekeeping: Fixed analyzers breaking other solutions (#1823)

- src/EventBuilder/AutoPlatform.cs
- src/EventBuilder/Cecil/DelegateTemplateInformation.cs
- src/EventBuilder/Cecil/EventTemplateInformation.cs
- src/EventBuilder/Cecil/StaticEventTemplateInformation.cs
- src/EventBuilder/CommandLineOptions.cs
- src/EventBuilder/Entities/PublicTypeInfo.cs
- src/EventBuilder/ExitCode.cs
- src/EventBuilder/Platforms/Android.cs
- src/EventBuilder/Platforms/BasePlatform.cs
- src/EventBuilder/Platforms/IPlatform.cs
- src/EventBuilder/Platforms/Mac.cs
- src/EventBuilder/Platforms/iOS.cs
- src/EventBuilder/Platforms/tvOS.cs
- src/EventBuilder/Program.cs
housekeeping
event builder has a couple of minor warnings
fix the warnings
one of the warnings was for having setters on `Assemblies` and `CecilSearchDirectories`, which I've changed on the interface but this ended up needing a change on the Bespoke path. I don't think this should impact anything, but it's possible it might. Happy to think of alternatives/just ignore this warning though.
I've also just ignored the warnings about iOS, because they seemed slightly …
> housekeeping: tidying of build warnings in event builder

- src/ReactiveUI.Tests/DependencyResolverTests.cs
- src/ReactiveUI.Wpf/ReactiveWindow.cs
A new control is added, that implements the `IViewFor<TViewModel>` interface — `ReactiveWindow<TViewModel>`. Why? `ReactiveUserControl` exists, but `ReactiveWindow` doesn't, but sometimes it can be useful to avoid writing boilerplace code (and also to avoid mistakes when implementing `IViewFor` interface using dependency properties)
There is no `ReactiveWindow<TViewModel>`.
There is `ReactiveWindow<TViewModel>`.
Nothing.
> feature: Add WPF ReactiveWindow

- samples/getting-started/ReactiveDemo/AppViewModel.cs
- samples/getting-started/ReactiveDemo/MainWindow.xaml
- samples/getting-started/ReactiveDemo/MainWindow.xaml.cs
- samples/getting-started/ReactiveDemo/ReactiveDemo.csproj
After we've added the `ReactiveWindow<TViewModel>` and published ReactiveUI 9.1.1, it makes sense to update the getting started guide app to use `ReactiveWindow` instead of implementing IViewFor by hand for WPF, and to update package versions.
Getting started app startup Window isn't Reactive.
Getting started app startup Window is Reactive.
Nothing.
> housekeeping: Use ReactiveWindow in the Getting Started app

- src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
- src/ReactiveUI.Tests/CommandBindingTests.cs
- src/ReactiveUI.Tests/Platforms/winforms/CommandBindingTests.cs
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
- src/ReactiveUI.Tests/WeakEventManagerTest.cs
- src/ReactiveUI/Bindings/Command/CommandBinderImplementation.cs
- src/ReactiveUI/EventManagers/WeakEventManager.cs
- src/ReactiveUI/Platforms/uap10.0.16299/WinRTAutoSuspendApplication.cs
- src/ReactiveUI/ReactiveCommand/IReactiveCommand.cs
- src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs
- src/ReactiveUI/ReactiveCommand/ReactiveCommandBase.cs
- version.json
This removes the abstract base class we use in ReactiveCommand.
There is a abstract base class. Users can introduce subtle bugs by using it directly in their code. It was meant for interop with the ICommand but now ReactiveCommandBase<TParam, TResult> now implements that logic. There is also a interface allow some of the Command Binding code to keep functioning and exposes the observables for the user. It's deliberately not derived from ICommand due to us wanting the separation.
refactor.
Users who have a derived off the abstract base class. …
> refactor: Remove ReactiveCommand abstract class.

- samples/getting-started/ReactiveDemo/NugetDetailsView.xaml
- samples/getting-started/ReactiveDemo/NugetDetailsView.xaml.cs
- samples/getting-started/ReactiveDemo/ReactiveDemo.csproj
Update ReactiveDemo sample
ReactiveDemo sample solution does not build. After adding missing dependencies, Views cannot be opened in designer.
In ReactiveDemo sample:
NugetDetailsView.xaml can be opened in Design view.
Fixes missing references to PresentationCore, PresentationFramework and WindowsBase.
Nothting. Just wonder now if missing dependencies are not actually missing. I mainly work in VS for Windows, but I don't know how the sample hs to be used to target e.g. Xamarin.
**Other …
> ReactiveDemo hack around VS xaml designer issue with inherits from generic classes

- README.md
"Downloads" badge in README.md should display stats for `reactiveui` NuGet package.
Shields.io displays stats for `reactiveui-core` package now, which doesn't seem to exist anymore.
Shields.io should display stats for `reactiveui` NuGet package.
Nothing.
> housekeeping: Update shields.io downloads badge

- README.md
This PR adds ReactiveUI.Fody package usage example to README.md.
There is no info about ReactiveUI.Fody in README.md
ReactiveUI.Fody plugin link at Fody README.md file now points to ReactiveUI main repository (see https://github.com/Fody/Fody/pull/611), but here is no info right now about our awesome ReactiveUI.Fody plugin. This PR adds this info with a simple example.
Nothing.
> housekeeping: Add ReactiveUI.Fody usage example

- src/ReactiveUI.XamForms/RoutedViewHost.cs
- src/ReactiveUI.XamForms/ViewModelViewHost.cs
- src/ReactiveUI/Platforms/android/FlexibleCommandBinder.cs
- src/ReactiveUI/Platforms/apple-common/ObservableForPropertyBase.cs
- src/ReactiveUI/Platforms/apple-common/ViewModelViewHost.cs
- src/ReactiveUI/Platforms/net461/ComponentModelTypeConverter.cs
- src/ReactiveUI/Platforms/uikit-common/FlexibleCommandBinder.cs
- src/ReactiveUI/Platforms/uikit-common/RoutedViewHost.cs
- src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs
- src/ReactiveUI/Platforms/xamarin-common/ComponentModelTypeConverter.cs
Housekeeping. Replacing string.Format with string interpolation.
string.Format is used.
string interpolation is used where appropriate.
No idea.
NA?
> housekeeping: Use string interpolation where appropriate

- build.cake
- build.cmd
- src/global.json
Update cake from 0.22.0 to 0.30.0 with all the latest dependencies.
Update msbuild.sdk.extras from 0.6.61 to 0.6.65
> housekeeping: now use cake 0.30.0

- src/ReactiveUI.Tests/RoutableViewModelMixinTests.cs
- src/ReactiveUI/Routing/RoutableViewModelMixin.cs
Bug Fix
https://github.com/reactiveui/ReactiveUI/issues/1874
WhenNavigatingFromObservable completes when NavigateAndReset is invoked
Navigation operations
This is crucial for my project, as the `WhenNavigatingFromObservable()` feature is critical for cleanup.
> fix: WhenNavigatingFromObservable completes when NavigateAndReset is invoked (#1875)

- directory.build.props
- src/Directory.build.props
- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
- Nuget now wants either PackageLicenseLiteral or PackageLicenseFile. Using the literal for MIT
- Update to Fody 3.3.5 which removes issues for PackageLicenseLiteral.
> housekeeping: Use NuGet PackageLicenseLiteral, update fody.

- src/ReactiveUI/Platforms/android/AutoSuspendHelper.cs
closes #1865, closes #991
ShouldPersistState fires twice upon sending the app to the background.
Won't fire multiple times.
Nothing
Android documentation strongly recommends saving persistent data in OnPause rather than OnSaveInstanceState. OnPause is invoked every time OnSaveInstanceState is (hence the duplicate ShouldPersistState emission), but not the other way around. Plus, OnSaveInstanceState is meant for [saving **transient UI** …
> Fix: Android ShouldPersistState fires twice

- README.md
This PR mentions in README.md that ReactiveUI has a new package named `ReactiveUI.Events.XamEssentials` published.
There is no info that we support `Xamarin.Essentials`.
There is info that we support `Xamarin.Essentials`! :1st_place_medal: 
Nothing.
> housekeeping: Mention Events.XamEssentials package

- src/ReactiveUI/Platforms/windows-common/ReactiveUserControl.cs
This PR fixes two documentation issues, see https://github.com/reactiveui/website/issues/122 and https://github.com/reactiveui/website/issues/127
`ReactiveUserControl<TViewModel>` xml-doc describing it's usage is wrong, there are missing XAML directives `xmlns` and `xmlns:x`, also `x:Class` syntax is wrong, if someone would copy-paste that snippet, their project won't compile.
Missing directives are added, alongside with `xmlns:mc` and `xmlns:d` as they are also common.
Nothing.
> housekeeping: Correct ReactiveUserControl xml docs

- README.md
README.md file was updated with info about ReactiveUI packages for Tizen platform.
There is no info in README.md about which packages Tizen devs should install.
Info about which packages Tizen devs should install (`ReactiveUI` and `ReactiveUI.Events`) has been added.
> housekeeping: Mention ReactiveUI packages required for Tizen

- build.cake
- build.sh
- Fixed build.sh to bootstrap for modules
- Removed GitReleaseManager tool preprocessor
Moving build to current Cake version.
Cake is running version 0.31.0
Cake runs version 0.32.1
The build.,
> housekeeping: Upgraded Cake to v0.32.1

- src/ReactiveUI.Wpf/ReactiveWindow.cs
This is documentation improvement. Related to https://github.com/reactiveui/ReactiveUI/pull/1888
When bootstrapping a new WPF project with ReactiveUI, I copy-pasted XAML markup snippet from [API docs](https://reactiveui.net/api/reactiveui/reactivewindow_1/) page and it didn't compile due to missing xmlns directives and wrong `x:Class` syntax.
Now, the sample compiles, and uses correct syntax and correct `xmlns` directives.
Nothing.
> housekeeping: Correct ReactiveWindow usage example

- src/ReactiveUI.Tests/Platforms/xaml/ActivationForViewFetcherTest.cs
- src/ReactiveUI.Wpf/TransitioningContentControl.cs
- src/ReactiveUI/Platforms/windows-common/ActivationForViewFetcher.cs
- src/ReactiveUI/Platforms/windows-common/AutoDataTemplateBindingHook.cs
- src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
- src/ReactiveUI/View/DefaultViewLocator.cs
This fixes #1905 -- where a combobox does not correctly update in WPF if the combobox item is selected.
The boxes remain empty.
Due to the fact Combobox item's are cloned when they become the main view item, WhenActivated events wouldn't be fired correctly. Now also include "IsHitTestEnabled" in the list of included events we monitor.
Also changed so the ViewModelViewHost doesn't rely on the RxUI binding which can potentially give some performance boosts but also might reduce memory leak potential.
Hopefully nothing.
> fix: Combobox not updating when using Bind() generated ViewModelViewHost

- src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs
This PR adds usage examples to [ReactiveCommand](https://reactiveui.net/api/reactiveui/reactivecommand/) API docs. Addresses https://github.com/reactiveui/rfcs/issues/5#issuecomment-389593613
There are no examples in our API docs showing up how to create and execute a command.
Examples are present.
> housekeeping: Add ReactiveCommand usage examples

- README.md
NuGet badges in README.md are now showing ReactiveUI latest stable version number.
There are pre-versions currently, and someone could possibly think the framework isn't stable enough.
Now, README displays stable versions instead of pre-versions.
> housekeeping: Show stable NuGet versions

- src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
fixes #1920 
When a combobox is set to -1, it would previously cause a exception, 
will now just give a warning and set to default content.
> fix: Fix when a combobox SelectedIndex -1 it would crash

- src/ReactiveUI.Tests/Commands/ReactiveCommandTest.cs
Sometimes the tests with ReactiveCommand can fail due to threading issues. Now use the ImmediateScheduler for the failing cases.
> housekeeping: Fix ReactiveCommand tests failing on .net core 2.0

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net461.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp2.0.approved.txt
- src/ReactiveUI.Tests/ObservableAsPropertyHelper/ObservableAsPropertyHelperTest.cs
- src/ReactiveUI/ObservableForProperty/OAPHCreationHelperMixin.cs
- src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs
- src/ReactiveUI/Platforms/uikit-common/CommonReactiveSource.cs
- src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs
- src/ReactiveUI/ReactiveObject/ReactiveObject.cs
Fixes #823 
This fixes both performance related aspects and memory usage of the `ObservableAsPropertyHelper`
Thanks to @cabauman for assisting in tracking down the problem.
The following was used as a benchmark:
```cs
/// <summary>
/// A mock that wraps a ObservableAsPropertyHelper property.
/// </summary>
public class MockOAPHViewModel : ReactiveObject
{
private readonly ObservableAsPropertyHelper<bool> _myVar1;
/// <summary>
/// Initializes a new instance of the <see cref="MockOAPHViewModel"/> class.
/// </summary>
public MockOAPHViewModel()
{
_myVar1 = Observable.Never<bool>().ToProperty(this, nameof(MyProperty1));
}
/// <summary>
/// Gets a value indicating whether the OAPH value is set.
/// </summary>
public bool MyProperty1 => _myVar1.Value;
}
```
```cs
[Benchmark]
public void …
```
> fix: Memory usage of OAPH and ReactiveObject

- src/ReactiveUI/Platforms/uap10.0.16299/ReactiveUI.rd.xml
- src/ReactiveUI/ReactiveUI.csproj
Fixes https://github.com/reactiveui/ReactiveUI/issues/1750
ReactiveUI code-behind type safe bindings are [broken](https://github.com/reactiveui/ReactiveUI/issues/1750) for Universal Windows Platform applications when compiling those with .NET Native toolchain. There are several temporary solutions for this:
1. Turning .NET Native compiler off
2. Using `{x:Bind }` bindings instead of ReactiveUI `Bind` and `BindCommand` methods
3. Editing `Properties\Default.rd.xml` file to include type info for controls used by the app:
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
<Application>
<Assembly …
```
> fix: .NET Native Support

- integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
- src/EventBuilder/Platforms/Essentials.cs
- src/EventBuilder/Platforms/Tizen.cs
- src/EventBuilder/Platforms/XamForms.cs
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
Upgrade Xamarin.Forms to version 3.4
Xamarin.Forms targets version 3.3
Xamarin.Forms targets version 3.4
Xamarin.Forms based controls
> (housekeeping) Upgraded Xamarin.Forms to v3.4

- azure-pipelines.yml
- build.cake
To keep the builds consistent between all projects, we are now using a common cake recipe.
> housekeeping: Make ReactiveUI use the new ReactiveUI.Cake.Recipe

- README.md
[Very] Small change to README.md
Without the http protocol (`http://` or `https://`), Markdown translates `github.com/reactiveui/ReactiveUI/issues` into `https://github.com/reactiveui/ReactiveUI/blob/master/github.com/reactiveui/ReactiveUI/issues`, which is not a page that exists!
The link works ⚡️ 
Nothing
It works (without http/https) for `Passing on knowledge and teaching the next generation of developers`, unsure why to be frank.
> housekeeping: Fix typo in the [GitHub issues] url

- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
bug fixes #1959
Null crashes in the binding engine.
Null checks and null propogation
> fix: null pointer exception in binding

- README.md
README.md update.
There is no info in README that ReactiveUI supports routing currenctly, no references to [User Input Validation](https://reactiveui.net/docs/handbook/user-input-validation/) page on ReactiveUI website. 
Added missing references to docs, added info about routing, made code snippets a bit smaller :space_invader: 
Nothing.
> housekeeping: Mention Routing, shorten validation docs in README

- src/ReactiveUI.Fody.Tests/FodyWeavers.xsd
- src/ReactiveUI.Tests/Platforms/windows-xaml/XamlViewDependencyResolverTests.cs
- src/ReactiveUI.Tests/Platforms/winforms/WinFormsViewDependencyResolverTests.cs
- src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.net461.approved.txt
- src/ReactiveUI.Tests/Platforms/wpf/WpfViewDependencyResolverTests.cs
- src/ReactiveUI.Tests/Resolvers/DependencyResolverTests.cs
- src/ReactiveUI.Tests/Resolvers/PocoObservableForPropertyTests.cs
- src/ReactiveUI.Tests/Utilities/TestLogger.cs
- src/ReactiveUI.Winforms/ActivationForViewFetcher.cs
- src/ReactiveUI/Bindings/Converter/EqualityTypeConverter.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Legacy/ReactiveDerivedCollection.cs
- src/ReactiveUI/Legacy/ReactiveList.cs
- src/ReactiveUI/Mixins/ObservableLoggingMixin.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveControl.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveImageView.cs
- src/ReactiveUI/Platforms/uap10.0.16299/DependencyObjectObservableForProperty.cs
- src/ReactiveUI/Platforms/uikit-common/CommonReactiveSource.cs
- src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs
- src/ReactiveUI/ReactiveUI.csproj
- src/ReactiveUI/Routing/MessageBus.cs
- src/ReactiveUI/View/DefaultViewLocator.cs
There are a number of interface changes with Splat v7. Updated to take advantage.
Also removed all the code generated warnings.
> housekeeping: Update to Splat v7

- src/ReactiveUI.Fody.Tests/FodyWeavers.xsd
- src/ReactiveUI.Winforms/WinformsCreatesObservableForProperty.cs
- src/ReactiveUI/Bindings/Command/CreatesCommandBinding.cs
- src/ReactiveUI/Bindings/Converter/EqualityTypeConverter.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Expression/Reflection.cs
- src/ReactiveUI/Mixins/AutoPersistHelper.cs
- src/ReactiveUI/Mixins/ReactiveNotifyPropertyChangedMixin.cs
- src/ReactiveUI/Platforms/apple-common/KVOObservableForProperty.cs
Removed the external locks now the MRU cache has them in Splat v7
locks were external due to MRU cache not being threadsafe.
MRU cache has internal locks.
hopefully nothing
> housekeeping: removed external locks now splat mru cache has locking

- src/ReactiveUI.XamForms/RoutedViewHost.cs
Bug Fix for Xamarin Forms
It defaults to animate the transition even if the user has specified the [DisableAnimation] attribute.
It checks whether the user has disabled animation or not
PopToRoot functionality on Xamarin Forms 
> Check for DisableAnimation attribute before PopToRootAsync

- README.md
- directory.build.props
- integrationtests/Directory.Build.props
- src/Directory.build.props
did a search for betts and updated README.md, and multiple *.build.props folders.
Fixes documentation to show Anaïs Betts
Some spots don't show Anaïs Betts
N/A
Shouldn't break anything, but there could be some more spots that need to be updated.
> housekeeping: updated docs to Anaïs Betters

- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
- src/ReactiveUI.Events/ReactiveUI.Events.csproj
- src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.net461.approved.txt
- src/ReactiveUI.Tests/Utilities/ApiApprovalBase.cs
- src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
- src/global.json
> housekeeping: Update to MSBuild.Sdk.Extras v2.0.24 and output API differences on DevOps builds.

- 4eac0733-0a64-4c41-a024-157e17e6276c.cake
- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
- src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
Fixes https://github.com/reactiveui/ReactiveUI/issues/2021
> fix: WhenActivated not fired when in ViewModelViewHost

- src/ReactiveUI.Events/ReactiveUI.Events.csproj
- src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.net461.approved.txt
- src/global.json
- version.json
Downgrade to MsBuild.Sdk.Extras 1.6.68 since it was preventing WhenActivated was firing.
This should fix #2021
> fix: WhenActivated on WPF by reverting to MsBuild.Sdk.Extras 1.6.18

- samples/uwp/ReactiveUI.UwpRouting.sln
- samples/uwp/ReactiveUI.UwpRouting/App.xaml
- samples/uwp/ReactiveUI.UwpRouting/App.xaml.cs
- samples/uwp/ReactiveUI.UwpRouting/Assets/LockScreenLogo.scale-200.png
- samples/uwp/ReactiveUI.UwpRouting/Assets/SplashScreen.scale-200.png
- samples/uwp/ReactiveUI.UwpRouting/Assets/Square150x150Logo.scale-200.png
- samples/uwp/ReactiveUI.UwpRouting/Assets/Square44x44Logo.scale-200.png
- samples/uwp/ReactiveUI.UwpRouting/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
- samples/uwp/ReactiveUI.UwpRouting/Assets/StoreLogo.png
- samples/uwp/ReactiveUI.UwpRouting/Assets/Wide310x150Logo.scale-200.png
- samples/uwp/ReactiveUI.UwpRouting/Package.appxmanifest
- samples/uwp/ReactiveUI.UwpRouting/Properties/AssemblyInfo.cs
- samples/uwp/ReactiveUI.UwpRouting/Properties/Default.rd.xml
- samples/uwp/ReactiveUI.UwpRouting/ReactiveUI.UwpRouting.csproj
- samples/uwp/ReactiveUI.UwpRouting/ViewModels/FirstViewModel.cs
- samples/uwp/ReactiveUI.UwpRouting/ViewModels/MainViewModel.cs
- samples/uwp/ReactiveUI.UwpRouting/Views/FirstView.xaml
- samples/uwp/ReactiveUI.UwpRouting/Views/FirstView.xaml.cs
- samples/uwp/ReactiveUI.UwpRouting/Views/MainView.xaml
- samples/uwp/ReactiveUI.UwpRouting/Views/MainView.xaml.cs
This PR adds a basic Universal Windows Platform routing example powered by ReactiveUI.
There are no UWP sample apps now in the samples directory.
A new UWP sample app is added, showing up ReactiveUI routing (with animations)
Nothing.
> feature: Add Universal Windows routing example

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net461.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp2.0.approved.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/ApiApprovalTests.Winforms.net461.approved.txt
- src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.net461.approved.txt
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/FakeXamlCommandBindingView.cs
- src/ReactiveUI.Tests/Platforms/wpf/WpfCommandBindingImplementationTests.cs
- src/ReactiveUI.Tests/Resolvers/PocoObservableForPropertyTests.cs
- src/ReactiveUI.Winforms/WinformsCreatesObservableForProperty.cs
- src/ReactiveUI.Wpf/DependencyObjectObservableForProperty.cs
- src/ReactiveUI.Wpf/Registrations.cs
- src/ReactiveUI/Bindings/Command/CommandBinderImplementation.cs
- src/ReactiveUI/Interfaces/ICreatesObservableForProperty.cs
- src/ReactiveUI/Mixins/ReactiveNotifyPropertyChangedMixin.cs
- src/ReactiveUI/ObservableForProperty/INPCObservableForProperty.cs
- src/ReactiveUI/ObservableForProperty/IROObservableForProperty.cs
- src/ReactiveUI/ObservableForProperty/POCOObservableForProperty.cs
- src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs
- src/ReactiveUI/Platforms/apple-common/KVOObservableForProperty.cs
- src/ReactiveUI/Platforms/apple-common/ObservableForPropertyBase.cs
- src/ReactiveUI/Platforms/uap/DependencyObjectObservableForProperty.cs
- src/ReactiveUI/RxApp.cs
Bug fix
BindCommand will output warnings when binding ViewModel command to view button on WPF #2037
Warnings are suppressed for the specific scenario.
API approval tests
> Suppress binding warnings for BindCommand on WPF #2037

- src/ReactiveUI/Platforms/android/HandlerScheduler.cs
Fixes #1859 where the android bind command will swallow exceptions.
> fix: BindCommand unhandled exceptions don't fire on Xamarin Android

- src/ReactiveUI.Tests/ReactiveObject/ReactiveObjectTests.cs
- src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs
Resolves: #2013 
Exceptions thrown on `RaiseAndSetIfChanged` are not being rethrown if there is no "ThrownExceptions" subscribed.
Exceptions thrown on `RaiseAndSetIfChanged` are rethrown if there is no "ThrownExceptions" observable subscriptions.
> fix: Rethrow exception on RaiseAndSetIfChanged

- src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs
Feature
The GetItemViewType is standard with only a position ID, which cannot be used to work out what item belongs in the sourceList.
The GetItemViewType addition, now bubbles up the current position as well as the ViewModel so that the cell view type can be worked out.  This is important following best practices when a RecyclerView has different ViewHolders inside it.  With different View Cells.
Unsure
> Feature:  ReactiveRecyclerViewAdapter.GetItemViewType now passed view model type

- src/ReactiveUI.AndroidSupport/ControlFetcherMixin.cs
Bug #2052 
Breaks with the old Fragment
Re-introduced the Support Libraries for Fragment
> Fix: ControlFetcherMixin using wrong type

- src/ReactiveUI/Mixins/ReactiveNotifyPropertyChangedMixin.cs
- src/ReactiveUI/Platforms/netstandard2.0/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs
- src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
Fix https://github.com/reactiveui/ReactiveUI/issues/2053
Links to the [Installation](https://reactiveui.net/docs/getting-started/installation/) page are broken.
Links to the [Installation](https://reactiveui.net/docs/getting-started/installation/) page are no longer broken.
Nothing.
> housekeeping: Correct links to Installation docs

- src/ReactiveUI.Uno/ActivationForViewFetcher.cs
- src/ReactiveUI.Uno/PlatformRegistrations.cs
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
- src/ReactiveUI.Uno/WinRTAppDataDriver.cs
- src/ReactiveUI/Platforms/uap/DependencyObjectObservableForProperty.cs
- src/ReactiveUI/Platforms/uap/TransitioningContentControl.Empty.cs
- src/ReactiveUI/Platforms/windows-common/AutoDataTemplateBindingHook.cs
- src/ReactiveUI/Platforms/windows-common/BooleanToVisibilityHint.cs
- src/ReactiveUI/Platforms/windows-common/BooleanToVisibilityTypeConverter.cs
- src/ReactiveUI/Platforms/windows-common/PlatformOperations.cs
- src/ReactiveUI/Platforms/windows-common/ReactivePage.cs
- src/ReactiveUI/Platforms/windows-common/ReactiveUserControl.cs
- src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs
- src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
- Changed so that the ReactiveUI.Uno.csproj now references ReactiveUI.csproj
- Change UAP/Windows Common to put items into the ReactiveUI.Uno if HAS_UNO is defined.
- Don't register the WinRTAppDataDriver for Uno at the moment until we work out the replacement methods that aren't implemented in Uno, these are 
```
WinRTAppDataDriver.cs(32,34): warning Uno0001: Windows.Storage.FileIO.ReadTextAsync(Windows.Storage.IStorageFile, Windows.Storage.Streams.UnicodeEncoding) is not implemented in Uno [C:\source\reactiveui\ReactiveUI\src\ReactiveUI.Uno\ReactiveUI.Uno.csproj]
WinRTAppDataDriver.cs(32,58): warning Uno0001: Windows.Storage.Streams.UnicodeEncoding.Utf8 is not implemented in Uno [C:\source\reactiveui\ReactiveUI\src\ReactiveUI.Uno\ReactiveUI.Uno.csproj]
WinRTAppDataDriver.cs(71,61): …
```
> fix: uno not including ReactiveUI NuGet package

- src/ReactiveUI/Platforms/windows-common/ReactivePage.cs
- src/ReactiveUI/Platforms/windows-common/ReactiveUserControl.cs
Fixes missing constructors by Uno.UI.
Uno complains about these missing constructors.
Adds bridge constructors in the intermediate classes.
None
@jeromelaban Please have a look
> fix: added constructors required by Uno.UI for Android and iOS.

- src/ReactiveUI/Platforms/windows-common/ReactivePage.cs
Adds a parameterless constructor to the Uno ReactivePage
> fix: Uno ReactivePage has no parameterless constructor

- src/ReactiveUI/Platforms/windows-common/ReactiveUserControl.cs
Same as #2116 
These constructors appear to be required by the `ReactiveUserControl` as well.
> fix: adding special platform constructors to uno platform ReactiveUserControl as well

- src/Directory.build.props
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net461.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp2.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.net461.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.netcoreapp2.0.approved.txt
- src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.net461.approved.txt
- src/ReactiveUI.Uno/ActivationForViewFetcher.cs
- src/ReactiveUI/ReactiveUI.csproj
Fix ReactiveUI.Uno project compilation.
Something changed in Uno API so our CI checks fail now with `CS0201` and ` CS0029`
The solution builds locally so let's see if it does on the CI server.
Nothing.
> Bump System.Reactive, fix ReactiveUI.Uno compilation

- cake.config
- src/Directory.build.targets
- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.Events/ReactiveUI.Events.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
- src/ReactiveUI/ReactiveUI.csproj
Working around an Android build issue with MsBuild.Sdk.Extras
ReactiveUI doesn't build.
ReactiveUI builds.
Nothing that isn't already broken.
> fix: Android DesignTimeBuild issue with MsBuild.Sdk.Extras

- src/Directory.build.props
Minor lipstick.
If I dorked up the XML in the GitHub editor then this PR won't build, if it builds then 🚢 unless touchups required.
> docs: add the uno platform, remove windows store

- src/global.json
Fixed the Azure Pipelines build
The build is broken
The build succeeds
Nothing
> fix: Downgrade MsBuild.Sdk.Extras

- src/Benchmarks/AutoPersistBenchmark.cs
- src/Benchmarks/CreateReactiveListBenchmark.cs
- src/Benchmarks/INPCObservableForPropertyBenchmarks.cs
- src/Benchmarks/Mocks/MockHostScreen.cs
- src/Benchmarks/Mocks/MockViewModel.cs
- src/Benchmarks/NavigationStackBenchmark.cs
- src/Benchmarks/Program.cs
- src/Benchmarks/ReactiveCommandCreateBenchmark.cs
- src/Benchmarks/ReactiveListOperationBenchmark.cs
- src/Benchmarks/ReactiveUI.Benchmarks.csproj
- src/Benchmarks/RoutableViewModelMixinsBenchmarks.cs
- src/ReactiveUI/ReactiveUI.csproj
Add Benchmarks for `ReactiveCommand.Create`
Relates To: #1734 
Benchmarks are created for the following
1. Create
2. CreateFromTask
3. CreateFromObservable
Nothing
> performance: Added ReactiveCommand Benchmarks

- src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewViewHolder.cs
Thus eliminating the need to have a collection to get the ViewModel from.
This is helpful when using IObservable<IChangeSet<TViewModel>> as we don't have a list if it has been sorted during the Dynamic Data connection
Feature to return the ViewModel of the item that is selected in the adaptor for Android
None
> feature: add view model change observables to android ReactiveRecyclerViewViewHolder 

- build.cake
Now using azure pipelines for the package source, now that MyGet is going away soon. 
Doesn't make sense to use GitHub packages for this, and GitHub packages requires github credentials to work for the user.
> housekeeping: use the azure repository for the cake repo now

- src/ReactiveUI/Platforms/netstandard2.0/PlatformRegistrations.cs
WASM projects will run under .net standard so the exception will likely cause issues in the future.
This removes the exception in the platform registrations.
This fixes #2162
> fix: remove exception in .netstandard 2.0 code

- src/ReactiveUI/Platforms/uap/DependencyObjectObservableForProperty.cs
Bug fix
When building an Observable to observe a property of an object, if it inherits for `DependencyObject` and implements `INotifyPropertyChanged` the observable will be built using the `INotifyPropertyChanged.PropertyChanged` event.
The issue is that on iOS and Android the `UIElement` implements the `INotifyPropertyChanged` but it never raise the event: https://github.com/unoplatform/uno/issues/1551.
On UNO projects, if an object inherit from `DependencyObject` we will create a observable from the `DependencyProperty` if found and fallback to the `INotifyPropertyChanged` otherwise.
If a `DependencyObject` has a `DependencyProperty` which is …
> Prioritize DependencyObject over INPC for UWP based projects

- src/ReactiveUI/ReactiveUI.csproj
The preview versions of Reactive Extensions contain `UseWPF` and `UseWinforms`, which will force the client library to attempt to find those. This does not work on non-windows builds of .net core app 3.0 applications.
The WPF/WinForms versions contain the preview System.Reactive with these changes which will still allow those .net core app users to use WPF/WinForms on .net core app 3.0
> fix: in non-UI .netcoreapp3.0 applications a compile error is produced.

- integrationtests/IntegrationTests.WPF/IntegrationTests.WPF.csproj
- integrationtests/IntegrationTests.WinForms/IntegrationTests.WinForms.csproj
- integrationtests/global.json
- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
- src/ReactiveUI.Fody.Tests/FodyWeavers.xsd
- src/ReactiveUI.Splat.Tests/ReactiveUI.Splat.Tests.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net461.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp2.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.0.approved.txt
- src/ReactiveUI.Tests/Platforms/common-gui/ProductionMode.cs
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
- src/ReactiveUI.Uno/Registrations.cs
- src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
- src/ReactiveUI.Winforms/Registrations.cs
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
- src/ReactiveUI.Wpf/Registrations.cs
- src/ReactiveUI/Platforms/android/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/mac/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/net4/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/tizen/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/uap/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/uikit-common/PlatformRegistrations.cs
- src/ReactiveUI/ReactiveUI.csproj
- src/ReactiveUI/RxApp.cs
- tools/packages.config
Remove the indicator for range indicators from RxApp due to not needed since the removal of ReactiveList
Removed redundant ExtrasEnableWpfProjectSetup for projects.
> housekeeping: Update to splat 9

- src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.net461.approved.txt
- src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.netcoreapp3.0.approved.txt
- src/ReactiveUI.Wpf/ReactiveWindow.cs
- src/ReactiveUI/Platforms/windows-common/ReactivePage.cs
- src/ReactiveUI/Platforms/windows-common/ReactiveUserControl.cs
Chris Pullman on Slack noticed that if classes aren't marked as abstract, the designer will function for WPF, where previously they wouldn't.
Removing the abstract on these classes to allow for the designer to function.
> fix: the WPF designer by removing abstract

- src/ReactiveUI/RxApp.cs
This PR fixes `RxApp.SuspensionHost` being null in a unit test runner starting from ReactiveUI 10.3.1. We stumbled upon this when [trying to update](https://github.com/AvaloniaUI/Avalonia/pull/3045) `Avalonia.ReactiveUI` to use latest ReactiveUI 10.3.1, there we got 4 failing tests due to `RxApp.SuspensionHost` containing the `null` value — a `NullReferenceException` was thrown from the [AutoSuspendHelper](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.ReactiveUI/AutoSuspendHelper.cs) constructor.
Starting from ReactiveUI 10.3.1, `RxApp.SuspensionHost` doesn't get initialized if a unit test runner is detected. This is probably caused by the upgrade to Splat 9 where the unit test mode …
> Fix NRE when accessing RxApp.SuspensionHost

- src/ReactiveUI/RxApp.cs
Fixes #2164 
* Adds a warning message when running .NET Standard informing the user a host package needs to be installed.
None
None
Nothing
> Feature: Add warning when running .NET Standard

- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
- src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
- src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
- src/ReactiveUI.Events.XamEssentials/ReactiveUI.Events.XamEssentials.csproj
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.Events/ReactiveUI.Events.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
- src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
- src/ReactiveUI/ReactiveUI.csproj
Updates descriptions of NuGet packages to be specific for each package
Same description for all packages
Each package has its own specific description
Nothing
> Feature: give packages unique descriptions and tags 

- src/Directory.build.props
- src/Directory.build.targets
Housekeeping for build process to enforce #2182 and ensure nuget package descriptions are set AND not the default.
#2182 all packages have same description
msbuild task in targets file to validate pre-compile stage.
merge after #2182 as it will break the build prior to that being completed.
> Housekeeping: Msbuild nuget package description validation

- src/ReactiveUI.Wpf/Registrations.cs
Fixes #2194
Should be fine, anyone using .NET Framework where this works will have MainThreadScheduler paved by RxApp itself later anyways
> Fix: TypeLoadException in .net core app 3.0

- src/ReactiveUI.Winforms/RoutedViewHost.cs
Adds `SuspendLayout` to the RoutedViewHost WinForms control.
SuspendLayout is missing.
SuspendLayout has been added.
Nothing.
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)
There currently isn't any way to check for a suspended layout in WinForms unless reflection is used.
> feature: Added SuspendLayout to RoutedViewHost WinForms control.

- src/ReactiveUI.AndroidSupport/ReactivePagerAdapter.cs
- src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs
- src/ReactiveUI.AndroidX/ReactivePagerAdapter.cs
- src/ReactiveUI.AndroidX/ReactiveRecyclerViewAdapter.cs
The build is broken on several disposable points. 
These don't need the Interlocked.Exchange since they have re-entry guards within them already.
> Fix: the disposal analyzer errors

- src/ReactiveUI/Platforms/uap/SingleWindowDispatcherScheduler.cs
1 Check _dispatcher has been initialized to prevent always calling CoreApplication.Views[0].Dispatcher
2 Wrapped Interlocked.CompareExchange by try...catch to call standard exception handler
It is bugfix and fixes #2188 
https://github.com/reactiveui/ReactiveUI/issues/2188
App is not crashing on getting the first app view dispatcher in multiple views apps.
> Fix: fatal exception "Element not found" in UWP multiple views apps

- README.md
> housekeeping: Update link to Fody documentation

- src/ReactiveUI/Mixins/DependencyResolverMixins.cs
bug fix.
when loading on different platforms it will attempt to load DLLs for all the available NuGet packages we support. This will throw a FileNotFoundException. 
Does a file check to make sure the DLL is available before attempting to load the DLL.
Hopefully nobody.
> fix: exception happening on startup of applications

- src/ReactiveUI/Platforms/uap/SingleWindowDispatcherScheduler.cs
this fix is related to #2154 , some more testing showed that the former bugfix also has to be in place in ScheduleOnDispatcherNow
fix related to #2154 
When accessing the RxApp.MainThreadScheduler too early (i.e. no MainWindow yet), the CoreDispatcher can't be fetched in SingleWindowDispatcherScheduler's ctor. Thus, ScheduleOnDispatcherNow has to contain the original fix as well (check if _dispatcher is still null and if so, try again fetching the Dispatcher.)
> fix: sometimes the core dispatcher can't be fetched in constructor

- src/ReactiveUI/Mixins/DependencyResolverMixins.cs
fixes #2264 
That it fails to load assemblies on .net native. It attempts to check to see if the assemblies exist.
Will have the old exception back for unknown assemblies. This will be fixed with init() changes later.
Goes back to old functionality so shouldn't.
> fix: issues with binding to library

- src/ReactiveUI/Expression/Reflection.cs
Bug Fix #2282
Using AutoSuspendHelper on UWP,Mac,IOS do crash the app on startup
AutoSuspendHelper work correctly on UWP (can't test on Mac, IOS)
Nothing
dont know why build.cmd crash with this errors
```
Setting up tools...
Error: One or more errors occurred. (Object reference not set to an instance of an object.)
Object reference not set to an instance of an object.
```
> Fix Reflection.ThrowIfMethodsNotOverloaded

- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
Bug fix
When targeting `ReactiveUI.Uno`, I'm getting warnings such as this one:
Let's make it equal to the main ReactiveUI project, that depends on `Splat.Drawing` version `9.*`, rather than a specific version.
This causes warnings.
> fix: warnings about package downgrade

- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
Uses wildcard matching now that I have brought the wasm project out of preview.
> refactor: Make the wasm project use wildcard versioning

- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Blazor/Registrations.cs
Bug fix.  Changes to Registrations class to enable ReactiveUI.Blazor to determine operating platform effectively, Scheduler initialization
mono-wasm throws errors when initializing ReactiveCommand
No errors, commands work.
Potential to break ReactiveUI.Blazor on Server *IF* scheduling changes.  Potential to become obsolete once mono-wasm utilizes wasm threading.
Requires latest PR raised against System.Reactive.Wasm
> feature: Enable WASM on Blazor

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveLayoutComponentBase.cs
Fixes #2298 where the view model property being changed doesn't trigger a state refresh.
> fix: Blazor StateHasChanged not firing on ViewModel change

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveLayoutComponentBase.cs
As pointed out by @michaelstonis  in #2298 a null check is needed for the view model.
> fix: add null check for blazor view model property changes

- src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs
Fix api website documentation (/reactiveui/reactivecommand/)
Invalid syntax does not compile.
Valid syntax. See also: /docs/handbook/commands/index.md
> Fix invalid syntax in API documentation

- src/ReactiveUI.Tests/Platforms/winforms/DefaultPropertyBindingTests.cs
- src/ReactiveUI.XamForms/RoutedViewHost.cs
Fixes a bug where `NavigateBack` was not firing NavigationStack changes.
Resolves: #2286 
When `NavigateBack` is called the NavigationStack changes fire on the `Router.Scheduler` thread and the navigation works correctly.
Backwards navigation on Xamarin.Forms
> fix: NavigateBack ObserveOn Router Scheduler

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveLayoutComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
Bug fix to resolve #2308 
Views inheriting from `ReactiveComponentBase<T>` and/or `ReactiveLayoutComponentBase<T>` crash on initialization
Views inheriting from `ReactiveComponentBase<T>` and/or `ReactiveLayoutComponentBase<T>` do not crash on initialization
Nothing that ain't already broken
> Update and fix to ReactiveComponentBase and ReactiveLayoutComponentBase

- snippets/Visual Studio/ruicommand.snippet
- snippets/Visual Studio/ruiinteraction.snippet
- snippets/Visual Studio/ruiiv4.snippet
- snippets/Visual Studio/ruioaph.snippet
- snippets/Visual Studio/ruiprop.snippet
Fix interaction snippet: `=>` replaced with `{ get; } =`
Some minor final syntax adjustments
Failed to find a registration for a Interaction.
No exception. The property returns the registered Interaction instead of a new one.
> Fix and refactor Visual Studio snippets

- src/ReactiveUI.XamForms/RoutedViewHost.cs
@garyng provided a solution for fixing the `RoutedViewHost` Xamarin.Forms implementation.
fixes: #2317 
The stack values do not get distorted after the navigation pattern provided.
Xamarin.Forms navigation
I tested this in a sample and saw that the `NavigationStack` seems to be correct.  I am going to look into creating some unit tests for this behavior so we can make sure it continues to function as expected.
> fix: NavigateBack wrong values on the NavigationStack

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveLayoutComponentBase.cs
fix
There is a exception that happens when the ViewModel is changed, because the render hasn't happened yet.
We fire the StateHasChanged in a InvokeAsync, which will dispatch it after the render.
Hopefully no-one.
> Fix: StateHasChanged firing before render being available in Blazor

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveLayoutComponentBase.cs
Bug fix - moves WhenAny that was throwing errors in constructor to OnAfterRender.
Functionality - Adds `[Parameter]` tag to ViewModel property in component base to allow allow users to compose ViewModel in Razor syntax.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The render handle is not yet assigned.
```
**kaboom** basically.  
Hopefully not **kaboom**, although I've thought that before.
Nothing that ain't already broke.
> fix: Parameter tag on ReactiveComponentBase, moved WhenAny

- src/ReactiveUI/Interactions/Interaction.cs
Doccomments fixes.
Just a few edits for readability.
Maybe the use of _party_ was intended to encompass the user, not only application components, but I don't think it affects the general understanding of how interactions work.
> fix: grammar and spelling of the Interactions documentation

- src/ReactiveUI.AndroidSupport/ReactiveFragment.cs
- src/ReactiveUI.AndroidSupport/ReactiveFragmentActivity.cs
- src/ReactiveUI.AndroidSupport/ReactivePagerAdapter.cs
- src/ReactiveUI.AndroidSupport/ReactivePreferenceFragment.cs
- src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs
- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.AndroidX/ReactivePagerAdapter.cs
- src/ReactiveUI.AndroidX/ReactivePreferenceFragment.cs
- src/ReactiveUI.AndroidX/ReactiveRecyclerViewAdapter.cs
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI/Platforms/android/ReactiveFragment.cs
- src/ReactiveUI/Platforms/android/ReactivePreferenceFragment.cs
1) Mark ReactiveFragment and ReactivePreferenceFragment (core ReactiveUI project) as obsolete.
Fragment and PreferenceFragment were deprecated in API level 28:
https://developer.android.com/reference/android/preference/PreferenceFragment
https://developer.android.com/reference/android/app/Fragment
2) Adds a ReactivePreferenceFragment to ReactiveUI.AndroidX and ReactiveUI.AndroidSupport projects as alternatives to the obsolete one.
Users can use these classes without warning.
Users will be warned about these classes being obsolete, and encouraged to use the AndroidX or AndroidSupport equivalents.
Nothing.
**Please check if the PR fulfills these …
> Mark deprecated fragment classes obsolete

- integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
- src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
General housekeeping.  Xamarin.Forms 4.6 is coming out in the next cycle based on their current release cadence, moving this change in now because of consumer reported issues.
Resolves: #2386 
Xamarin 4.4.* is the minimum required version.
Xamarin 4.5.* is the minimum required version.
ReactiveUI.XamForms
> housekeeping: Upgraded Xamarin.Forms to v4.5

- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs
This fixes a bug where android text binding would crash.
It fixes #2170 
It crashes on binding.
It doesn't crash.
> fix: Fix android crashing on text binding

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
Relates To: #2377 
The current implementation of the `ReactiveComponentBase` is potentially creating unnecessary subscriptions.  Currently, we are wiring up `this.WhenAnyValue` in the `OnAfterRender` outside the `firstRender` which causes additional subscriptions every render.
We currently have our logic checking for the first render, doing some subscriptions for state changes, and then doing others outside of that if block.  That code is potentially leaking subscriptions.  We also do not call that state change correctly in the observable pipeline.
This change moves all subscription logic to inside the `firstRender` if statement.  This will reduce the number of subscriptions …
> fix: ReactiveComponentBase creating unnecessary subscriptions

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
Resolves: #2377
When you run the sample provided in the report after a few updates, Blazor will throw an `OutOfMemoryException`.
The sample no longer throw the exception.
`ReactiveComponentBase`
I tested my changes on a branch of the provided sample.  I will note that even though I am now disposing of the subscription with a composite disposable, I stopped seeing the issue as soon as I moved it into the `firstRender` check.
I let the app run for over an hour and did not experience the issue.  The most I did see logged on the memory footprint was a call to the GC that the …
> fix: Additional Subscriptions causing out of memory exception

- src/ReactiveUI.Wpf/Themes/Generic.xaml
- src/ReactiveUI.Wpf/TransitioningContentControl.cs
Improved TransitioningContentControl animations in WPF
- Added more transitions (Fade, Move, Slide, Drop, Bounce)
- Added DirectionProperty (Left, Right, Down, Up)
- Added DurationProperty
- Remove TransitionPart
```xaml
<reactiveUi:RoutedViewHost x:Name="RoutedViewHost" Transition="SlideLeft"/>
```
```xaml
<reactiveUi:RoutedViewHost x:Name="RoutedViewHost" Transition="Slide" Direction="Right" />
```
> Improved TransitioningContentControl animations

- src/ReactiveUI.Tests/ReactiveObject/ReactiveObjectTests.cs
- src/ReactiveUI/Interfaces/ReactivePropertyChangedEventArgs.cs
- src/ReactiveUI/Interfaces/ReactivePropertyChangingEventArgs.cs
- src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs
- src/ReactiveUI/ReactiveObject/ReactiveObject.cs
Fixes #2382 DelayChangeNotifications does not delay PropertyChanged events
Calling `DelayChangeNotifications()` on a `ReactiveObject` delays the `Changing` and `Changed` observable notifications, but not the actual `PropertyChanging` and `PropertyChanged` events.
`DelayChangeNotifications()` now delays `PropertyChanging` and `PropertyChanged` events the same as the observables. Duplicate events are also removed the same as with the observables.
*Code relying on the current behavior of `PropertyChanging` and `PropertyChanged` events not being delayed.*
While I don't think this will break stuff, the most likely places for other bugs to be introduced: …
> Fix Bug #2382 DelayChangeNotifications does not delay PropertyChanged events

- src/Directory.build.props
- src/ReactiveUI.Tests/Platforms/winforms/CommandBindingTests.cs
Updates Microsoft.CodeAnalysis.FxCopAnalyzers to version 3.0.0
Microsoft.CodeAnalysis.FxCopAnalyzers is on version 2.9.8
Microsoft.CodeAnalysis.FxCopAnalyzers will be on version 3.0.0
Analyzers
> housekeeping: Updated FxCopAnalyzers to v3.0

- src/ReactiveUI/Mixins/DependencyResolverMixins.cs
developer usefulness 
When using _RegisterViewsForViewModels_, it throws an InvalidOperationException with the unhelpful message, "Sequence contains no matching element," if any of the views are missing a parameterless constructor.
Message is changed to "Failed to register type {typeInfo.FullName} because it's missing a parameterless constructor."
Nothing.
Resolves #2437
> fix: Throw an informative registry exception in RegisterViewsForViewModels

- src/ReactiveUI.Blazor/ReactiveInjectableComponentBase.cs
Blazor has a option of using the Microsoft DI to inject properties onto a Component.
This allows you to inject your view model onto your view.
> feature: Add Injectable component base for blazor.

- src/ReactiveUI.Tests/ObservableAsPropertyHelper/ObservableAsPropertyHelperTest.cs
- src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs
> ObservableAsPropertyHelper.Value throws ArgumentNullException #2455

- src/ReactiveUI.Tests/Mocks/PropertyBindViewModel.cs
- src/ReactiveUI.Tests/Platforms/windows-xaml/PropertyBindingTest.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
1. Fix OneWayBind with converter invalid cast https://github.com/reactiveui/ReactiveUI/issues/2466
2. Add missing Test OneWayBind with converter invalid cast https://github.com/reactiveui/ReactiveUI/issues/2466
> Fix OneWayBind converter

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/ApiApprovalTests.Winforms.net472.approved.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/ApiApprovalTests.Winforms.netcoreapp3.1.approved.txt
- src/ReactiveUI.Winforms/ContentControlBindingHook.cs
- src/ReactiveUI/Bindings/Property/IPropertyBinderImplementation.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Bindings/Property/PropertyBindingMixins.cs
- src/ReactiveUI/Bindings/Reactive/IReactiveBinding.cs
- src/ReactiveUI/Bindings/Reactive/ReactiveBinding.cs
- src/ReactiveUI/Expression/Reflection.cs
- src/ReactiveUI/Interfaces/IPropertyBindingHook.cs
- src/ReactiveUI/Platforms/windows-common/AutoDataTemplateBindingHook.cs
This PR modifies the `PropertyBindingMixins` used mainly within `ReactiveUserControl` codebehind `WhenActivated` blocks.
It changes the `viewModel` members to be nullable.
Bit of contextual overview:
The ViewModel parameter in `Bind` is mostly unused.  The reason it exists is to simplify generic specification of the call.  By passing the ViewModel in, the generics can be implied, whereas if the parameter was omitted, the user would have to type out the verbose generic args themselves for every call.  Otherwise, the parameter is mostly unneeded, and theoretically could be removed.
99% of the time `Bind` is used, `ReactiveUserControl.ViewModel` member is what is passed in.  The current misalignment in nullability, though, means the user has to pass in the …
> Fix: Make Bind() ViewModel parameters nullable.

- src/ReactiveUI.Tests/Suspension/DummyAppState.cs
- src/ReactiveUI.Tests/Suspension/SuspensionHostExtensionsTests.cs
- src/ReactiveUI/Suspension/SuspensionHostExtensions.cs
Fixes an InvalidCastException when observing app state change.
fixes: #2465
The invalid cast exception is fixed.
SuspensionHost extensions
> fix: invalid cast exception with nullable appstate

- src/ReactiveUI.Tests/Platforms/windows-xaml/PropertyBindingTest.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
Fixes #2474, Fixes #2476 
BindTo and OneWayBind silently (but logged) stop working when attempting to assign null.
Restores previous behavior, before regression: allows null to be assigned.
Nothing.
> Fix: BindTo and OneWayBind not working for null values

- src/ReactiveUI/Interfaces/IViewLocator.cs
Docs
Resolves #2451
Doesn't claim to assign the `ViewModel` property of `IViewFor`
Nothing
Whether or not we want to change the default view locator implementation to populate the `ViewModel` property can be discussed and implemented in a separate PR.
> Fix misleading interface documentation

- src/ReactiveUI.Fody.Tests/Issues/Issue47Tests.cs
- src/ReactiveUI.Fody/ObservableAsPropertyWeaver.cs
Bug fix: resolves #2243 
Breaks project if using a long property with the `ObservableAsProperty` attribute
Doesn't break.
Nothing
Fix was just migrated from the old repo, as referenced in the comments in the linked issue.
> Fix: ReactiveUI.Fody "long" property breaks build

- src/ReactiveUI.Tests/Platforms/winforms/CommandBindingTests.cs
- src/ReactiveUI.Tests/Platforms/winforms/DefaultPropertyBindingTests.cs
- src/ReactiveUI.Tests/RxAppTest.cs
- src/ReactiveUI.Wpf/Registrations.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Platforms/android/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/mac/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/net4/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/netcoreapp2/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/netcoreapp3/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/netstandard2.0/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/tizen/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/uap/PlatformRegistrations.cs
- src/ReactiveUI/Platforms/uikit-common/PlatformRegistrations.cs
- src/ReactiveUI/RxApp.cs
Fix
All the current (non-skipped) unit tests in the ReactiveUI solution pass when run together. However, some of them (particularly a handful of the xaml binding tests), fail when run in isolation or small groups. Which means some tests are dependent on others. An unfortunate consequence of having the RxApp ambient context, leaking state.
**The main issues I found:**
1) The current code [assigns `CurrentThreadScheduler.Instance` to `_mainThreadScheduler`](https://github.com/reactiveui/ReactiveUI/blob/68596de514622ecf5961c1587f47ad6d702da76e/src/ReactiveUI/RxApp.cs#L121) instead of `_unitTestMainThreadScheduler`, so `_unitTestMainThreadScheduler` is left with whatever the platform registration assigned. For …
> Fix: RxApp scheduler logic makes unit tests unpredictable

- src/ReactiveUI/Platforms/ios/LinkerOverrides.cs
In the linker override for iOS, the UITextField setter was not trickered (probably because a little too much use of copy/paste).
> Fixes UITextField linker setter override

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/InteractionBinding/InteractionBinderImplementationTests.cs
- src/ReactiveUI.Tests/Mocks/InteractionAncestorView.cs
- src/ReactiveUI.Tests/Mocks/InteractionAncestorViewModel.cs
- src/ReactiveUI.Tests/Mocks/InteractionBindView.cs
- src/ReactiveUI.Tests/Mocks/InteractionBindViewModel.cs
- src/ReactiveUI/Bindings/Interaction/IInteractionBinderImplementation.cs
- src/ReactiveUI/Bindings/Interaction/InteractionBinderImplementation.cs
- src/ReactiveUI/Bindings/Interaction/InteractionBindingMixins.cs
Feature.
Resolves #2280 
The user now has an elegant and familiar way to hook up interactions in the view, and hides the complexity of handling when an interaction or its view model changes.
Now it's as simple as:
```
this.BindInteraction(ViewModel, vm => vm.MyInteraction, input => /*Do Something*/);
```
Nothing
> feature: Implement Interaction binding

- src/Directory.build.props
- src/ReactiveUI.Fody.Tests/FodyWeavers.xsd
- src/ReactiveUI.Tests/ObservedChanged/ObservedChangedMixinTest.cs
- src/ReactiveUI.XamForms/RoutedViewHost.cs
- src/ReactiveUI/Bindings/Command/CommandBinderImplementation.cs
- src/ReactiveUI/Bindings/Command/CreatesCommandBinding.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Bindings/Reactive/ReactiveBinding.cs
- src/ReactiveUI/Expression/Reflection.cs
- src/ReactiveUI/Interactions/Interaction.cs
- src/ReactiveUI/Interactions/UnhandledInteractionException.cs
- src/ReactiveUI/Mixins/DependencyResolverMixins.cs
- src/ReactiveUI/Observable.cs
- src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
- src/ReactiveUI/ReactiveCommand/ReactiveCommandMixins.cs
- src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs
- src/ReactiveUI/Routing/MessageBus.cs
- src/analyzers.ruleset
- src/analyzers.tests.ruleset
Older versions of StyleCop analyzers forced a space before the `!` character when confirming nullability. This new version doesn't require that.
Also removed old SourceLink csproj settings and not requiring SA1316 (Tuple's requiring upper space first letters). 
SA1316 wasn't turned on due to it being a breaking API change.
> housekeeping: Update nullability operator spacing

- src/ReactiveUI.Tests/Routing/RoutableViewModelMixinTests.cs
- src/ReactiveUI/Routing/RoutableViewModelMixin.cs
Bug
Calling `NavigateAndReset` doesn't complete the observable returned by `WhenNavigatedToObservable`.
This happens because `WhenNavigatedToObservable` only checks for `ListChangeReason.Remove`, and not `ListChangeReason.Clear`.
Calling `NavigateAndReset` completes the observable. This PR reuses the fix that was applied to `WhenNavigatingFromObservable`.
Nothing
> Fix: WhenNavigatedToObservable completion

- src/ReactiveUI.XamForms/AutoSuspendHelper.cs
This PR adds a new `AutoSuspendHelper` utility class to the `ReactiveUI.XamForms` package. In the proposed implementation we rely on Xamarin.Forms app lifecycle events https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/app-lifecycle
Currently, `AutoSuspendHelper` implementations exist for iOS and Android as separate classes. An implementation targeting Xamarin.Forms could help to reduce the amount of platform-specific code as stated in https://github.com/reactiveui/ReactiveUI/issues/1429 and also this way we can support other platforms supported by XF.
Now, there is an implementation of `AutoSuspendHelper` that works with Xamarin.Forms. Expected usage:
```cs …
```
> Add AutoSuspendHelper to ReactiveUI.XamForms

- src/ReactiveUI.Tests/WhenAny/ReactiveNotifyPropertyChangedMixinTest.cs
- src/ReactiveUI/Expression/ExpressionRewriter.cs
- src/ReactiveUI/Mixins/ExpressionMixins.cs
This PR intends to improve the error message when providing an unsupported expression type in the `WhenAny` calls.
Fix #1209
> Update unsupported expression error messages

- README.md
- src/Directory.build.props
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/ObservableAsPropertyHelper/ObservableAsPropertyHelperTest.cs
- src/ReactiveUI/ObservableForProperty/OAPHCreationHelperMixin.cs
- src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs
Allow to not emit the initial value when deferring the subscription.
If you subscribe to the property change it will emit a first default value.
If you subscribe to the property change it will NOT emit a first default value.
As far as I can tell the biggest risk, and a risk I would be facing on some projects, is that to workaround this behavior I have used `Skip(1)` and if the first value is no longer emitted then the `Skip(1)` will skip the wrong value.
Fix #2124
> Update OAPH to skip initial value when deferring subscription

- src/ReactiveUI.Wpf/TransitioningContentControl.cs
resolves: #2565 
`GetRenderTargetBitmapFromUiElement` throws an exception when `ui.Element.RenderSize.Height` is zero
return a default value in the `Height == 0` case
`TransitionContentControl `
> fix:  TransitionContentControl throwing exception on control height zero

- src/ReactiveUI/Platforms/ios/LinkerOverrides.cs
It's crashing on release iOS
```
System.ArgumentException: Set Method not found for 'On'
at System.Reflection.RuntimePropertyInfo.SetValue (System.Object obj, System.Object value, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] index, System.Globalization.CultureInfo culture) [0x00026] in <5068fc8a32e54286ab6bfc5ee27f556e>:0 
at System.Reflection.PropertyInfo.SetValue (System.Object obj, System.Object value, System.Object[] index) [0x00000] in <5068fc8a32e54286ab6bfc5ee27f556e>:0 
at ReactiveUI.Reflection.TrySetValueToPropertyChain[TValue] (System.Object target, System.Collections.Generic.IEnumerable`1[T] expressionChain, TValue value, System.Boolean shouldThrow) [0x000b0] in <e1949f822771464dbdc9df682532a22b>:0 
at …
```
> Fix: add UISwitch to linker overrides 

- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
This PR bumps `Microsoft.AspNetCore.Components` versions for NETStandard and NET5.
Needed to do that manually since in https://github.com/reactiveui/ReactiveUI/pull/2667 the bot bumps both refs to 5.* version.
> deps: Bump Microsoft.AspNetCore.Components in /src

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/ApiApprovalTests.Winforms.net472.approved.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/ApiApprovalTests.Winforms.net5.0.approved.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/ApiApprovalTests.Winforms.netcoreapp3.1.approved.txt
- src/ReactiveUI/Interfaces/IPlatformOperations.cs
It's super important that any interface we register in an `IWantsToRegisterStuff` is `public`, and ideally, the implementation too. This means that people can always extend ReactiveUI or support a new platform without having to fork the library
> Fix IPlatformOperations to be public like other registrable interfaces

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI/Mixins/DependencyResolverMixins.cs
- src/ReactiveUI/RegistrationNamespace.cs
With this PR, the `InitializeReactiveUI` extension method is now falling back to `PlatformRegistrationManager.NamespacesToRegister` if there are no registration namespaces provided via `params` of the `InitializeReactiveUI` method. The `NamespacesToRegister` property is mutable as opposed to `DefaultRegistrationNamespaces` — if we prefer `NamespacesToRegister` over the read only `DefaultRegistrationNamespaces` as the default value [here](https://github.com/reactiveui/ReactiveUI/blob/15f542b01da300d350b8ddb49855155c45531e8b/src/ReactiveUI/Mixins/DependencyResolverMixins.cs#L44), our users will be able to disable implicit dependency discovery if they'd like to via a call to `PlatformRegistrationManager.SetRegistrationNamespaces()`.
**What is …
> fix: Add RegistrationNamespace.Avalonia

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Commands/ReactiveCommandTest.cs
- src/ReactiveUI/Bindings/Command/CommandBinder.cs
- src/ReactiveUI/Bindings/Command/CommandBinderImplementation.cs
- src/ReactiveUI/Bindings/Command/CommandBinderImplementationMixins.cs
- src/ReactiveUI/Bindings/Command/ICommandBinderImplementation.cs
- src/ReactiveUI/ReactiveCommand/ReactiveCommandMixins.cs
…method
Added Tests using a Nullable Viewmodel
Added nullability for ViewModel property in BindCommand
Proposed fix for #2646
feature to allow nullable ViewModels and properties to be used without compiler warnings for InvokeCommand and BindCommand
when Nullable values are used with InvokeCommand they present a compiler warning 
when Nullable values are used with InvokeCommand they shouldn't present a compiler warning 
none expected
> fix: Add Nullability for target and ICommand to InvokeCommand extension

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Platforms/windows-xaml/PropertyBindingTest.cs
- src/ReactiveUI/Bindings/Property/IPropertyBinderImplementation.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Bindings/Property/PropertyBindingMixins.cs
Updated Bind, OneWayBind and BindTo to allow nullable properties to be selected with less decorators.
Sub properties will still require ! and ? operators as required.
The Aim is to have less of an impact to those users upgrading older code.
update
Bind, OneWayBind and BindTo all require additional Nullable decorators to remove 'result may be null' compiler warnings for Nullable ViewModels and Properties
The Bind, OneWay and BindTo property binding extension methods now do not require additional decorators for the ViewModel and the first property
None expected, but a code review should take place to remove any additional ! and ? decorators that may …
> Update For Property Binding to make it easier to use Nullable values

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Routing/RoutingStateTests.cs
- src/ReactiveUI.XamForms.Tests/Mocks/NavigationViewModel.cs
- src/ReactiveUI/Routing/RoutingState.cs
Changed Routing state to provide the nullable ViewModel upon navigating or Null if the stack is empty
closes #2743
feature
NavigateBack returns a Unit
NavigateBack returns a nullable IRoutableViewModel
may produce compile errors if there is currently a usage of the NavigateBack provided Unit
> feature RoutingState NavigateBack Result Type To IRoutableViewModel closes #2743

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Platforms/windows-xaml/PropertyBindingTest.cs
- src/ReactiveUI.Tests/Platforms/winforms/DefaultPropertyBindingTests.cs
- src/ReactiveUI.Tests/Utilities/ApiApprovalBase.cs
- src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs
Bug fix
Custom implementation of `IReactiveObject` does not fire PropertyChanging and PropertyChanged events.
See #2594 
`IReactiveObjectExtensions.SubscribePropertyChangedEvents` and `IReactiveObjectExtensions.SubscribePropertyChangingEvents are` now public
This PR breaks the public API by adding two new public extension methods `IReactiveObjectExtensions.SubscribePropertyChangedEvents` and `IReactiveObjectExtensions.SubscribePropertyChangingEvents are`
> Fix: Allow IReactiveObject to access subscription extensions

- src/ReactiveUI.Tests/Platforms/wpf/Mocks/WpfTestWindow.cs
- src/ReactiveUI.Tests/Platforms/wpf/WpfActivationForViewFetcherTest.cs
- src/ReactiveUI.Wpf/ActivationForViewFetcher.cs
- src/ReactiveUI/RegistrationNamespace.cs
Bug fix.
When a WPF application is shutdown, the `Unloaded` event is not fired and, as a result, the `View` is not deactivated by `ReactiveUI`; as explained in the issue https://github.com/reactiveui/ReactiveUI/issues/2490.
The `ActivationForViewFetcher` will observe the `Closing` event (if the `View` is a `Window`) to determine if the `View` should be deactivated.
Nothing.
> Fix WPF View deactivation

- src/ReactiveUI.Fody.Helpers/ObservableAsPropertyExtensions.cs
- src/ReactiveUI.Fody.Tests/API/ApiApprovalTests.ReactiveUIFody.net5.0.approved.txt
- src/ReactiveUI.Fody.Tests/API/ApiApprovalTests.ReactiveUIFody.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Platforms/windows-xaml/RxAppDependencyObjectTests.cs
- src/ReactiveUI.Tests/ReactiveObject/Mocks/OaphNameOfTestFixture.cs
- src/ReactiveUI.Tests/ReactiveObject/Mocks/WhenAnyTestFixture.cs
- src/ReactiveUI.Tests/Resolvers/INPCObservableForPropertyTests.cs
- src/ReactiveUI.Tests/WhenAny/ReactiveNotifyPropertyChangedMixinTest.cs
- src/ReactiveUI/Interfaces/ICreatesObservableForProperty.cs
- src/ReactiveUI/Mixins/ReactiveNotifyPropertyChangedMixin.cs
- src/ReactiveUI/ObservableForProperty/INPCObservableForProperty.cs
- src/ReactiveUI/ObservableForProperty/OAPHCreationHelperMixin.cs
- src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs
fixes #2811 can pass nullable in but return type is not forced to nullable
fix
OAPH returns a nullable type regardless of the OAPH it is attached to
OAPH returns a matching type of the OAPH it is attached to
none
> fixes #2811 Updated nullable values for OAPH

- src/ReactiveUI.Tests/Routing/Mocks/TestView.cs
- src/ReactiveUI.Tests/Routing/RoutedViewHostTests.cs
- src/ReactiveUI.Tests/Routing/ViewModelViewHostTests.cs
- src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs
- src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
Refactored RoutedViewHost and ViewModelViewHost to allow DefaultContent to be shown
fixes #2815
fix 
DefaultContent is not displayed for RoutedViewHost and ViewModelViewHost when loaded with null ViewModel
DefaultContent is displayed for RoutedViewHost and ViewModelViewHost when loaded with null ViewModel
Content will have a value when previously may not have depending upon the version of ReactiveUI i.e. >9.8.9
> fix RoutedViewHost and ViewModelViewHost to allow DefaultContent

- src/ReactiveUI.Tests/Platforms/wpf/Mocks/TransitionMock/FirstView.xaml
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/TransitionMock/FirstView.xaml.cs
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/TransitionMock/SecondView.xaml
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/TransitionMock/SecondView.xaml.cs
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/TransitionMock/TCMockWindow.xaml
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/TransitionMock/TCMockWindow.xaml.cs
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/TransitionMock/TCMockWindowViewModel.cs
- src/ReactiveUI.Tests/Platforms/wpf/WpfActivationForViewFetcherTest.cs
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
- src/ReactiveUI.Wpf/Themes/Generic.xaml
- src/ReactiveUI.Wpf/TransitioningContentControl.cs
RenderTargetBitmap take an int therefore the minimum input value must be 1.
fix #2801 
Transitioning Content Control has a DPI issue with a calculation returning less than 1;
Transitioning Content Control handles DPI issue with a calculation returning less than 1 but being resolved to 1;
none as is only used for animation.
> fix Transitioning Content Control DPI issue

- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Tests/Commands/ReactiveCommandTest.cs
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/CommandBindingViewModel.cs
- src/ReactiveUI.XamForms.Tests/Activation/Mocks/App.xaml.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveControl.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveImageView.cs
- src/ReactiveUI/ReactiveCommand/ReactiveCommandBase.cs
fix
Tests do not pass
Tests now pass
N/A
> fix Command Scheduler not set to immediate where required for CanExecute

- src/ReactiveUI.Blazor/Registrations.cs
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Mocks/PropertyBindViewModel.cs
- src/ReactiveUI.Tests/Platforms/windows-xaml/PropertyBindingTest.cs
- src/ReactiveUI.Uno/Registrations.cs
- src/ReactiveUI.Winforms/Registrations.cs
- src/ReactiveUI.Wpf/Registrations.cs
- src/ReactiveUI.XamForms/Registrations.cs
- src/ReactiveUI/Bindings/Converter/DecimalToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/DoubleToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/SingleToStringTypeConverter.cs
- src/ReactiveUI/Platforms/uap/PlatformRegistrations.cs
- src/ReactiveUI/Registration/Registrations.cs
feature add more IBindingTypeConverter implementations #1070
only a few IBindingTypeConverter implementations exist
common type converters added
none expected as if a user registers their own it should be resolved instead of the base functions
They may need to raise the affinity value above our base level of 10.
> feature #1070 add more IBindingTypeConverter implementations

- src/ReactiveUI.Blazor/Registrations.cs
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Tests/Mocks/PropertyBindViewModel.cs
- src/ReactiveUI.Tests/Platforms/windows-xaml/PropertyBindingTest.cs
- src/ReactiveUI.Uno/Registrations.cs
- src/ReactiveUI.XamForms/Registrations.cs
- src/ReactiveUI/Bindings/Converter/ByteToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/IntegerToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/LongToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/ShortToStringTypeConverter.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveControl.cs
- src/ReactiveUI/Platforms/apple-common/ReactiveImageView.cs
- src/ReactiveUI/Registration/Registrations.cs
feature
few default converters exist
Add Byte, Short, Integer and Long to String BindingTypeConverters
users should set any custom BindingTypeConverters to an affinity > 10
> Add Integer to string BindingTypeConverters

- src/ReactiveUI.Tests/Commands/ReactiveCommandTest.cs
- src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs
Changed ObserveOn to only affect the internal subscription
fix #2866
CanExecute stops Execute functioning when ObserveOn is assigned to global function
CanExecute only has ObserveOn assigned to internal subscription
none expected all existing tests are passing
> fix #2866 CanExecute Scheduler

- src/ReactiveUI.Tests/Platforms/windows-xaml/CommandBindingImplementationTests.cs
- src/ReactiveUI.Tests/Resolvers/PocoObservableForPropertyTests.cs
- src/global.json
fix
BindCommand with parameter incorrectly coded in tests
OLD Assert.Equal(0, received);
NEW condition Assert.Equal(13, received);
none but documentation for using BindCommand with parameter using Expression<Func<parameter>> may need a better explanation
This update is related to #2904 but proves that the function is working as expected.
User code may need to be updated to ensure correct operation
> fix BindCommand Tests

- src/ReactiveUI/View/DefaultViewLocator.cs
Co-authored-by: matej.hrlec@inel.com
> fix: improve null handling in DefaultViewLocator

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net472.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net5.0.approved.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp3.1.approved.txt
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
- src/ReactiveUI/Bindings/Property/PropertyBindingMixins.cs
fix #2913 
fix #2914 
OneWayBind has a extension method with a nullable decorator on the selector reported to cause issues
UNO dev channel has linking issues in latest releases.
extension method OneWayBind with a nullable decorator on selector reverted
Rolling UNO back to last stable version
OneWayBind none expected
UNO if reliance on any new 3.0.10-devxxx channel features has been adopted a manual update to the dev version will be required
> fix OneWayBind selector, rollback UNO version

- .github/workflows/build-samples.yml
- .github/workflows/ci-build.yml
build fix
openjdk 11 missing so net6 failing
adds maui check which installs openjdk 11
n/a
> fix: resolve ci failure by adding maui-check to install openjdk

- src/ReactiveUI.Tests/Platforms/wpf/WpfActivationForViewFetcherTest.cs
- src/ReactiveUI.Wpf/ActivationForViewFetcher.cs
fixes https://github.com/reactiveui/ReactiveUI/issues/2935
There is a memory leak introduced in #2793
Remove the dispatcher object hook to prevent the memory leak.
Users relying on the dispatcher closing, but this will cause a memory leak which is the greater evil.
> fix: memory leak on WPF

- src/ReactiveUI.Uno.WinUI/ReactiveUI.Uno.WinUI.csproj
- src/ReactiveUI.Uno/ActivationForViewFetcher.cs
- src/ReactiveUI.Uno/CoreDispatcherScheduler.cs
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
Fix the WinUI package for Uno not to have imported package. This causes problems with duplicate package names.
> fix: uno winui csproj incorrectly configured

- src/Directory.build.props
bug fix
Fixes https://github.com/reactiveui/ReactiveUI/issues/2994
Using full PDB 
Temporarily include Java.Interop direct from the folder for MonoAndroid10
Now also use portable format which is the preferred format now.
> fix: Incorrect version of JavaInterop included

- .github/workflows/ci-build.yml
- src/Directory.build.props
- src/Java.Interop.dll
- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Drawing/ReactiveUI.Drawing.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Uno.WinUI/ReactiveUI.Uno.WinUI.csproj
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
- src/ReactiveUI/ReactiveUI.csproj
Adds the Java.Interop temporary fix to any project containing the MonoAndroid target framework.
This gets around a bug until the next Visual Studio release where it includes too recent of version of Java.Interop for Xamarin.
Attempted to previously fix with Directory.Build.Props but needs to be included in every file.
> Fix: Add Java.Interop to all MonoAndroid projects

- version.json
Release 16.4.x
Has a breaking change, changing ReactiveCommand not to have a can execute scheduler. You can specify a scheduler if you need it by using `ObserveOn` on your IObservable you pass in for the `CanExecute`
Additionally, there are some additional default converters that handle nullable types.
> housekeeping: Release 16.4.x

- integrationtests/IntegrationTests.Shared.Tests/IntegrationTests.Shared.Tests.csproj
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
- src/ReactiveUI.Drawing/ReactiveUI.Drawing.csproj
- src/ReactiveUI.Fody.Analyzer.Test/ReactiveUI.Fody.Analyzer.Test.csproj
- src/ReactiveUI.Fody.Analyzer/ReactiveUI.Fody.Analyzer.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
- src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
- src/ReactiveUI.LeakTests/ReactiveUI.LeakTests.csproj
- src/ReactiveUI.Splat.Tests/ReactiveUI.Splat.Tests.csproj
- src/ReactiveUI.Testing.Tests/ReactiveUI.Testing.Tests.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.Net4_8.verified.txt
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
- src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj
- src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
- src/ReactiveUI.XamForms.Tests/ReactiveUI.XamForms.Tests.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
- src/ReactiveUI/ReactiveUI.csproj
breaking change
Supports .Net 5, however packages being released from Microsoft are not including .Net 5 and instead targeting .Net 6
net461 is being deprecated in a couple months.
netcoreapp3.1 has a easy upgrade route to net6
fixes #3033
Support for .Net5 is removed in favour for .Net 6. Official support stops in 6 months
net461 support is removed in favour of net461
netcoreapp3.1 is removed, upgrade to net6
Users will need to upgrade net 5 applications to net 6
> breaking: Remove Net5/NetCoreApp3.1/Net461 FrameworkTarget's

- README.md
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Tests/Resolvers/PocoObservableForPropertyTests.cs
fix
"Xamarin.AndroidX.Preference" Version="1.1.1.12", "Xamarin.AndroidX.Lifecycle.LiveData" Version="2.4.0.1" and "Xamarin.Google.Android.Material" Version="1.4.0.5" requires a newer Xamarin.AndroidX.Core version than Xamarin.Forms currently supports
rollback due to a breaking change in Xamarin packages
none expected
> fix Rollback AndriodX packages due to breaking change

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_8.verified.txt
- src/ReactiveUI/Mixins/DependencyResolverMixins.cs
- src/ReactiveUI/RegistrationNamespace.cs
fixes #3081 
Uno WinUI package is not part of the Dependency Resolver
Add Uno WinUI to the list.
> fix: Uno UI registrations are not initialized

- src/Directory.build.targets
- src/ReactiveUI.Uno.WinUI/ReactiveUI.Uno.WinUI.csproj
- src/ReactiveUI.Uno/ActivationForViewFetcher.cs
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
fix
There is no windows target framework
There's a windows target framework.
> fix: add windows net6 to uno winui

- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
Existing code using  ReactiveUI V17.0.13 to V17.1.4 will not compile without adding extra packages
Xamarin.Forms has been updated to use 1.7.0.1 of AndroidX.Core
Removed * from Xamarin.Forms version due to breaking change by Xamarin without following SemVer 2
None expected
> Update to AndriodX 1.7.0.1

- src/ReactiveUI/Platforms/uikit-common/ReactiveTableViewSource.cs
bug fix
build errors when targeting net6.0-ios or net6.0-tvos
```
The type or namespace name 'nfloat' could not be found (are you missing a using directive or an assembly reference?) 
```
no build errors
nothing
Because of newly introduced native types in C#, UIKit nfloat was moved from System.nfloat to ObjCRuntime.nfloat.
Source: https://github.com/xamarin/xamarin-macios/issues/13087
> fix: net6 iOS/tvOS build errors

- src/Directory.build.props
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Maui/ReactiveMasterDetailPage.cs
- src/ReactiveUI.Maui/ReactiveNavigationPage.cs
- src/ReactiveUI.Maui/ReactiveUI.Maui.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_8.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.Net4_8.verified.txt
- src/ReactiveUI.Uno.WinUI/ReactiveUI.Uno.WinUI.csproj
- src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
- src/ReactiveUI/Activation/ViewForMixins.cs
- src/ReactiveUI/Bindings/Command/CreatesCommandBinding.cs
- src/ReactiveUI/Mixins/AutoPersistHelper.cs
- src/ReactiveUI/Mixins/ReactiveNotifyPropertyChangedMixin.cs
- src/ReactiveUI/Platforms/xamarin-common/ComponentModelTypeConverter.cs
Update dependencies of a number of packages.
> housekeeping: Update dependencies

- .github/workflows/build-samples.yml
- .github/workflows/ci-build.yml
- .github/workflows/release.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- .github/workflows/release.yml
Fixes the release by removing the permissions tab. Will work out what permissions we need in the future.
This action is behind a approval system anyway so less critical then the main build task.
> fix: Remove permissions on release since we need ability to release

- src/ReactiveUI.Maui/ReactiveUI.Maui.csproj
- src/ReactiveUI.Maui/Registrations.cs
- src/ReactiveUI.Uwp/Common/AutoDataTemplateBindingHook.cs
- src/ReactiveUI.Uwp/Common/BooleanToVisibilityHint.cs
- src/ReactiveUI.Uwp/Common/BooleanToVisibilityTypeConverter.cs
- src/ReactiveUI.Uwp/Common/ReactivePage.cs
- src/ReactiveUI.WinUI/DependencyObjectObservableForProperty.cs
Fix for #3020 
Maui WinUI does not have Schedulers set for RxApp Schedulers
Maui WinUI has a Scheduler set for RxApp.MainThreadScheduler and RxApp.TaskpoolScheduler
other WinUI registrations applied.
> Fix for MAUI WinUI Schedulers

- src/ReactiveUI.Maui/RoutedViewHost.cs
Fix for #3035
1. Direct `Router.NavigationStack` manipulations are not affected on MAUI's `NavigationPage.Navigation.NavigationStack`
2. MAUI's `NavigationPage.PoppedToRoot` event is not supported
3. Double navigation to the same `VM` occures on application start
Bugs are fixed
Sample app: https://github.com/ili/ReactiveUI-Navigation-Issue/tree/fix-maui-navigation
Direct `NavigationPage.Navigation` manipulations are used to avoid page activations.
> Fix for MAUI RoutedViewHost

- src/ReactiveUI/Bindings/Converter/NullableByteToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/NullableDecimalToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/NullableDoubleToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/NullableIntegerToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/NullableLongToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/NullableShortToStringTypeConverter.cs
- src/ReactiveUI/Bindings/Converter/NullableSingleToStringTypeConverter.cs
Current implementation doesnt respect the possibility to assign null on null/empty string.
This potentially Fixes #3166.
But this might be breaking change, so I am not sure if it is good idea.
I have personally already stumbled on this issue few times and caused me headache, but never got into checking what is the issue.
Because when I declare number as nullable, then I expect it to be null, when I delete the text from TextBox. The way it is now is counter intuitive.
The fix makes sense to me, but could break lot of apps relying in that """feature""".
> [FIX] nullable conversions

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveInjectableComponentBase.cs
Null was filtered twice.
Optimization.
The `viewModelChanged` checked the null twice.
Filters only once.
The new version of #3319. That cannot be updated because its branch was deleted.
> Optimize null filtering

- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Drawing/ReactiveUI.Drawing.csproj
- src/ReactiveUI.Fody.Analyzer/ReactiveUI.Fody.Analyzer.csproj
- src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
- src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet6_0.verified.txt
- src/ReactiveUI/ReactiveUI.csproj
- src/ReactiveUI/Routing/RoutingState.cs
> Fix Change NavigationStack as DataMember

- .github/workflows/ci-build.yml
- .github/workflows/release.yml
- src/Directory.build.props
- src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Drawing/ReactiveUI.Drawing.csproj
- src/ReactiveUI.Fody.Analyzer/ReactiveUI.Fody.Analyzer.csproj
- src/ReactiveUI.sln
- src/ReactiveUI/ReactiveUI.csproj
- version.json
Update
MonoAndroid V12.0
MonoAndroid V12.1
Built using SDK32
> Update MonoAndroid to V12.1 (SDK 32)

- src/Directory.build.props
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Maui/ReactiveShell.cs
- src/ReactiveUI.Maui/ReactiveShellContent.cs
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
Feature
No Reactive version of Shell or ShellContent exists in MAUI
Add Feature ReactiveShell
Add Feature ReactiveShellContent
Update Blazor packages
Update AndriodX packages
Non expected
> Add Feature to MAUI

- src/Directory.build.props
- src/ReactiveUI.Maui/ReactiveUI.Maui.csproj
- src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj
- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
- src/global.json
Fix for #3493
Works on all targets except windows10.0.19041
Works on all targets
Added windows10.0.19041.0 target as a workaround for System.Reactive targeting net5.0-windows10.0.19041.0
When windows10.0.19041.0 is selected by the end user it causes the DispatcherScheduler in System.Reactive to be exposed and used.
none expected
> Fix issue in ReactiveUI.Wpf when windows10.0.19041 is selected at runtime by end user

- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
Fix for #3495 
Targeting windows10.0.19041.0 exposes System.Reactive base functionality causing issues with ReactiveUI
When targeting windows10.0.19041.0 ReactiveUI uses System.Reactive base functionality
None expected
> Fix DispatcherScheduler issue with ObserveOn

- src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
Fix #3505 
windows10.0.17763.0 missing WPF DispatcherScheduler extensions
windows10.0.17763.0 includes WPF DispatcherScheduler extensions
non - this is a patch to a regression of functionality 
> Fix #3505 include extensions for windows10.0.17763.0

- src/ReactiveUI.Maui/Common/AutoDataTemplateBindingHook.cs
- src/ReactiveUI.Maui/Common/ReactiveUserControl.cs
Fix for #3248 
ViewModelViewHost not working on WinUI projects.
Updated namespace to allow to work
none expected
> Fix For ViewModelViewHost not working on WinUI projects

- src/ReactiveUI.Maui/ReactiveUI.Maui.csproj
Update
There is a possibility that we could use functionality that is not available on the end users target by importing a newer SDK than the target we use.
By removing the latest SDK we will automatically fall back to our target framework 19041 this will ensure that we don't use components that are not compatible with older versions of windows 10 whilst enabling the end user a simple means of using the library with the SDK automatically being by the IDE selecting the correct SDK based upon the end users Target choices
None expected, those who have already added the newer SDK's can continue to do so
**Please check if the PR fulfils these …
> Update : Remove Requirements for the Latest WinUI SDK in Maui

- src/ReactiveUI.Maui/RoutedViewHost.cs
- version.json
Fix for #3563
After clearing the Navigation stack, when Navigating using PopToRoot or NavigateBack an exception occurs in InvalidateCurrentViewModel trying to cast Type A to Type B
Handlers are added to synchronise the navigation stacks and ignore incompatible viewmodels
None expected as this issue must have been an underlying issue and would have crashed the end application
> Fix For Maui Navigation cast Type A to Type B

- src/Directory.build.props
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI/ReactiveCommand/IReactiveCommand.cs
- src/ReactiveUI/ReactiveCommand/ReactiveCommandBase.cs
feature
Fixes https://github.com/reactiveui/ReactiveUI/issues/3582
That you can't specify any generic variant.
A new interface of `IReactiveCommand<TParam, TResult>` is added. It does not implement `ICommand` by design.
It should still be all as is, since its a new interface inbetween.
> feature: Add IReactiveCommand generic interface to allow for generic variants

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet7_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI.Tests/InteractionsTest.cs
- src/ReactiveUI/Bindings/Interaction/IInteractionBinderImplementation.cs
- src/ReactiveUI/Bindings/Interaction/InteractionBinderImplementation.cs
- src/ReactiveUI/Bindings/Interaction/InteractionBindingMixins.cs
- src/ReactiveUI/Interactions/IInteraction.cs
- src/ReactiveUI/Interactions/IInteractionContext.cs
- src/ReactiveUI/Interactions/IOutputContext.cs
- src/ReactiveUI/Interactions/Interaction.cs
- src/ReactiveUI/Interactions/InteractionContext.cs
On the interface `IInteractionContext` the `GetOutput()` is no longer accessible. You can still cast the concrete class. This enforces strict requirements
Since `Interaction` generated the `InteractionContext` there should be minimal changes to users unless they use `GetOutput` on the context. The `GetOutput` is on another interface used internally to get the output value. 
There is now support for providing your own context's by overriding the protected method `GenerateContext` on the `Interaction` class.
> breaking: Add a interface to IInteraction

- src/Directory.build.props
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
- src/ReactiveUI.Drawing/ReactiveUI.Drawing.csproj
- src/ReactiveUI.Fody.Analyzer.Test/ReactiveUI.Fody.Analyzer.Tests.csproj
- src/ReactiveUI.Fody.Tests/ApiApprovalBase.cs
- src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
- src/ReactiveUI.LeakTests/ReactiveUI.LeakTests.csproj
- src/ReactiveUI.Splat.Tests/ReactiveUI.Splat.Tests.csproj
- src/ReactiveUI.Testing.Tests/ReactiveUI.Testing.Tests.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet7_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI.Tests/AwaiterTest.cs
- src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
- src/ReactiveUI/Mixins/ChangeSetMixin.cs
- src/ReactiveUI/ReactiveUI.csproj
- src/ReactiveUI/Routing/RoutingState.cs
- version.json
housekeeping
Packages are failing to build due to multiple dependencies
Updated relevant packages
None expected
> Housekeeping Update packages

- src/ReactiveUI.Tests/ObservableAsPropertyHelper/ObservableAsPropertyHelperTest.cs
- src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs
Fixes #3682
For deferred subscriptions in OAPH 2 changes where made:
- On first `Value` access INPC is no longer emitted while the `Value` is still the initial value.
- After accessing `Value` for the first time, INPC is no longer emitted if the value produced from source is the same as the initial value
I don't think anything will break. It doesn't make sense for any UI framework to subscribe to INPC without reading the initial value anyway.
> Fix stop oaph omitting inappropriately 

- src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj
Feature
WinUI has net 6.0 and net 7.0 builds
ReacitveUI.WinUI now includes a build for net 8.0
Target framework needs to be updated to windows10.0.19041.0 if using an earlier version.
> Feature enable Net 8.0 on WinUI

- src/ReactiveUI.Maui/ActivationForViewFetcher.cs
- src/ReactiveUI.Maui/ReactiveUI.Maui.csproj
- src/ReactiveUI.Maui/ViewModelViewHost.cs
Fix for #3700 
Maui Activation fails.
Maui Activation updated to include all relevant types
none expected
> Fix for #3700 Maui Activation fails

- src/Directory.build.props
- src/ReactiveUI.Fody.Tests/API/ApiApprovalTests.cs
- src/ReactiveUI.Fody.Tests/ApiExtensions.cs
- src/ReactiveUI.Maui/ReactiveFlyoutPage.cs
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet8_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.cs
- src/ReactiveUI.Tests/Platforms/windows-xaml/Api/XamlApiApprovalTests.cs
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.cs
- src/ReactiveUI.Tests/Platforms/wpf/API/WpfApiApprovalTests.cs
- src/ReactiveUI.Tests/Utilities/ApiExtensions.cs
FIx for #3719 
Maui is missing ReactiveFlyoutPage 
Added ReactiveFlyoutPage to Maui
Updated Verify.Xunit and made code changes as required.
None
> FIx - Add ReactiveFlyoutPage to Maui

- src/ReactiveUI.Maui/Common/ViewModelViewHost.cs
- src/ReactiveUI.Maui/ViewModelViewHost.cs
- src/ReactiveUI.Tests/Platforms/wpf/API/WpfApiApprovalTests.Wpf.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/Platforms/wpf/API/WpfApiApprovalTests.Wpf.DotNet7_0.verified.txt
- src/ReactiveUI.Tests/Platforms/wpf/API/WpfApiApprovalTests.Wpf.DotNet8_0.verified.txt
- src/ReactiveUI.Tests/Platforms/wpf/API/WpfApiApprovalTests.Wpf.Net4_7.verified.txt
- src/ReactiveUI.Tests/Platforms/wpf/Mocks/ViewModelViewHosts/FakeViewWithContract.cs
- src/ReactiveUI.Tests/Platforms/wpf/WpfActiveContentTests.cs
- src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
- src/ReactiveUI.Wpf/Common/ViewModelViewHost.cs
- src/ReactiveUI.XamForms/ViewModelViewHost.cs
This changes applys to the Maui/Wpf/XamarinForm platform.
- Feature Request. See  #3713 
1. The ViewModelViewHost resolves view by the ViewContract property. Currently ignores the `ViewContract` condition if nothing found.
1. Add a property of `ContractFallbackByPass` so that we can bypass this fallback behavior.
2. Expose a virtual method , i.e. `protected virtual void ResolveViewForViewModel(object? viewModel, string? contract)` , which allows developers override this behavior.
As far as I can see, it does not break anying.
For WPF/MAUI/XamForms/WinUI, the …
> Allow Developers Bypass the Default Fallback Behavior (resolves #3713)

- src/ReactiveUI/Platforms/android/ControlFetcherMixin.cs
Fix for #3714 
WireUpControls throws exception with .Net 8.0 Android
WireUpControls works with .Net 8.0 Android
none expected
> Fix for WireUpControls throws exception

- .github/workflows/ci-build.yml
- .github/workflows/release.yml
- src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj
- src/global.json
Update build script
using MsBuild
using DotNet Build
none expected
> Housekeeping Update Build to use dotnet build

- src/ReactiveUI.Blazor/ReactiveInjectableComponentBase.cs
Fix for #3413
IActivatableViewModel does not activate
adds ability to hook to IActivatableViewModel Activate and Deactivate
None expected
> Fix for does not trigger WhenActivated()

- src/ReactiveUI/ReactiveUI.csproj
update
Packages are the same for all TFM's
Less dependencies are included for net 6+ due to them being available as part of the framework
n/a
closes #3792
> #3792 Leverage framework for dependencies

- src/ReactiveUI.Blazor/ReactiveComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveInjectableComponentBase.cs
- src/ReactiveUI.Blazor/ReactiveLayoutComponentBase.cs
Bug fix. Current implementation did increase RefCount under ViewModelActivator once, but decrement it twice on deactivation. So the ViewModel was bricked if it was used as Scoped, or Singleton and would never activate again.
Fixed behavior
Should only fix
> Fix Blazor ViewModelActivation

- src/Directory.Packages.props
- src/ReactiveUI/Routing/RoutingState.cs
fix
ReactiveUI 20.1.1 includes DynamicData 8
DynamicData 9 has an update to the Observable Change Set which introduces a default value, this results in a mismatch in count between V8 and V9
the default value has been removed from the RoutingState CurrentViewModel
Execution should match previous versions
> Fix to enable use of DynamicData 9.0

- src/Directory.Packages.props
- src/ReactiveUI.AndroidX/ControlFetcherMixin.cs
- src/ReactiveUI.AndroidX/GlobalUsings.cs
- src/ReactiveUI.AndroidX/ReactiveAppCompatActivity.cs
- src/ReactiveUI.AndroidX/ReactiveAppCompatActivity{TViewModel}.cs
- src/ReactiveUI.AndroidX/ReactiveDialogFragment.cs
- src/ReactiveUI.AndroidX/ReactiveDialogFragment{TViewModel}.cs
- src/ReactiveUI.AndroidX/ReactiveFragment.cs
- src/ReactiveUI.AndroidX/ReactiveFragmentActivity.cs
- src/ReactiveUI.AndroidX/ReactiveFragmentActivity{TViewModel}.cs
- src/ReactiveUI.AndroidX/ReactiveFragment{TViewModel}.cs
- src/ReactiveUI.AndroidX/ReactivePagerAdapter.cs
- src/ReactiveUI.AndroidX/ReactivePagerAdapter{TViewModel,TCollection}.cs
- src/ReactiveUI.AndroidX/ReactivePreferenceFragment.cs
- src/ReactiveUI.AndroidX/ReactivePreferenceFragment{TViewModel}.cs
- src/ReactiveUI.AndroidX/ReactiveRecyclerViewAdapter.cs
- src/ReactiveUI.AndroidX/ReactiveRecyclerViewAdapter{TViewModel,TCollection}.cs
- src/ReactiveUI.AndroidX/ReactiveRecyclerViewViewHolder.cs
- src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet8_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI.sln
- src/ReactiveUI/Properties/AssemblyInfo.cs
Feature
#3851
Functionality ported from the Mono Android TFM version that went out of support.
Only supports Net 8.0 plus with the latest packages released on 29th August 2024
No support for older targets if upgrading from the legacy package.
> Feature Add AndroidX with new packages

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet8_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet9_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI/Bindings/Command/CreatesCommandBinding.cs
- src/ReactiveUI/Bindings/Command/CreatesCommandBindingViaCommandParameter.cs
- src/ReactiveUI/Bindings/Command/CreatesCommandBindingViaEvent.cs
- src/ReactiveUI/Expression/Reflection.cs
- src/ReactiveUI/Interfaces/ISuspensionDriver.cs
- src/ReactiveUI/Mixins/AutoPersistHelper.cs
- src/ReactiveUI/PlatformRegistrationManager.cs
- src/ReactiveUI/Platforms/android/BundleSuspensionDriver.cs
- src/ReactiveUI/Platforms/android/ReactiveViewHost.cs
- src/ReactiveUI/Platforms/apple-common/AppSupportJsonSuspensionDriver.cs
- src/ReactiveUI/Platforms/mobile-common/ComponentModelTypeConverter.cs
- src/ReactiveUI/ReactiveUI.csproj
- src/ReactiveUI/View/DefaultViewLocator.cs
update
BinaryFormatter is used for suspension
Remove BinaryFormatter
Start adding AOT Markup
Suspension will fail to Deserialize
**** BREAKING CHANGE ****
> Remove BinaryFormatter, Start Adding AOT Markup

- README.md
It fixes the URL, in the documentation, to be consistent with [ReactiveUI.Blazor](https://www.reactiveui.net/docs/getting-started/installation/blazor) found in [Getting Started](https://www.reactiveui.net/docs/getting-started/installation/blazor) instead of [the dead URL](https://www.reactiveui.net/blog/2020/07/article-blazor-compelling-example).
Following the current URL, It leads to 404 Response.
The URL leads to existing and relevant page.
None that I know.
N/A
> Replace dead URL

- src/Directory.Packages.props
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet8_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet9_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet8_0.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet9_0.verified.txt
- src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.Net4_7.verified.txt
- src/ReactiveUI.Tests/ReactiveProperty/Mocks/SubcribeTestViewModel.cs
- src/ReactiveUI.Tests/ReactiveProperty/ReactivePropertyTest.cs
- src/ReactiveUI/Bindings/Command/CommandBinderImplementation.cs
- src/ReactiveUI/Expression/ExpressionRewriter.cs
- src/ReactiveUI/Mixins/DependencyResolverMixins.cs
- src/ReactiveUI/Platforms/android/ControlFetcherMixin.cs
- src/ReactiveUI/Platforms/android/FlexibleCommandBinder.cs
- src/ReactiveUI/Platforms/mac/AutoSuspendHelper.cs
- src/ReactiveUI/Platforms/mobile-common/ComponentModelTypeConverter.cs
- src/ReactiveUI/Platforms/net/ComponentModelTypeConverter.cs
- src/ReactiveUI/Platforms/uikit-common/AutoSuspendHelper.cs
- src/ReactiveUI/ReactiveProperty/ReactiveProperty.cs
- src/ReactiveUI/ReactiveProperty/ReactivePropertyMixins.cs
fix for #3935 
#3935 
ReactiveProperty updated to handle multiple subscribers
None expected, core function still retained
> Update ReactiveProperty for multiple subscribers

- src/ReactiveUI.Tests/Platforms/winforms/Mocks/FakeWinformViewModel.cs
- src/ReactiveUI.Winforms/ActivationForViewFetcher.cs
- src/ReactiveUI.Winforms/ContentControlBindingHook.cs
- src/ReactiveUI.Winforms/CreatesWinformsCommandBinding.cs
- src/ReactiveUI.Winforms/GlobalUsings.cs
- src/ReactiveUI.Winforms/PanelSetMethodBindingConverter.cs
- src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
- src/ReactiveUI.Winforms/ReactiveUserControl.cs
- src/ReactiveUI.Winforms/ReactiveUserControlNonGeneric.cs
- src/ReactiveUI.Winforms/Registrations.cs
- src/ReactiveUI.Winforms/RoutedViewHost.cs
- src/ReactiveUI.Winforms/TableContentSetMethodBindingConverter.cs
- src/ReactiveUI.Winforms/ViewModelViewHost.cs
Fix for #3885 
#3885 
This Removes ObserveOn and SubscribeOn extensions that are included with System.Reactive 6.0.1
None expected 
> Update WinForms to remove ControlObservable

- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet7_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet8_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet9_0.verified.txt
- src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
- src/ReactiveUI/Bindings/Property/IPropertyBinderImplementation.cs
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
- src/ReactiveUI/Bindings/Property/PropertyBindingMixins.cs
Fixes nullable annotations for OneWayBind
https://github.com/reactiveui/ReactiveUI/issues/4009
When the object you select is nullable, there is a warning for dereferencing it without nullcheck. If the object is not nullable, there is no warning.
Not sure, I'm not that familiar with the codebase, but I don't see what it could break.
Let me know if I should improve the PR in any way.
> Fix nullable annotations for OneWayBind

- src/ReactiveUI/ReactiveUI.csproj
https://github.com/reactiveui/ReactiveUI/pull/3933 mistakenly removed the target framework condition for STJ. Referencing the STJ package on .NET 8+ causes the STJ source generator to run twice, resulting in build errors. See https://github.com/dotnet/wpf/issues/8943.
Bug fix
Build errors for projects referencing ReactiveUI and using STJ source generation at the same time.
No build errors.
> Do not reference System.Text.Json for .NET 8+

- src/ReactiveUI.sln
- src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
closes #4003 
#4003 
Refactored BindTo to wrap inner exceptions in TargetInvocationException for better error reporting. Also made minor code cleanups and added missing using directives.
users will experience unhandled exceptions if invalid read-only bindings exist i.e. a binding is set to TwoWay for a read only property.
> Improve exception handling in property binder

- src/ReactiveUI.Maui/RoutedViewHost.cs
Fix
closes #3820 
#3820 
Changed RoutedViewHost to be a partial class to allow splitting its implementation. 
Refactored navigation stack comparison to use the StacksAreDifferent() method for improved clarity and maintainability.
If currently calling NavigateAndReset at startup may cause navigation to end up in a different place.
> Fix NavigateAndReset navigation for Maui
