ReactiveUI/Cocoa/ReactiveCollectionReusableView.cs
ReactiveUI/Cocoa/ReactiveCollectionView.cs
ReactiveUI/Cocoa/ReactiveCollectionViewCell.cs
ReactiveUI/Cocoa/ReactiveControl.cs
ReactiveUI/Cocoa/ReactiveImageView.cs
ReactiveUI/Cocoa/ReactiveNSView.cs
ReactiveUI/Cocoa/ReactiveTableView.cs
ReactiveUI/Cocoa/ReactiveTableViewCell.cs
ReactiveUI_XSIOS.sln

Update ReactiveNSView : add .ctor(CGRect) for Unified API.

---

.gitignore
MakeRelease.ps1
ReactiveUI/ReactiveUI_Mac64.csproj

Not sure what else to update to have proper things done for NuGet, but at least now the unified mac build won't overwrite the MonoMac version.

Updated ReactiveUI_Mac64 to output to Xamarin.Mac folder.

---

ReactiveUI/ReactiveUI_Net45.csproj

Remove source control binding cruft

---

ReactiveUI.AndroidSupport/ControlFetcherMixin.cs
ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj

This enables `WireUpControl` for `AppCompatActivity` and `Android.Support.V4.App.Fragment`

Add a ControlFetcherMixin for the Android Support library

---

docs/basics/whenany.md

Just a tiny typo fix in the docs.

Fix a typo.

---

ReactiveUI.Events/ReactiveUI.Events_XamForms_XS.csproj

This PR fixes #881 by fixing the project file and adding the requisite file stubs for the XamForms events package.

Fix events package for XamForms

---

ReactiveUI/ReactiveUI_WinRT.csproj
ReactiveUI/ReactiveUI_WinRT80.csproj

Turns out, WINRT doesn't support it :S

Remove XmlnsDefinitionAttribute from WINRT.

---

ReactiveUI.XamForms/XamForms/RoutedViewHost.cs

Xamarin Forms RoutedViewHost issues

---

ReactiveUI.XamForms/XamForms/ViewModelViewHost.cs

Fixes #947 by changing the base class for `ViewModelViewHost` to `ContentView`.

Use ContentView as base class for ViewModelViewHost.

---

ReactiveUI/Android/BundleSuspensionDriver.cs

https://github.com/reactiveui/ReactiveUI/issues/984

adding serializer.Serialize(st, state); into SaveState

---

README.md

initial revamp of README.md

---

ReactiveUI.Events/Events.mustache

#yourfirstpr

---

ReactiveUI/ReactiveCollectionMixins.cs

Fixes #1009 by adding an optional `IScheduler` parameter to `CreateCollection` overloads. If unspecified, defaults to `RxApp.MainThreadScheduler`.

Add scheduler parameter to CreateCollection.

---

ReactiveUI.Tests/RxRouting.cs
ReactiveUI/ViewLocator.cs

#1014 resolve base interface types correctly, and add unit tests to cover more cases

---

ReactiveUI/AutoPersistHelper.cs

Enhancement for #989 
(this should target the proper branch now, previous PR was #999)

ActOnEveryObject<T> can accept IReadOnlyReactiveCollection<T>

---

ReactiveUI/ReactiveUI_Android.csproj
ReactiveUI/ReactiveUI_iOS.csproj
ReactiveUI/ReactiveUI_iOS64.csproj

included ViewAttributes.cs into iOS, iOS64 and Android

---

ReactiveUI.AndroidSupport/ControlFetcherMixin.cs
ReactiveUI.AndroidSupport/ReactiveDialogFragment.cs
ReactiveUI.AndroidSupport/ReactiveFragment.cs
ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs
ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj

This bumps up the target framework to latest (6.0 at this moment) and
also sets the flag to use the latest available platform SDK going
forward

Resolves issue building android support project

---

README.md

Just some ones that jumped out at me. 
If I spot any others, I'll fix as I go.

Fixed a couple of minor typos

---

README.md

cc @kentcb for better words suggestions

added section for code reviewers

---

ReactiveUI.XamForms/XamForms/RoutedViewHost.cs

Rather than hooking into the NavigateBack command, monitor the navigation
stack itself for deltas. If the deltas indicate that backwards navigation
has occured, make a best attempt at providing a reasonable animation to
that point.
This allows VMs to remove multiple views from the navigation stack,
without necessarily popping to the root.

Improve backwards navigation handling.

---

ReactiveUI/Activation.cs

Adds a Deactivated observable to ViewModelActivator, addresses #963.

---

ReactiveUI/Cocoa/RoutedViewHost.cs
ReactiveUI/ReactiveUI_iOS64.csproj

Back when I started doing iOS + RxUI, I had to fix a bunch of issues in the iOS `RoutedViewHost`. Most notably, it's an actual control now, not just a helper class.
I've been running a non-trivial app with this implementation for quite some time, so am reasonably confident in the implementation.

Fix various RoutedViewHost issues.

---

docs/basics/view-location.md

This feature was confusing, because it was not obvious that ReactiveUI was not accepting my `IViewLocator` because it was registering its own internal `DefaultViewLocator` after I registered mine.
Finding out about `Locator.CurrentMutable.InitializeSplat()` and `Locator.CurrentMutable.InitializeReactiveUI()` was key.

Add example of custom view location

---

ReactiveUI/Xaml/WinRTAutoSuspendApplication.cs

changed LaunchActivatedEventArgs to IActivatedEventArgs to make it work with resume behavior. Renamed variable from _launched to _Activated

changed LaunchActivatedEventArgs to IActivatedEventArgs

---

ReactiveUI.AndroidSupport/ReactiveAppCompatActivity.cs
ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj

Add ReactiveAppCompatActivity. This class is actually a copy of ReactiveActionBarActivity, but extends from AppCompatActivity, the new standard for Android compat activities.

Add ReactiveAppCompatActivity

---

src/ReactiveUI.Events/ReactiveUI.Events_UWP.csproj
src/ReactiveUI/ReactiveUI_UWP.csproj

feat: reactiveui-core/reactiveui-events now targets UWP 10.0.14393.0 aka anniversary edition

---

src/ReactiveUI-Core.nuspec

Bug fix.
Most platforms have a dependency on Splat 1.0
All platforms target Splat 1.4.0 at a minimum.
No.

Fix Splat dependency.

---

src/ReactiveUI/ReactiveUI_UWP.csproj

Bug fix
UWP is missing the interactions feature.
The UWP project includes interactions.
No

Add interactions to UWP project.

---

appveyor.yml

chore/refactor
Only Events_* and *.nupkg are uploaded.
Events_*, *.nukpeg and MSIL assemblies are uploaded.
No

refactor: upload .dll artefacts to appveyor on successful build

---

src/ReactiveUI-XamForms.nuspec
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Bugfix
https://github.com/reactiveui/ReactiveUI/issues/1173
No
fixes #1173

bug: resolved install of reactiveui-xamforms into a library targeting WPA81 or Profile111

---

README.md

Docs update
The Readme and the homepage for Reactiveui.net were using outdated code samples, based on RxUI 6. #1200 
Code samples based on RxUI 7
No

Update Samples to RxUI 7

---

src/ReactiveUI.Tests/ReactiveCommandTest.cs
src/ReactiveUI/ReactiveCommand.cs

Swallow exceptions in InvokeCommand pipelines

---

src/ReactiveUI.Tests/InteractionsTest.cs
src/ReactiveUI/Interactions.cs

See #1205.
This PR also improves test coverage of interactions.

feature: add scheduling support to interactions

---

src/ReactiveUI/ViewLocator.cs

Extra xml comment was creating a warning

chore: tidy up xml comment

---

src/ReactiveUI.Tests/ViewLocatorTests.cs

refactor: use xunit IsType in unit tests

---

README.md

Document update (Readme file), Table of Contents specifically.
Functioning
N/A
No

Addition of Table of Contents with relative links

---

src/ReactiveUI/ObservedChangedMixin.cs

Also tidied up whitespace as per rebracer config

chore: improved ObservedChangedMixin xml documentation

---

src/ReactiveUI/ObservableAsPropertyHelper.cs

Rebracer also decided it didn't like some of the formatting (it's a seperate commit though, in case it wants reverting or something)

chore: tidy up XMLDOC in ObservableAsPropertyHelper

---

README.md

sponsors update on readme
-
Now your open collective backers and sponsors can to appear directly on your README. 
see how it'll look [here](https://github.com/apex/apex#backers)
Also add badges on top.
no
[More info](https://github.com/opencollective/opencollective/wiki/Github-banner)

 Add backers and sponsors from Open Collective

---

src/ReactiveUI.Tests/ReactiveCommandTest.cs
src/ReactiveUI/ReactiveCommand.cs

fix: schedule output of ReactiveCommand.Execute

---

CODE_OF_CONDUCT.md
README.md

housekeeping
- email paul
- email geoff
- email shared inbox
no

housekeeping: use hello@reactiveui.net for all communication

---

CODE_OF_CONDUCT.md
README.md
src/ReactiveUI.Tests/ReactiveCommandTest.cs
src/ReactiveUI.Tests/ViewLocatorTests.cs
src/ReactiveUI/Android/ControlFetcherMixin.cs
src/ReactiveUI/AutoPersistHelper.cs
src/ReactiveUI/CompatMixins.cs
src/ReactiveUI/Interactions.cs
src/ReactiveUI/ObservableAsPropertyHelper.cs
src/ReactiveUI/ObservedChangedMixin.cs
src/ReactiveUI/OrderedComparer.cs
src/ReactiveUI/PropertyBinding.cs
src/ReactiveUI/ReactiveCollectionMixins.cs
src/ReactiveUI/ReactiveCommand.cs
src/ReactiveUI/RegisterableInterfaces.cs
src/ReactiveUI/ViewLocator.cs

Ship ReactiveUI 7.3

---

src/ReactiveUI.XamForms/ViewModelViewHost.cs

Feature
- No ability to set `ViewContract` through XAML (because an observable is required)
- Default view contract is both expensive and pointless
- Added a `ViewContract` property so that a fixed contract can be assigned in XAML. This brings feature parity with the WPF `ViewModelViewHost`, which already has this property.
- Removed the (copypasta) default `ViewContractObservable` because it is both expensive (especially on Android!) and pointless (because XF ships with a stubbed `IPlatformOperations` implementation that does nothing, so all that pipeline creation ends …

feat: add support for ViewContract property to ViewModelViewHost

---

src/ReactiveUI.Tests/ActivationTests.cs

Extra test!
I really hope not...

test: add additional unit test to cover Activation returning IDisposable

---

src/ReactiveUI/ReactiveNotifyPropertyChangedMixin.cs

chore: tidy up comments in ReactiveNotifyPropertyChangedMixins

---

src/ReactiveUI/ReactiveCommand.cs

Tidies up more comments.
More renaming of This parameter...

chore: update comments in ReactiveCommand

---

src/ReactiveUI/LoggingMixins.cs

updating more comments
Ish. Renamed some `This` params to `@this` for consistency,

chore: update logging mixing XML comments

---

src/ReactiveUI.Testing/TestUtils.cs

Comment update
Comments don't cover the set of parameters the methods have.
No warnings from VS.
No :)

chore: tweaking comments in TestUtils

---

src/Directory.build.props

housekeeping
🚓 Has references to Windows Phone 🚔 
🔥 Windows Phone (and other things!) 🔥 
No
The `<owners>` field isn't actually used by NuGet.org but I've reduced it's scope down to match the NuGet.org push ACL (just in-case something goes wrong upstream)

housekeeping: nuget packaging :lipstick:

---

.github/PULL_REQUEST_TEMPLATE.md

Chore - improve wording on PR template to force people to think more deeply about breaking changes, not lead them to yes/no answers.

Improve wording on PR template

---

.github/ISSUE_TEMPLATE.md

docs update
Testing against prerelease builds points to page on old website.
Link points to the shiny new website :)
Hopefully nothing..

housekeeping update ISSUE_TEMPLATE to match website

---

src/Directory.build.props

housekeeping/bugfix
Old version
New version:
* See https://github.com/akavache/Akavache/issues/371
* See https://github.com/onovotny/MSBuildSdkExtras/commits/master
If this build is green then nothing is broken. 

housekeeping: update to MSBuild.Sdk.Extras 1.0.9

---

src/Directory.build.props

housekeeping
Old version
New version see https://oren.codes/2017/08/29/use-all-tfms-with-sdk-style-projects-in-visual-studio-for-mac/
Our build; if the build is green then 💯okay for merging.

housekeeping: upgrade MSBuild.Sdk.Extras

---

src/Directory.build.props

housekeeping
We don't ship a license
We now ship a license
If build is green then we are 🚢 

housekeeping: add license to nuget package

---

.gitignore
build.cake
src/ReactiveUI.Tests/API/ApiApprovalTests.Blend.approved.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.approved.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.Winforms.approved.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.cs
src/ReactiveUI.Tests/App_Packages/PublicApiGenerator.6.0.0/ApiGenerator.cs
src/ReactiveUI.Tests/ReactiveUI.Tests.csproj

Replaces #1264, but exactly the same sort of thing

feature: add approval tests

---

src/ReactiveUI.Winforms/ReactiveDerivedBindingListMixins.cs

Doc change
Comments that don't really match, build time warning
Docs that match the code
Nothing?

chore: fix xml doc on ReactiveDerivedBindingListMixins

---

.github/stale.yml

housekeeping
Added two new issue types to track developer experience
Anything labeled with these issues will never be automatically closed.
Probot. Easy to backout via reverting this commit.

housekeeping: don't autoclose dx issues or cx issues

---

CONTRIBUTING.md

Update CONTRIBUTING.md to reference 'develop' branch instead of 'master'

---

build.cmd
tools/packages.config

Fix cake version in build.cmd
Version was pinned in #1482, but because of out custom boostrapper this may not work.
Pin build.
CI builds, so should be obvious if it does break things :)
Related to #1474

housekeeping: specify cake version in bootstrap script

---

appveyor.yml

See https://github.com/reactiveui/ReactiveUI/pull/1487#pullrequestreview-64776408

housekeeping: remove && exit 0

---

src/ReactiveUI.Wpf/CpsWorkaround.targets
src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj

Workaround for CPS

---

.github/stale.yml

Don't label issues as "up-for-grabs". Instead use "help wanted" and GitHub will automatically ferry people towards our project.

housekeeping: github has spoken this is the new convention

---

build.cake

housekeeping: compile csproj with multiple target frameworks in parallel

---

src/ReactiveUI/RegisterableInterfaces.cs

tiny little docs update.
Warning on AppVeyor builds mostly...
Nothing?

housekeeping: tidy comments in registerable interfaces

---

src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
src/ReactiveUI/RoutableViewModelMixin.cs

Tiny docs change.
Warning in appveyor/builds.
Nothing?

housekeeping: tidy comments in RoutableViewModelMixen

---

src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj

Bugfix
No XML docs included for wpf project
Include XML docs for WPF project
Nothing?
Fixes #1538

fix: include xml docs in WPF package

---

build.cake

Bug fix in build process
#1566

fix ReactiveUI nuget dependency not being pinned correctly

---

src/ReactiveUI.Tests/ReactiveUI.Tests.csproj

Housekeeping
Older version of xunit used.
Newer version of xunit, includes some analysers etc.
Slight possibility of unit tests being broken, have run locally, and want to run in CI to verify.

chore: update xUnit to latest version

---

integrationtests/IntegrationTests.Android/IntegrationTests.Android.csproj
integrationtests/IntegrationTests.Android/MainActivity.cs
integrationtests/IntegrationTests.Android/Properties/AndroidManifest.xml
integrationtests/IntegrationTests.Android/Resources/Resource.Designer.cs
integrationtests/IntegrationTests.Android/Resources/layout/activity_main.axml
integrationtests/IntegrationTests.Android/Resources/layout/content_main.axml

Integration testing for the Android platform
Not implemented yet
Implemented
Nothing
Tested on a real device

feature: added Android platform

---

GitReleaseManager.yaml

hopefully a fix to our release process
GitReleaseManager fails to create release in GitHub - https://ci.appveyor.com/project/dotnetfoundation/reactiveui/build/1.0.508
Hopefully correcting some YAML
nothing that isn't already broken, hopefully

housekeeping: fix configuration for tizen

---

LICENSE
src/Directory.build.props

Ship MIT license into v8 release

---

GitReleaseManager.yaml
src/ReactiveUI/ReactiveList.cs
src/ReactiveUI/ReactiveObject.cs
src/ReactiveUI/WeakEventManager.cs

Hotfix
Resolves regression picked up by @ElijahReva 
WPF/WinForms now functional
n/a

Ship ReactiveUI v8.0.1

---

version.json

bumps semver
We are at 8.1.x
Now we are at 8.2.x

housekeeping: ship v8.2.x

---

.github/stale.yml

houseekeeping
Improves language used by stalebot and references https://reactiveui.net/blog/2018/05/reactiveui-succession

housekeeping: updated stalebot message

---

version.json

bumps semver
We are at 8.2.x
Now we are at 8.3.x

housekeeping: ship v8.3.x

---

README.md

Fixed the existing review teams to go to their new location. 
Also added additional teams that have been created by @ghuntley

fix: Update teams to point towards correct URI

---

src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
src/ReactiveUI/ReactiveUI.csproj

Change Splat to 4.0.2
Be 4.0.0 min
Be 4.0.2 min
Those who don't update.

housekeeping: Splat 4.0.2 is now required to fix MsBuild.Sdk.Extras issues

---

src/Directory.build.props

This is because the SourceLink data doesn't seem to be uploading properly.
Updates to the latest SourceLink
Be a older version
Be a newer version
Shouldn't unless there is a breaking change in SourceLink.

Bug Make SourceLink the latest version.

---

version.json

Go from version 8.4 to 8.5
Be 8.4
Be 8.5

Housekeeping: Release ReactiveUI 8.5

---

src/ReactiveUI/Platforms/netstandard2.0/PlatformRegistrations.cs
src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs
src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
src/ReactiveUI/ReactiveNotifyPropertyChangedMixin.cs

Usability improvements and Fixes #1597
Trash messages that aren't actionable
We tell the user to ensure that they have right packages installed with a link to installation instructions in our documentation.
Nothing
What language should we use? I'm leaving this one open as an easy help wanted. Discuss then PR this branch.

Fix: change exceptions to have meaningful directions to documentation to help users.

---

README.md

housekeeping
Glenn Watson is not on the Core Team
Glenn Watson is on the Core Team

housekeeping: Add Glen Watson to Core Team (#1718)

---

src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs

Feature: Make it easier for users to respond to RecyclerView item click events by adding ItemClicked and ItemLongClicked observable properties to the base adapter. Adding item click event properties to the adapter is a common pattern in Android. Here's a [sample by Xamarin](https://github.com/xamarin/monodroid-samples/blob/186573e7f203794026c5b004b7f43be4ab813ed2/android5.0/RecyclerViewer/RecyclerViewer/MainActivity.cs#L131).
The base ViewHolder already contains click event properties but they aren't accessible from outside the adapter. So the user basically has to implement some variation of what I did in this PR every time they …

Expose ItemClicked & ItemLongClicked streams

---

benchmarks/global.json

housekeeping: Update to latest msbuild.sdk.extras

---

benchmarks/global.json
src/global.json

Update to the latest version of MSBuild.Sdk.Extras

Updated the version of MSBuild.Sdk.Extras to the latest version

---

src/Directory.build.props
src/EventBuilder/Cecil/PathSearchAssemblyResolver.cs
src/EventBuilder/EventBuilder.csproj
src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
src/ReactiveUI/ReactiveUI.csproj

housekeeping to up the version of dynamicdata and splat.
old version.s
new versions.
shouldn't.

housekeeping: Update dependencies to latest versions. XamForms, Android, DynamicData, Splat

---

directory.build.props

Update analyzers to latest versions.

housekeeping: update analyzers to the latest versions

---

src/ReactiveUI.Tests/Platforms/xaml/PropertyBindingTestViews.cs
src/ReactiveUI.Tests/ReactiveNotifyPropertyChangedMixinTest.cs
src/ReactiveUI.Wpf/Attributes.cs
src/ReactiveUI.XamForms/ReactiveContentPage.cs
src/ReactiveUI/Platforms/android/ReactiveActivity.cs
src/ReactiveUI/Platforms/android/ReactivePreferenceActivity.cs
src/ReactiveUI/Platforms/android/ResolveStrategy.cs
src/ReactiveUI/Platforms/apple-common/IndexNormalizer.cs
src/ReactiveUI/Platforms/apple-common/ReactiveSplitViewController.cs
src/ReactiveUI/Platforms/apple-common/ViewModelViewHost.cs
src/ReactiveUI/Platforms/uikit-common/ReactiveCollectionViewSource.cs

Housekeeping.
Warnings are raised for numerous whitespace related code issues.
Some of these warnings are resolved.
NA
NA

housekeeping: Resolve petty whitespace related warnings.

---

src/ReactiveUI.Tests/Activation/ActivatingView.cs
src/ReactiveUI.Tests/Activation/ActivatingViewModel.cs
src/ReactiveUI.Tests/Activation/CanActivateViewFetcherTests.cs
src/ReactiveUI.Tests/Activation/DerivedActivatingViewModel.cs
src/ReactiveUI.Tests/CommandBindingTests.cs
src/ReactiveUI.Tests/DependencyResolverTests.cs
src/ReactiveUI.Tests/INPCObservableForPropertyTests.cs
src/ReactiveUI.Tests/JsonHelper.cs
src/ReactiveUI.Tests/ObservableAsPropertyHelperTest.cs
src/ReactiveUI.Tests/ObservedChangedMixinTest.cs
src/ReactiveUI.Tests/OrderedComparerTests.cs
src/ReactiveUI.Tests/Platforms/winforms/CommandBindingTests.cs
src/ReactiveUI.Tests/Platforms/winforms/DefaultPropertyBindingTests.cs
src/ReactiveUI.Tests/Platforms/xaml/ActivationForViewFetcherTest.cs
src/ReactiveUI.Tests/Platforms/xaml/DependencyObjectObservableForPropertyTest.cs
src/ReactiveUI.Tests/Platforms/xaml/PropertyBindingTestViews.cs
src/ReactiveUI.Tests/PocoObservableForPropertyTests.cs
src/ReactiveUI.Tests/PropertyBindingTest.cs
src/ReactiveUI.Tests/ReactiveCollectionTest.cs
src/ReactiveUI.Tests/ReactiveCommandTest.cs
src/ReactiveUI.Tests/ReactiveNotifyPropertyChangedMixinTest.cs
src/ReactiveUI.Tests/ReactiveObjectTest.cs
src/ReactiveUI.Tests/RoutableViewModelMixinTests.cs
src/ReactiveUI.Tests/TestLogger.cs
src/ReactiveUI.Tests/Utility.cs
src/ReactiveUI.Tests/ViewLocatorTests.cs
src/ReactiveUI.Tests/WaitForDispatcherSchedulerTests.cs
src/ReactiveUI/Platforms/windows-common/BindingTypeConverters.cs
src/ReactiveUI/ReactiveCommand/ReactiveCommandBase.cs

Housekeeping
Lots of warnings
Fix a lot of the random warnings mostly in the test project.

housekeeping: remove warnings from code base

---

azure-pipelines.yml

Adds preview/* to build on azure pipelines
preview/* builds don't build on azure pipelines
Build will trigger on pull requests and branches on preview/*
Nothing

(housekeeping) Add preview branches to azure pipelines (#1858)

---

build.cake
build.cmd

housekeeping: Update to cake 0.31.0

---

src/EventBuilder/Platforms/XamForms.cs

Update the XamForms to 3.3.0.967583

housekeeping: Update XamForms events to 3.3.0.967583

---

README.md

This PR adds NuGet shields.io badges with version number and a link to the package page (based on Slack discussion). Also, I commented out empty sections with teams, let's un-comment them when we decide what to put there or which tool to use to autogen images :) 
Nothing.

housekeeping: Add NuGet badges

---

azure-pipelines.yml
build.cake

housekeeping
The signing does not work.
The nerdbank git versioning happens inside the azure script.
Fixes the two things above.

housekeeping: fix signing to work/use nbgv from cake.

---

src/ReactiveUI/Platforms/uap10.0.16299/WinRTAppDataDriver.cs

simple warning fix for the WinRTAppDataDriver.cs file.

housekeeping: fix warning in WinRTAppDataDriver.cs

---

src/ReactiveUI.Tests/PocoObservableForPropertyTests.cs
src/ReactiveUI.Tests/ReactiveCollectionTest.cs
src/ReactiveUI.Tests/TestLogger.cs
src/ReactiveUI/ReactiveUI.csproj

Now using Splat 6.* as the default.

housekeeping: Make Splat 6.* the default.

---

README.md
directory.build.props
src/Directory.build.props
src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs

housekeeping: Updating to 9.8.15 release

---

README.md

Let's update our logo in README!

housekeeping: Use the new Logo in README

---

README.md

[ReactiveUI.Fody][FodyDoc] package is now mentioned in README.md (one of the coolest feature IMHO)
[![FodyBadge]][Fody]
[Fody]: https://www.nuget.org/packages/ReactiveUI.Fody/
[FodyDoc]: https://reactiveui.net/docs/handbook/view-models/#managing-boilerplate-code
[FodyBadge]: https://img.shields.io/nuget/v/ReactiveUI.Fody.svg

housekeeping: Add ReactiveUI.Fody package to Table

---

src/ReactiveUI/View/DefaultViewLocator.cs

Bug fix
https://github.com/reactiveui/ReactiveUI/issues/1918
Could not find a way to Test other than manually this fix as it just removes debug lines form the console.

Fix 1918 removing misleading debug information

---

integrationtests/IntegrationTests.Shared.Tests/IntegrationTests.Shared.Tests.csproj
samples/xamarin-forms/Cinephile/Cinephile/Cinephile.csproj
src/EventBuilder/EventBuilder.csproj

Update various nuget packages to the latest versions. Dependabot seems to be down.

housekeeping: update nuget versions

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/EventBuilder/Platforms/XamForms.cs
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Updates Xamarin.Forms to version 3.5.x
ReactiveUI targets Xamarin.Forms version 3.4.x
ReactiveUI targets Xamarin.Forms version 3.5.x
Events?

(housekeeping) Upgraded Xamarin.Forms to v3.5

---

samples/testing/ReactiveUI.Samples.Testing.SimpleViewModels/src/ReactiveUI.Samples.Testing.SimpleViewModels.Tests/ReactiveUI.Samples.Testing.SimpleViewModelsUnitTests.csproj
src/Directory.build.props
src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
src/ReactiveUI.Events.XamEssentials/ReactiveUI.Events.XamEssentials.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.Events/ReactiveUI.Events.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
src/ReactiveUI/ReactiveUI.csproj

housekeeping: Update from ReactiveExtensions 4.0.0 to 4.1.5

---

README.md
directory.build.props
integrationtests/Directory.Build.props
samples/testing/ReactiveUI.Samples.Testing.SimpleViewModels/src/ReactiveUI.Samples.Testing.SimpleViewModels.Tests/ReactiveUI.Samples.Testing.SimpleViewModelsUnitTests.csproj
src/Directory.build.props
src/EventBuilder/EventBuilder.csproj
src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
src/ReactiveUI.Mac.sln
src/ReactiveUI.Testing.Tests/ReactiveUI.Testing.Tests.csproj
src/ReactiveUI.Testing.Tests/TestFixture.cs
src/ReactiveUI.Testing.Tests/TestFixtureBuilder.cs
src/ReactiveUI.Testing.Tests/TestFixtureBuilderExtensionTests.cs
src/ReactiveUI.Testing/IBuilderExtensions.cs
src/ReactiveUI.Testing/MessageBusExtensions.cs
src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
src/ReactiveUI.Testing/SchedulerExtensions.cs
src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.net461.approved.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.netcoreapp2.0.approved.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.cs
src/ReactiveUI.Tests/Utilities/ApiApprovalBase.cs
src/ReactiveUI.sln
src/ReactiveUI/ObservableForProperty/POCOObservableForProperty.cs

Update the preview 10.0.1 release with updated contents from master.

houskeeeping: Update preview 10.0.1 with contents from master.

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/EventBuilder/Platforms/XamForms.cs
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Updates Xamarin.Forms to 3.6
We target Xamarin.Forms 3.5
We target Xamarin.Forms 3.6
Xamarin.Forms support

housekeeping: Upgraded Xamarin.Forms to v3.6

---

src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewAdapter.cs

fix: Added Equals to position and items.count check

fix: ReactiveRecyclerViewAdapter having a incorrect out of bounds check

---

build.cake
src/ReactiveUI.Events.XamEssentials/ReactiveUI.Events.XamEssentials.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.Events/ReactiveUI.Events.csproj

- Change processing over to using Pharmacist msbuild plugin
- Will work on adding the framework based version of Pharmacist next.

feature: Swap the xam essentials to latest version.

---

src/ReactiveUI.Blend/FollowObservableStateBehavior.cs
src/ReactiveUI.Blend/Platforms/net461/ObservableTrigger.cs
src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
src/ReactiveUI.Tests/Platforms/windows-xaml/Api/ApiApprovalTests.Blend.net461.approved.txt

Chagne over to using the official SDK. See https://developercommunity.visualstudio.com/content/problem/535255/how-to-install-blend-sdk-in-visual-studio-2019.html for details.

housekeeeping: Change blend SDK to use official microsoft version.

---

README.md

housekeeping: minor tweaks to readme

---

src/ReactiveUI.Uno/ReactiveUI.Uno.csproj

Based on PR from @weitzhandler with some additional changes to make it compile.

feature: allow uno namespace for uap17.0.17763

---

README.md

docs: add uno platform to readme

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Upgrade the minimum Xamarin.Forms version.
Minimum version is 4.0
Minimum version is 4.1
Xamarin.Forms

housekeeping: Upgraded Xamarin.Forms to v4.1

---

build.config

housekeeping: Update to cake 0.34.1

---

src/ReactiveUI.Blazor/ReactiveComponentBase.cs
src/ReactiveUI.Blazor/ReactiveLayoutComponentBase.cs
src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj

Updates AspNetCore preview6 to preview9 and adjusts the existing code for the new API changes.
No samples and it's brand new... and no NuGet, so nothing yet?

Updated to aspnetcore preview9 and fixed any changes in the API.

---

build.cake

Adding blazor to the cake build.

Housekeeping: add blazor to the cake build. 

---

src/Directory.build.targets
src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
src/ReactiveUI.Events/ReactiveUI.Events.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
src/ReactiveUI.Uno/ReactiveUI.Uno.csproj
src/ReactiveUI/ReactiveUI.csproj
src/global.json

This version up's the UWP support to 6.2.9
This is to attempt to help #2166

housekeeping: Update MsBuild.Sdk.Extras to 2.0.43

---

CONTRIBUTING.md

Docs Update => Update target base branch when submitting a pull request like spoken in (https://github.com/reactiveui/ReactiveUI/issues/2164#issuecomment-537233075)
Wrong target base branch 
Nothing

Housekeeping: update contribution guide to mention master

---

src/global.json

Updates to the latest version of MsBuild.Sdk.Extras

housekeeping: Update to MsBuild.Sdk.Extras 2.0.54

---

src/Directory.build.props
src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
src/ReactiveUI.Events/ReactiveUI.Events.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
src/ReactiveUI/ReactiveUI.csproj

Fixes #2202 
Update to 4.2.0 as part of our regular updates.

Housekeeping: Update System.Reactive from 4.1.6 to 4.2.0

---

src/ReactiveUI/Platforms/uap/SingleWindowDispatcherScheduler.cs

Now catching the exception and proceeding as if we don't have any dispatcher set.

fix: exception inside UWP SingleWindowDispatcherScheduler

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Upgrades Xamarin.Forms to v4.2
Xamarin.Forms references to v4.1
Xamarin.Forms references to v4.2
ReactiveUI.XamForms
ReactiveUI.Events.XamForms

housekeeping: Upgraded Xamarin.Forms to v4.2

---

README.md

Doc update.
Punctuation errors
Fixed errors

Fix Readme of punctuation errors

---

src/ReactiveUI/Platforms/uap/SingleWindowDispatcherScheduler.cs

type: fix 
accessing CoreApplication.Views throws in XamlIslands, thus in this case get the CoreDispatcher by alternate means
Fixes #2154
Bugfix, see description above
please see Issue #2154 
There is nothing implemented in XamlIsland to check if code is running hosted inside it. The change looks for the very specific case where accessing the CoreApplication.Views.Count property yields > 0, yet accessing CoreApplication.Views[0] throws an exception. In this case, the CoreDispatcher is fetched by Window.Current.Dispatcher.
(I could not think of any UnitTest for this change because it would …

Fix: scheduler crashes in xaml islands

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Upgrades Xamarin.Forms to v4.3
Xamarin.Forms references to v4.2
Xamarin.Forms references to v4.3
ReactiveUI.XamForms
ReactiveUI.Events.XamForms

housekeeping: Upgraded Xamarin.Forms to v4.3

---

src/ReactiveUI.Blend/Platforms/uap/Behavior.cs

docs update
it had a typo
it doesn't have that typo anymore
absolutely nothing

Fix typo in doc comment

---

build.config

Updating the version of cake used.

housekeeping: Update Cake to 0.36.0

---

snippets/Visual Studio/ruiinteraction.snippet
snippets/Visual Studio/ruiiv4.snippet
snippets/Visual Studio/ruioaph.snippet

- Fix ruiiv4 snippet (invalid title: `IViewFor<T>`) - Not Working
- Fix typo ruiopah --> ruioaph
- New snippet for Interactions

Feature: fix and add Visual Studio snippets

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Updates Xamarin.Forms to version 4.4.*
We depend on Xamarin 4.3.*
Depending on Xamarin 4.4.*
ReactiveUI.XamForms
This follows our policy for [Xamarin.Forms minimum version](https://reactiveui.net/contribute/maintainers/platform-knowledge/xamarin-forms/#when-to-bump)

housekeeping: Upgraded Xamarin.Forms to v4.4

---

README.md

Updated README for name change
Name is obsolete
Name is correct
Nothing

housekeeping: updated README to Claire Novotny

---

version.json

Housekeeping: Release 11.4

---

build.config

Updates Cake to v0.38.1
The most updated version of ReactiveUI.Cake.Recipe is broken
The ReactiveUI.Cake.Recipe works
Nothing

housekeeping: Update Cake to v0.38.1

---

version.json

Add a few extra branch options to the version.json file.

housekeeping: add extra branches to version.json

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Upgrades Xamarin.Forms to v4.6
Targeting Xamarin.Forms to v4.5
Targeting Xamarin.Forms to v4.6
Nothing

housekeeping: Upgraded Xamarin.Forms to v4.6

---

src/ReactiveUI.Android.Tests/ReactiveUI.Android.Tests.csproj
src/ReactiveUI.sln
src/stylecop.json

1. Cleanup stylecop.json
2. Fix missing path in solution
3. Cleanup missing resources

housekeeping: Minor solution/setting file cleanup

---

src/ReactiveUI.Fody.Analyzer.Test/Helpers/DiagnosticResultLocation.cs

Housekeeping: Change nullability in Tests

---

src/ReactiveUI.Tests/ReactiveObject/Mocks/OaphNameOfTestFixture.cs
src/ReactiveUI.Tests/Routing/Mocks/TestScreen.cs
src/ReactiveUI.Tests/WhenAny/WhenAnyObservableTests.cs
src/ReactiveUI.Uno/CoreDispatcherScheduler.cs
src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
src/ReactiveUI/Expression/Reflection.cs

Add pragma warning disable 8600, 8605, 8603, 8613, 8619

Add pragma warning disable 8600, 8605, 8603, 8613, 8619

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

change Xamarin.Forms target version to 4.7
Xamarin.Forms targets 4.6
Xamarin.Forms targets 4.7
ReacitveUI.XamForms

housekeeping: Upgraded Xamarin.Forms to v4.7

---

src/ReactiveUI.Splat.Tests/SplatAdapterTests.cs

Fixes the ReactiveUI build failing on the SplatAdapterTests
The build is broken.
The build is working
Nothing that isn't already broken.

fix: SplatAdapterTests

---

README.md

This PR adds a reference to ReactiveUI.Blazor into the table in README.md.
Currently, there is no reference to ReactiveUI.Blazor in our README.md file.
Now, there is a reference to ReactiveUI.Blazor in our README.md file.
Nothing.

Mention ReactiveUI.Blazor in README.md

---

README.md

This PR adds a reference to [ReactiveUI.AndroidX](https://www.nuget.org/packages/ReactiveUI.AndroidX/) to our `README.md` file.
Currently, we aren't mentioning `ReactiveUI.AndroidX` in our README.md file.
With this change, we will be mentioning `ReactiveUI.AndroidX` in our README.md file.
Nothing.

housekeeping: Mention ReactiveUI.AndroidX

---

README.md

housekeeping: changed sponsorship

---

README.md

Remove some of the materials duplicated by the website. Might even remove that NuGet matrix due to it being more up to date on the website version.

housekeeping: Cleanup the readme a bit more

---

integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Upgrades the Xamarin dependency to 4.8.*
Xamarin dependency is 4.7.*
Xamarin dependency is 4.8.*

housekeeping: Upgraded Xamarin.Forms to v4.8

---

integrationtests/IntegrationTests.XamarinForms.Android/IntegrationTests.XamarinForms.Android.csproj
integrationtests/IntegrationTests.XamarinForms.UWP/IntegrationTests.XamarinForms.UWP.csproj
integrationtests/IntegrationTests.XamarinForms.iOS/IntegrationTests.XamarinForms.iOS.csproj
integrationtests/IntegrationTests.XamarinForms/IntegrationTests.XamarinForms.csproj
src/Directory.build.props
src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
src/ReactiveUI/Bindings/Command/CommandBinderImplementation.cs
src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs
src/ReactiveUI/Expression/Reflection.cs

This PR updates nullability annotations and cherry-picks dependabot dependencies.

fix: Update nullability, pick dependencies

---

nuget.config

fixes github action ci build in line with https://github.com/reactiveui/splat/pull/694
pkg restore failing on ci
enforces nuget.org
n/a

housekeeping: add nuget.config

---

README.md
version.json

housekeeping Update README.md to remove Events

---

README.md

This PR adds a mention of the new Uwp and WinUI packages to README.md file.
Currently, there is no info regarding Uwp and WinUI packages in README.md, and I got a bit confused when upgrading an app.
Now, the docs are added.
Nothing.

housekeeping: Mention new Uwp and WinUI packages

---

src/ReactiveUI.Tests/Routing/RoutingStateTests.cs
src/ReactiveUI/ReactiveCommand/ReactiveCommand.cs
src/ReactiveUI/Routing/RoutingState.cs

fix RoutingState test

---

README.md

This status is no longer valid and shows an invalid image

housekeeping: Remove dependabot status

---

src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.Net4_8.verified.txt
src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj

Fixes https://github.com/reactiveui/ReactiveUI/issues/3084

Fix Rx operators duplicated in net4

---

src/ReactiveUI.Uwp/DependencyObjectObservableForProperty.cs
src/ReactiveUI.WinUI/DependencyObjectObservableForProperty.cs

Possible fix to bug #2669 
Admittedly I have not had time to test yet...but figured I'd put it out there in case anyone wants to pick it up

fix: Pass flags through to notification

---

src/Directory.build.props
src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Fody/ReactiveUI.Fody.csproj
src/ReactiveUI.LeakTests/ReactiveUI.LeakTests.csproj
src/ReactiveUI.Splat.Tests/ReactiveUI.Splat.Tests.csproj
src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet6_0.verified.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_8.verified.txt
src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj
src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj

Fix
Build fails
Build passes
None expected

Fix API Tests and Update Packages

---

src/Directory.build.props
src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.Net4_7.verified.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.Net4_7.verified.txt
src/ReactiveUI.Tests/Platforms/windows-xaml/Api/XamlApiApprovalTests.Blend.Net4_7.verified.txt
src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.Net4_7.verified.txt

fix: verify.xunit

---

integrationtests/IntegrationTests.Android/IntegrationTests.Android.csproj
integrationtests/IntegrationTests.Android/Properties/AndroidManifest.xml
integrationtests/IntegrationTests.Shared.Tests/IntegrationTests.Shared.Tests.csproj
integrationtests/IntegrationTests.XamarinForms.Android/IntegrationTests.XamarinForms.Android.csproj
integrationtests/IntegrationTests.XamarinForms.Android/Properties/AndroidManifest.xml

update
Android projects failing in integration
All projects build
None, only affects integration projects

Housekeeping Update Integration Projects

---

integrationtests/IntegrationTests.Android/MainActivity.cs
integrationtests/IntegrationTests.XamarinForms.Android/Resources/values/styles.xml
integrationtests/IntegrationTests.XamarinForms.UWP/Properties/Default.rd.xml

resolve https://github.com/reactiveui/ReactiveUI/issues/3367
cc @glennawatson

update integrationtests folder links

---

src/ReactiveUI.Blend/Properties/ReactiveUI.Blend_UWP.rd.xml
src/ReactiveUI.Testing/Properties/ReactiveUI.Testing.rd.xml
src/ReactiveUI.Winforms/ObservableCollectionChangedToListChangedTransformer.cs

resolve https://github.com/reactiveui/ReactiveUI/issues/3376

housekeeping: update src folder links

---

.github/workflows/ci-build.yml
.github/workflows/release.yml
src/ReactiveUI/Platforms/apple-common/AppSupportJsonSuspensionDriver.cs

Patch for VS2022 17.3.6
Uses release edition of VS2022
Uses Preview Edition of VS2022

Patch For VS 2022 17.3.6 TVOS bug

---

integrationtests/Directory.Build.props
integrationtests/IntegrationTests.Android/IntegrationTests.Android.csproj
integrationtests/IntegrationTests.Mac/IntegrationTests.Mac.csproj
integrationtests/IntegrationTests.Shared.Tests/IntegrationTests.Shared.Tests.csproj
integrationtests/IntegrationTests.XamarinForms.Android/IntegrationTests.XamarinForms.Android.csproj
src/Directory.build.props
src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.XamForms.Tests/Activation/ActivatingReactivePagesTests.cs
src/ReactiveUI/Platforms/android/ControlFetcherMixin.cs

fix Update
Packages need to be updated with more than one at a time to have a successful build
Packages updated and build issues resolved through correct package versions
none

Update packages fix build

---

src/Directory.build.props
src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
src/ReactiveUI.Drawing/ReactiveUI.Drawing.csproj
src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
src/ReactiveUI.Tests/Routing/RoutingStateTests.cs
src/ReactiveUI.Uwp/ReactiveUI.Uwp.csproj
src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj
src/ReactiveUI/ReactiveUI.csproj

Housekeeping
Using old Targets
Targets updated
updated Targets may affect some users, recommend updating to a newer SDK

Housekeeping Update and Remove Unsupported Targets

---

src/ReactiveUI.AndroidX/ReactiveRecyclerViewViewHolder.cs
src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj

Fix
AndroidX has a Depreciated component
Added Depreciated Tag to code section with warning
None Expected

Housekeeping : Fix warnings

---

src/Directory.build.props
src/ReactiveUI.AndroidX/ReactiveUI.AndroidX.csproj
src/ReactiveUI.Blazor/ReactiveUI.Blazor.csproj
src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj

Dependabot failing to update due to multiple dependencies
Update
Dependabot is failing to update multiple packages with dependencies.
Bulk update packages to resolve conflicts.
none

Housekeeping Update Packages

---

src/Directory.Packages.props
src/ReactiveUI.Testing.Tests/ReactiveUI.Testing.Tests.csproj
src/ReactiveUI.Testing.Tests/xunit.runner.json
src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
src/ReactiveUI.Tests/xunit.runner.json

Fix for XUint tests
Xunit 2.6.6 + fails to pass tests due to parallelism
Using XUnit 2.8.0 with config file setting the parallelAlgorithm to aggressive
none

Fix For Xunit Async Tests

---

src/Directory.Packages.props
src/Directory.build.props
src/ReactiveUI.LeakTests/ReactiveUI.LeakTests.csproj
src/ReactiveUI.Maui/ReactiveUI.Maui.csproj
src/ReactiveUI.Splat.Tests/ReactiveUI.Splat.Tests.csproj
src/ReactiveUI.Testing.Tests/ReactiveUI.Testing.Tests.csproj
src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.DotNet9_0.verified.txt
src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.DotNet9_0.verified.txt
src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet8_0.verified.txt
src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.DotNet9_0.verified.txt
src/ReactiveUI.Tests/Platforms/winforms/API/WinformsApiApprovalTests.Winforms.Net4_7.verified.txt
src/ReactiveUI.Tests/Platforms/winforms/Mocks/FakeWinformsView.cs
src/ReactiveUI.Tests/Platforms/winforms/Mocks/NeverUsedView.cs
src/ReactiveUI.Tests/Platforms/winforms/Mocks/SingleInstanceExampleView.cs
src/ReactiveUI.Tests/Platforms/winforms/Mocks/SingleInstanceWithContractExampleView.cs
src/ReactiveUI.Tests/Platforms/winforms/Mocks/ThirdPartyControl.cs
src/ReactiveUI.Tests/Platforms/wpf/API/WpfApiApprovalTests.Wpf.DotNet9_0.verified.txt
src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj
src/ReactiveUI.Winforms/ReactiveUI.Winforms.csproj
src/ReactiveUI.Winforms/RoutedViewHost.cs
src/ReactiveUI.Winforms/ViewModelViewHost.cs
src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs
src/ReactiveUI/Platforms/android/AutoSuspendHelper.cs
src/ReactiveUI/ReactiveUI.csproj
version.json

update
Supports Net 6
Net 6 retired and added Net 9.0
Users of Net 6.0 will need to migrate to net 8 or net 9

Housekeeping Update to Net 9.0

---

.github/workflows/release.yml

Update release build

---

.github/workflows/release.yml

Update
Release build invalid
Release build updated 
N/A

Housekeeping Update release build

---

src/ReactiveUI.Tests/MessageBusTest.cs
src/ReactiveUI.Tests/RandomTests.cs

Tests update
Added multiple new unit tests to MessageBusTest.cs and RandomTests.cs to increase code coverage. Tests include scenarios for MessageBus contract isolation, scheduler registration, static properties, and various attribute and type converter behaviors. Also added tests for mixins, helpers, and static members to ensure all major code paths are exercised.
N/A

Add comprehensive unit tests for coverage improvement
